(function(){
'use strict';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const unit=(x,y)=>{const l=Math.hypot(x,y)||1;return {x:x/l,y:y/l}};
const ROLES=['GK','LB','CB','CB','RB','LM','CM','CM','RM','ST','ST'];
const HOMES=[[4,31],[20,8],[18,23],[18,39],[20,54],[38,7],[36,24],[36,39],[38,55],[57,23],[57,39]];
// One input per human. Logical keys stay arrowup/…/z/x/c/v whatever the device: keyboard layout or a gamepad index.
const KEYMAPS={arrows:{arrowup:'arrowup',arrowdown:'arrowdown',arrowleft:'arrowleft',arrowright:'arrowright',z:'z',x:'x',c:'c',v:'v',r:'r',d:'d'},
 wasd:{w:'arrowup',s:'arrowdown',a:'arrowleft',d:'arrowright',j:'z',l:'x',k:'c',i:'v'}};
KEYMAPS.arrowsPlay={...KEYMAPS.arrows};delete KEYMAPS.arrowsPlay.r;delete KEYMAPS.arrowsPlay.d;
const PADMAP={0:'z',1:'c',2:'x',3:'v',4:'c',5:'v',7:'z',12:'arrowup',13:'arrowdown',14:'arrowleft',15:'arrowright'};
class InputManager {
 constructor(options={}){this.active=false;this.down=new Set();this.pressed=new Set();this.shotBuffer=0;this.shotPower=null;this.shotHeld=0;this.shotCharging=false;
 this.keymap=options.keys===null?null:KEYMAPS[options.keys||'arrows'];this.pads=options.pads||null;this.sources=new Map();
 this.onDown=e=>{if(!this.active||!this.keymap)return;const k=this.keymap[(e.key||'').toLowerCase()];if(!k)return;e.preventDefault();if(e.repeat)return;this.press(k,'kb')};
 this.onUp=e=>{if(!this.keymap)return;const k=this.keymap[(e.key||'').toLowerCase()];if(k)this.release(k,'kb')};
 this.onBlur=()=>{this.down.clear();this.pressed.clear();this.sources.clear();this.cancelShot()};addEventListener('keydown',this.onDown);addEventListener('keyup',this.onUp);addEventListener('blur',this.onBlur);}
 press(k,source='kb'){const held=this.sources.get(k)||new Set();this.sources.set(k,held);if(held.has(source))return;held.add(source);if(this.down.has(k))return;this.down.add(k);
  if(k==='z'&&this.context?.phase==='PENALTIES'&&this.context.pen?.stage==='result'){this.pressed.add(k);return}if(k==='z'){this.shotCharging=true;this.shotHeld=0;this.shotBuffer=0;this.shotPower=null}else this.pressed.add(k)}
 release(k,source='kb'){const held=this.sources.get(k);if(held){held.delete(source);if(held.size)return}if(k==='z'&&this.active&&this.shotCharging){this.shotPower=Math.min(1,this.shotHeld/.85);this.shotBuffer=.28;this.pressed.add('z');this.shotCharging=false}this.down.delete(k)}
 // Gamepads are read directly (standard mapping, left stick or d-pad) so several pads can drive several humans.
 poll(){if(!this.pads||!this.active||typeof navigator==='undefined'||!navigator.getGamepads)return;const list=[...(navigator.getGamepads()||[])].filter(Boolean),pads=this.pads==='all'?list:list.filter(p=>this.pads.includes(p.index)),now=new Set();
  for(const pad of pads){pad.buttons.forEach((b,i)=>{if((b.pressed||b.value>.5)&&PADMAP[i])now.add(PADMAP[i])});const [x=0,y=0]=pad.axes;if(x<-.45)now.add('arrowleft');if(x>.45)now.add('arrowright');if(y<-.45)now.add('arrowup');if(y>.45)now.add('arrowdown')}
  const before=this.padDown||new Set();for(const k of now)if(!before.has(k))this.press(k,'pad');for(const k of before)if(!now.has(k))this.release(k,'pad');this.padDown=now}
 cancelShot(clearPressed=true){this.shotCharging=false;this.shotHeld=0;this.shotPower=null;this.shotBuffer=0;if(clearPressed)this.pressed.delete('z')}
 get shotCharge(){return this.shotCharging?Math.min(1,this.shotHeld/.85):this.shotPower||0}

 dispose(){this.active=false;removeEventListener('keydown',this.onDown);removeEventListener('keyup',this.onUp);removeEventListener('blur',this.onBlur);this.onBlur();}

 axis(){return unit(Number(this.down.has('arrowright'))-Number(this.down.has('arrowleft')),Number(this.down.has('arrowdown'))-Number(this.down.has('arrowup')))}
 take(k){const yes=this.pressed.has(k);this.pressed.delete(k);return yes}
 end(dt){if(this.active&&this.shotCharging)this.shotHeld=Math.min(.85,this.shotHeld+dt);this.shotBuffer=Math.max(0,this.shotBuffer-dt);if(!this.shotCharging&&!this.shotBuffer)this.shotPower=null;this.pressed.clear()}
}
InputManager.KEYMAPS=KEYMAPS;InputManager.PADMAP=PADMAP;
class Player {
 constructor(team,i){this.team=team;this.number=i+1;this.role=ROLES[i];this.home={x:team.id?100-HOMES[i][0]:HOMES[i][0],y:HOMES[i][1]};this.reset()}
 reset(){Object.assign(this,{x:this.home.x,y:this.home.y,vx:0,vy:0,face:{x:this.team.dir,y:0},target:{...this.home},receiverIntent:null,receiveState:'none',action:'idle',actionTime:0,visualKickFace:null,recovery:0,burst:0,specialCooldown:0,stun:0,aiWait:1,cpuSettle:0,tackleHit:false});}
 move(dx,dy,dt,speed=14){speed*=(.7+(this.attributes?.speed??75)/250)*(.94+(this.morale??65)/1000);if(this.stun>0||this.recovery>0)return;const n=unit(dx,dy);this.vx=n.x*speed;this.vy=n.y*speed;this.x+=this.vx*dt;this.y+=this.vy*dt;if(dx||dy){this.face=n;if(this.actionTime<=0)this.action='run'}else if(this.actionTime<=0)this.action='idle';this.x=clamp(this.x,-1,101);this.y=clamp(this.y,-1,63)}
 tick(dt){const wasStunned=this.stun;for(const k of ['actionTime','recovery','burst','specialCooldown','stun','aiWait','cpuSettle'])this[k]=Math.max(0,this[k]-dt);if(wasStunned>0&&this.stun===0){this.action='getup';this.actionTime=.28}this.vx=this.vy=0;if(!this.actionTime&&['pass','shoot','volley','getup'].includes(this.action))this.action='idle';if(this.actionTime===0&&this.action==='tackle'){this.recovery=this.hard?.38:.18;this.action='idle';}}
 tackle(hard){if(this.recovery||this.actionTime||this.stun)return;this.action='tackle';this.actionTime=hard?.42:.3;this.hard=hard;this.tackleHit=false;}
}
class Goalkeeper extends Player {
 update(match,dt){const b=match.ball,ownX=this.team.id?97:3,near=Math.abs(b.x-ownX)<14&&Math.abs(b.y-31)<17,incoming=!b.owner&&b.state==='shot'&&b.vx*this.team.dir<0,intercept=incoming?(b.flight>.12?b.y+b.vy*clamp((ownX-b.x)/b.vx,0,1.2):this.y):b.y;
 if(b.owner!==this&&this.keeperState==='GK_DIVING'&&this.actionTime>0){this.vx=this.vy=0;return}this.keeperState=near&&!b.owner&&!incoming?'GK_RUSHING':'GK_POSITIONING';this.target={x:near&&!b.owner&&!incoming?clamp(b.x,this.team.id?86:2,this.team.id?98:14):ownX,y:clamp(intercept,incoming?25:23,incoming?37:39)};
 if(b.owner!==this){const dx=this.target.x-this.x,dy=this.target.y-this.y,d=Math.hypot(dx,dy);if(d>.22)this.move(dx,dy,dt,Math.min(near?17:10,d/Math.max(dt,.001)/1.2));else{this.vx=this.vy=0;if(!this.actionTime)this.action='idle'}this.face={x:this.team.dir,y:0}}
 if(b.owner===this){this.keeperState='GK_HOLDING';this.action='keeper';if(this.aiWait<=0){this.keeperState='GK_DISTRIBUTING';match.pass(this,match.players.some(p=>p.team!==this.team&&distance(p,this)<12));}return}
 const smother=b.owner&&b.owner.team!==this.team&&b.controlMode==='FEET'&&distance(this,b.owner)<2.2;
 const ownPlay=!b.owner&&b.lastTeam===this.team.id&&b.state!=='shot'&&!(b.state==='rebound'&&b.flight>.6);if((!b.owner||smother)&&!ownPlay&&(b.lock<=0||incoming&&b.flight>.1)&&b.z<6&&distance(this,b)<(incoming?1.25+(this.attributes?.goalkeeping??75)/125:2.5+(this.attributes?.goalkeeping??75)/80)){match.stats.teams[this.team.id].saves++;this.action='keeper';this.actionTime=.4;if(b.z<(match.teamHasHumans(this.team)?3.2:2.5)&&Math.hypot(b.vx,b.vy)<43+((this.attributes?.goalkeeping??75)-75)*.4+(match.teamHasHumans(this.team)?14:0)){this.keeperState='GK_CATCHING';match.control(this);this.aiWait=2.5}else{this.keeperState='GK_DIVING';const choices=[-1,1].map(side=>{const spot={x:clamp(this.x+this.team.dir*12,2,98),y:clamp(this.y+side*14,5,57)},enemies=match.players.filter(p=>p.team!==this.team&&!p.sentOff),friends=match.players.filter(p=>p.team===this.team&&p!==this&&!p.sentOff);return {side,score:Math.min(...enemies.map(p=>distance(p,spot)))-Math.min(...friends.map(p=>distance(p,spot)))*.5}}).sort((a,b)=>b.score-a.score);// Hard or rising shots are often tipped over the bar: the ball goes out behind the line for a corner.
 const tip=Math.hypot(b.vx,b.vy)>46&&(b.z>1.4||match.stats.teams[this.team.id].saves%2===0);if(tip){b.kick(this,-this.team.dir*6,choices[0].side*5,18,'rebound');b.lock=.9;match.say('IN CORNER!',.9)}else{b.kick(this,this.team.dir*22,choices[0].side*18,3.5,'rebound');match.say('PARATA!',.7)}}}
 }
}
class Team {
 constructor(id){this.id=id;this.dir=id?-1:1;this.name=id?'CRIMSON FC':'NEON UNITED';this.state='LOOSE_BALL';this.players=ROLES.map((_,i)=>i?new Player(this,i):new Goalkeeper(this,i));this.ai=new TeamAI(this);}
}
class Ball {
 constructor(){this.reset()}
 reset(){Object.assign(this,{x:50,y:31,z:0,vx:0,vy:0,vz:0,owner:null,controlMode:'FREE',canBeStolen:true,state:'loose',lastTeam:0,passTarget:null,lock:0,flight:0})}
 kick(p,vx,vy,vz,state,target=null){this.controlMode='FREE';this.canBeStolen=true;this.owner=null;this.x=p.x+p.face.x*1.2;this.y=clamp(p.y+p.face.y*1.2,.2,61.8);this.vx=vx;this.vy=vy;this.vz=vz;this.z=state==='aerial'?2:Math.max(this.z,.2);this.state=state;this.lastTeam=p.team.id;this.passTarget=target;this.lock=.16;this.flight=0;p.action='kick';p.actionTime=.22;}
 update(dt){this.lock=Math.max(0,this.lock-dt);this.flight+=dt;if(this.owner){this.x=this.owner.x+this.owner.face.x*1.15;this.y=this.owner.y+this.owner.face.y*1.15;this.z=this.controlMode==='HANDS'?2.5:0;return}this.x+=this.vx*dt;this.y+=this.vy*dt;this.z+=this.vz*dt;this.vz-=24*dt;if(this.z<0){this.z=0;this.vz=Math.abs(this.vz)>3?-this.vz*.43:0;if(this.state==='aerial')this.state='rebound'}const f=Math.exp(-(this.z>.1?.12:.6)*dt);this.vx*=f;this.vy*=f;if(Math.hypot(this.vx,this.vy)<2&&!this.passTarget)this.state='loose';}
}
class TeamAI {
 constructor(team){this.team=team}
 update(m,dt){const t=this.team,b=m.ball,own=b.owner?.team===t,opponent=!!b.owner&&!own;
 t.state=own?(m.transition>0?'TRANSITION_ATTACK':'ATTACKING'):opponent?(m.transition>0?'TRANSITION_DEFEND':'DEFENDING'):'LOOSE_BALL';
 const active=t.players.filter(p=>!p.sentOff),ranked=active.filter(p=>p.role!=='GK').sort((a,c)=>distance(a,b)-distance(c,b)),chasers=ranked.filter(p=>!m.isControlled(p)).slice(0,2),danger=!own&&(t.id?b.x>72:b.x<28)&&Math.abs(b.y-31)<25,cover=ranked.filter(p=>!m.isControlled(p)&&['LB','CB','RB','CM'].includes(p.role)).slice(0,4),cpu=t.cpu||{},pace=cpu.pace||1;
 for(const p of active){if(p.role==='GK'){if(!m.isControlled(p)||b.owner!==p)p.update(m,dt);continue}if(m.isControlled(p))continue;
 let tx=p.home.x,ty=p.home.y;const attacking=own||(!opponent&&b.lastTeam===t.id);const local=t.id?100-b.x:b.x;
 const tactical=t.mentality==='Offensivo'?4:t.mentality==='Difensivo'?-4:0;const shift=tactical+(attacking?clamp(local*.32-4,0,23):clamp((local-50)*.24,-10,10));tx+=shift*t.dir;
 ty=clamp(p.home.y+(b.y-31)*.18+Math.sin(m.elapsed*1.8+p.number)*2.1,3,59);
 if(attacking){if(p.role==='ST')tx+=t.dir*(m.transition>0?10:5);if(['LM','RM','LB','RB'].includes(p.role))ty=p.home.y<31?5:57;if(p.role==='CM')tx+=t.dir*Math.sin(m.elapsed*1.3+p.number)*5;}
 if(opponent&&b.controlMode!=='HANDS'&&p===chasers[0]){tx=b.owner.x;ty=b.owner.y} else if(opponent&&b.controlMode!=='HANDS'&&p===chasers[1]){tx=b.x-t.dir*5;ty=b.y+(p.home.y<31?-4:4)}
 if(!b.owner&&chasers.includes(p)){tx=b.x+b.vx*.12;ty=b.y+b.vy*.12}
 if(danger&&cover.includes(p)&&!chasers.includes(p)){const slot=cover.indexOf(p);tx=clamp(b.x-t.dir*5,t.id?76:5,t.id?95:24);ty=clamp(31+(slot%2?-5:5),7,55)}
 if(b.passTarget===p){p.receiveState='approaching';const predicted=b.state==='aerial'&&p.receiverIntent?p.receiverIntent:{x:b.x+b.vx*.15,y:b.y+b.vy*.15};tx=predicted.x;ty=predicted.y;p.receiverIntent={x:tx,y:ty};}
 if(opponent&&b.controlMode==='HANDS'&&distance(p,b.owner)<7){tx=b.owner.x-t.dir*8;ty=b.owner.y+(p.home.y<31?-6:6)}
 p.target={x:clamp(tx,2,98),y:clamp(ty,2,60)};
 if(b.owner===p){if(p.cpuSettle>0)p.move(0,0,dt);else p.move(t.dir*16,clamp(31-p.y,-8,8),dt,(m.teamHasHumans(t)?12:9)*pace);if(p.aiWait<=0){const shootingZone=(t.id?p.x<24:p.x>76)&&Math.abs(p.y-31)<16;if(shootingZone)m.shoot(p);else m.pass(p);p.aiWait=shootingZone?1.65:1.1;} }
 else {if(distance(p,p.target)>.6)p.move(p.target.x-p.x,p.target.y-p.y,dt,13*pace);if(opponent&&b.canBeStolen&&distance(p,b.owner)<3&&p.aiWait<=0){p.tackle(false);p.aiWait=(m.isControlled(b.owner)?1.5:.9)*(cpu.tackleWait||1);}}
 }
 }
}
class MatchRules {
 constructor(m){this.m=m;this.remaining=120;this.period='REGULAR';this.goldenRemaining=30;this.score=[0,0];}
 leader(){const score=this.score.map((v,i)=>v+(this.offset?.[i]||0));if(score[0]===score[1]&&this.awayGoals){const away=this.awayGoals.map((v,i)=>v===null?this.score[i]:v);if(away[0]!==away[1])return away[0]>away[1]?0:1}return score[0]===score[1]?null:score[0]>score[1]?0:1}
 update(dt){if(this.m.phase!=='PLAY')return;if(this.period==='REGULAR'){this.remaining=Math.max(0,this.remaining-dt);if(!this.remaining){if(this.allowDraw||this.leader()!==null)this.finish();else{this.period='GOLDEN';this.m.restarts.kickoff(0);this.m.pass(this.m.ball.owner);this.m.phase='PLAY';this.m.restarts.data=null;this.m.say('GOLDEN GOAL!',2)}}}else if(this.period==='GOLDEN'){this.goldenRemaining=Math.max(0,this.goldenRemaining-dt);if(!this.goldenRemaining)this.m.startPenalties()}}
 goal(team){this.score[team]++;const p=this.m.lastShooter;this.m.scorers.push({team,playerId:p?.team.id===team?p.source?.id:undefined,name:p?.source?.name,assistId:this.m.lastAssist?.source?.id,minute:Math.round((120-this.remaining)/120*90)});this.m.say('GOAL!',2);if(this.period==='GOLDEN')this.finish();else this.m.restarts.kickoff(1-team,1.8)}
 finish(){this.m.phase='FINISHED';if(this.leader()!==null)this.m.teams[this.leader()].players.forEach(p=>{p.action='celebrate';p.actionTime=999});this.m.say(this.leader()===null?'PAREGGIO':this.m.teams[this.leader()].name+' VINCE!',999)}
}
class RestartManager {
 constructor(m){this.m=m;this.data=null}
 kickoff(team,delay=0){const m=this.m;m.players.forEach(p=>{p.reset();if(p.role!=='GK')p.x=team===p.team.id?(p.team.id?Math.max(52,p.x):Math.min(48,p.x)):(p.team.id?Math.max(53,p.x):Math.min(47,p.x))});for(const p of m.players){if(p.team.id===team||p.role==='GK')continue;const dx=p.x-50,dy=p.y-31,d=Math.hypot(dx,dy);if(d<10){const n=d>.001?unit(dx,dy):{x:p.team.dir*-1,y:0};p.x=50+n.x*10;p.y=31+n.y*10}}m.ball.reset();const taker=m.teams[team].players.find(p=>!p.sentOff&&p.role==='ST')||m.teams[team].players.find(p=>!p.sentOff&&p.role!=='GK');taker.x=50;taker.y=31;const support=m.teams[team].players.find(p=>!p.sentOff&&p!==taker&&p.role==='ST')||m.teams[team].players.find(p=>!p.sentOff&&p!==taker&&p.role!=='GK');if(support){support.x=team?54:46;support.y=34;}m.control(taker);m.phase='RESTART';this.data={type:'KICKOFF',team,taker,support,delay,age:0};}
 award(type,team,x,y){const m=this.m;m.phase='RESTART';m.ball.reset();const t=m.teams[team];const taker=type==='GOAL KICK'?t.players.find(p=>!p.sentOff&&p.role==='GK'):t.players.filter(p=>!p.sentOff&&p.role!=='GK').sort((a,b)=>distance(a,{x,y})-distance(b,{x,y}))[0];taker.x=x;taker.y=type==='THROW IN'?(y<31?-.25:62.25):y;taker.face={x:t.dir,y:y<31?1:-1};m.control(taker);if(type==='THROW IN'){m.ball.controlMode='HANDS';m.ball.canBeStolen=false}this.data={type,team,taker,delay:.65,age:0};m.say(type,1.2);
 for(const p of m.players){if(p===taker)continue;if(type==='CORNER'){p.target={x:team?12:88,y:18+(p.number*7)%27};p.x=p.target.x+(p.team.id===team?0:team?-3:3);p.y=p.target.y;}else{p.target={x:clamp(x+(p.team.id===team?t.dir*10:-t.dir*8),5,95),y:clamp(y<31?12+(p.number*4)%35:50-(p.number*4)%35,3,59)};}}
 }
 update(dt){const m=this.m,d=this.data;if(!d)return;d.age+=dt;d.delay=Math.max(0,d.delay-dt);if(d.type!=='KICKOFF')for(const p of m.players)if(p!==d.taker&&distance(p,p.target)>.8)p.move(p.target.x-p.x,p.target.y-p.y,dt,9);
 const h=m.humanOf(d.taker);if(d.delay)return;
 if(h){m.as(h,()=>{if(d.type!=='THROW IN'&&d.type!=='KICKOFF'&&m.input.take('z')){m.shoot(d.taker);this.release();return}const high=m.input.take('x');if(high||m.input.take('c'))this.take(high)})}else if(d.age>1.2)this.take(false);
 }
 take(high){const m=this.m,d=this.data;if(d.type==='THROW IN')d.taker.throwAt=m.elapsed;if(d.type==='CORNER')m.pass(d.taker,true);else m.pass(d.taker,high||d.type==='THROW IN');this.release()}
 release(){this.m.phase='PLAY';this.data=null}
}
class Match {
 constructor(input){this.humans=[{slot:0,team:0,input,selected:null,selectionTimer:0,label:'1P',color:'#ffec54'}];this.cur=null;input.context=this;this.scorers=[];this.debug=false;this.reset()}
 // Human controllers (1–4). selected/input/selectionTimer resolve to the human being processed (or 1P outside a human step).
 get human(){return this.cur||this.humans[0]}
 get selected(){return this.human.selected}set selected(v){this.human.selected=v}
 get input(){return this.human.input}set input(v){this.human.input=v}
 get selectionTimer(){return this.human.selectionTimer}set selectionTimer(v){this.human.selectionTimer=v}
 as(h,fn){const prev=this.cur;this.cur=h;try{return fn()}finally{this.cur=prev}}
 humansOf(team){const id=team?.id??team;return this.humans.filter(h=>h.team===id)}
 teamHasHumans(team){return this.humansOf(team).length>0}
 humanOf(p){return p?this.humans.find(h=>h.selected===p)||null:null}
 isControlled(p){return !!this.humanOf(p)}
 setHumans(list){const colors=['#ffec54','#5ff0ff','#7dff6a','#ff7ad9'];this.humans=list.map((h,i)=>({slot:i,team:h.team,input:h.input,label:h.label||(i+1)+'P',color:h.color||colors[i],selected:null,selectionTimer:0}));for(const h of this.humans)h.input.context=this;this.assignIdle();this.restarts.kickoff(0)}
 // Every human holds a distinct outfield player of his own team.
 assignIdle(){for(const h of this.humans){if(h.selected&&!h.selected.sentOff&&h.selected.team.id===h.team&&this.humans.every(o=>o===h||o.selected!==h.selected))continue;const taken=this.humans.filter(o=>o!==h).map(o=>o.selected),b=this.ball,pool=this.teams[h.team].players.filter(p=>!p.sentOff&&p.role!=='GK'&&!taken.includes(p)).sort((a,c)=>distance(a,b)-distance(c,b));h.selected=pool[0]||this.teams[h.team].players.find(p=>!p.sentOff)}}
 // A teammate gaining the ball goes to the human who passed it, else to the closest human of that team.
 assignControl(p){if(this.isControlled(p))return;const mates=this.humansOf(p.team);if(!mates.length)return;const passer=mates.find(h=>h.selected===this.lastPasser);(passer||mates.slice().sort((a,c)=>distance(a.selected||p,p)-distance(c.selected||p,p))[0]).selected=p}
 reset(){this.teams=[new Team(0),new Team(1)];this.players=this.teams.flatMap(t=>t.players);this.ball=new Ball();this.rules=new MatchRules(this);this.restarts=new RestartManager(this);this.stats={teams:[0,1].map(()=>({shots:0,passes:0,tackles:0,saves:0,possessionSeconds:0}))};this.scorers=[];this.lastShooter=null;this.lastPasser=null;this.lastAssist=null;this.elapsed=0;this.transition=0;for(const h of this.humans){h.selected=null;h.selectionTimer=0}this.assignIdle();this.message='C / X • CALCIO D’INIZIO';this.messageTime=2;this.restarts.kickoff(0);}
 say(s,t=1){this.message=s;this.messageTime=t}
 control(p){const b=this.ball;const old=b.owner?.team.id??b.lastTeam;if(old!==p.team.id){this.transition=1.6;this.lastPasser=null;}b.owner=p;b.controlMode=p.role==='GK'?'HANDS':'FEET';b.canBeStolen=p.role!=='GK';b.state='controlled';b.lastTeam=p.team.id;b.passTarget=null;b.vx=b.vy=b.vz=b.z=0;p.receiveState='controlled';p.receiverIntent=null;p.aiWait=Math.max(p.aiWait||0,this.teamHasHumans(p.team)?.65:1.1+(p.team.cpu?.react||0));p.cpuSettle=.28;this.assignControl(p);}
 chooseTarget(p,aerial=false){const restart=this.restarts.data;if(restart?.type==='KICKOFF'&&restart.taker===p&&restart.support&&!restart.support.sentOff)return restart.support;const candidates=p.team.players.filter(q=>!q.sentOff&&q!==p&&q.role!=='GK');return candidates.sort((a,b)=>{const score=q=>{const d=distance(p,q),n=unit(q.x-p.x,q.y-p.y),aim=aerial&&p===this.selected?this.input.axis():{x:0,y:0},face=Math.hypot(aim.x,aim.y)?aim:p.face,dot=n.x*face.x+n.y*face.y;return (dot>.25?100:dot>-.4?45:0)+dot*22-d*.8+q.team.dir*(q.x-p.x)*.15};return score(b)-score(a)})[0]}
 pass(p,aerial=false){if(p===this.selected)this.input.cancelShot();const q=this.chooseTarget(p,aerial);if(!q)return;if(this.restarts.data?.type==='KICKOFF'){q.x=p.team.id?55:45;q.y=34;q.vx=q.vy=0;}this.stats.teams[p.team.id].passes++;this.lastPasser=p;const b=this.ball,speed=36+(p.attributes?.passing??70)*.1;const travel=distance(p,q)/speed;let tx=clamp(q.x+q.vx*travel*.65,2,98),ty=clamp(q.y+q.vy*travel*.65,2,60);if(this.restarts.data?.type==='CORNER'){tx=p.team.id?10:90;ty=31}let launchSpeed=speed,lift=1.8;if(aerial){const flight=clamp(distance(p,q)/32,.65,1.65);tx=clamp(q.x+q.vx*flight*.35,2,98);ty=clamp(q.y+q.vy*flight*.35,2,60);if(this.restarts.data?.type==='CORNER'){tx=q.x;ty=q.y}const range=Math.max(.5,Math.hypot(tx-p.x,ty-p.y)-1.2);launchSpeed=range*.12/(1-Math.exp(-.12*flight));lift=(12*flight*flight-2)/flight;}const n=unit(tx-p.x,ty-p.y);p.face=n;b.kick(p,n.x*launchSpeed,n.y*launchSpeed,lift,aerial?'aerial':'pass',q);q.receiverIntent={x:tx,y:ty};q.receiveState='running';p.visualKickFace={...n};p.action='pass';p.actionTime=.3;this.say(aerial?'CROSS!':'PASS!',.45);}
 shoot(p,volley=false,power=null){if(!p||p.sentOff)return;this.stats.teams[p.team.id].shots++;this.lastAssist=this.lastPasser&&this.lastPasser!==p&&this.lastPasser.team===p.team?this.lastPasser:null;this.lastShooter=p;
 const human=p===this.selected&&this.isControlled(p);if(power===null&&human&&this.input.shotBuffer>0)power=this.input.shotPower;
 const charge=power===null?null:clamp(power,0,1),strength=charge===null?1:(.85+(p.attributes?.shotPower??75)/500),speed=(volley?68:55)*(.8+(p.attributes?.shooting??75)/375)*(charge===null?1:.68+.52*charge)*strength;
 const b=this.ball,goalX=p.team.id?-3:103,range=Math.hypot(goalX-p.x,31-p.y),pressure=this.players.some(q=>q.team!==p.team&&!q.sentOff&&q.role!=='GK'&&distance(q,p)<4.5),spread=2+(100-(p.attributes?.shooting??75))*.075+range*.12+Math.abs(p.y-31)*.1+(pressure?3.5:0)+(p.team.cpu?.aimError||0),cpuAim=31+Math.sin(this.stats.teams[p.team.id].shots*2.399963+p.number*.73)*spread,aim=human?clamp(31+this.input.axis().y*5+Math.sin(this.elapsed*7)*(volley?2.8:.8),25,37):cpuAim,n=unit(goalX-p.x,aim-p.y);p.face=n;b.kick(p,n.x*speed,n.y*speed,volley?7:charge===null?4:2.8+charge*2.2,'shot');p.visualKickFace={...n};p.action=volley?'volley':'shoot';p.actionTime=volley?.3:.32;
 this.lastShot={player:p,charge:charge??.6,speed,aim,time:this.elapsed};if(human)this.input.cancelShot();this.say(volley?'VOLLEY!':charge!==null&&charge>.85?'POWER SHOT!':'SHOOT!',.6);}

 selection(dt){const h=this.human,T=h.team;h.selectionTimer-=dt;const b=this.ball;if(!h.selected||h.selected.sentOff)this.assignIdle();if(b.owner?.team.id===T)return;if(b.passTarget?.team.id===T)return;if(h.selectionTimer>0||h.selected.actionTime>0)return;const taken=this.humans.filter(o=>o!==h).map(o=>o.selected),target=this.teams[T].players.filter(p=>!p.sentOff&&p.role!=='GK'&&!taken.includes(p)).sort((a,c)=>distance(a,b)-distance(c,b))[0];if(target&&target!==h.selected&&distance(target,b)+1.2<distance(h.selected,b)){h.selected=target;h.selectionTimer=.25}}
 collisions(){for(let i=0;i<this.players.length;i++)for(let j=i+1;j<this.players.length;j++){const a=this.players[i],b=this.players[j],d=distance(a,b);if(d<1.75){const n=d>.001?unit(a.x-b.x,a.y-b.y):{x:1,y:0};const overlap=(1.75-d)*.5;a.x+=n.x*overlap;a.y+=n.y*overlap;b.x-=n.x*overlap;b.y-=n.y*overlap;}}}
 tackles(dt){for(const p of this.players){if(p.action!=='tackle'||p.actionTime<=0)continue;const before={x:p.x,y:p.y};p.x=clamp(p.x+p.face.x*(p.hard?28:21)*dt,.5,99.5);p.y=clamp(p.y+p.face.y*(p.hard?28:21)*dt,.5,61.5);const b=this.ball,o=b.owner;if(!o||!b.canBeStolen||o.team===p.team||p.tackleHit)continue;const n=unit(o.x-p.x,o.y-p.y),human=this.isControlled(p);if(distance(p,o)<((p.hard?2.6:1.9)+(p.attributes?.defending??75)/125+(human?.7:0)-(p.team.cpu?.reach||0))&&n.x*p.face.x+n.y*p.face.y>(human?-.5:-.15)){if(this.shielded?.(p,o)){p.tackleHit=true;this.say('PALLA PROTETTA!',.45);continue}p.tackleHit=true;this.stats.teams[p.team.id].tackles++;o.stun=p.hard?.45:.2;p.x=before.x;p.y=before.y;if(p.hard||o.burst>0){b.kick(o,p.face.x*22,p.face.y*22,4,'rebound');b.lastTeam=p.team.id;}else this.control(p);this.say(p.hard?'POWER TACKLE!':'TACKLE!',.5)}}}
 receive(){const b=this.ball;if(b.owner||b.lock>0)return;for(const p of [...this.players].sort((a,c)=>distance(a,b)-distance(c,b))){if(p.sentOff||p.role==='GK'||p.stun>0||p.recovery>0)continue;const d=distance(p,b);const ph=this.humanOf(p);if(ph&&ph.input.shotBuffer>0&&d<3.5&&b.z>.6&&b.z<6){this.as(ph,()=>this.shoot(p,true));return}if(b.z>1.8||d>1.5+(p.attributes?.control??75)/150)continue;if(b.passTarget&&p.team.id===b.lastTeam&&p!==b.passTarget&&b.flight<1.8)continue;this.control(p);const owner=this.humanOf(p);if(owner&&owner.input.shotBuffer>0)this.as(owner,()=>this.shoot(p));return}if(b.flight>2.2){if(b.passTarget)b.passTarget.receiveState='none';b.passTarget=null;}}
 boundaries(){const b=this.ball;if(b.owner){if(b.controlMode==='HANDS'||b.x>=0&&b.x<=100&&b.y>=0&&b.y<=62)return;b.lastTeam=b.owner.team.id;b.owner=null;b.controlMode='FREE';b.canBeStolen=true;}if(b.x<0||b.x>100){const right=b.x>100;if(b.y>25&&b.y<37&&b.z<5){this.rules.goal(right?0:1);return}const defending=right?1:0;if(b.lastTeam===defending)this.restarts.award('CORNER',1-defending,right?99.5:.5,b.y<31?.5:61.5);else this.restarts.award('GOAL KICK',defending,right?94:6,31);}else if(b.y<0||b.y>62)this.restarts.award('THROW IN',1-b.lastTeam,clamp(b.x,2,98),b.y<0?0:62);}
 startPenalties(){this.phase='PENALTIES';this.rules.period='PENALTIES';this.pen={turn:0,history:[[],[]],kicks:[0,0],goals:[0,0],age:0,flight:false};this.setupPenalty();}
 setupPenalty(){const team=this.pen.turn%2;this.players.forEach(p=>{p.reset();p.x=45;p.y=8+p.number*3});const p=this.teams[team].players.find(p=>!p.sentOff&&p.role==='ST')||this.teams[team].players.find(p=>!p.sentOff&&p.role!=='GK');p.x=team?18:82;p.y=31;p.face={x:this.teams[team].dir,y:0};const g=this.teams[1-team].players.find(p=>!p.sentOff&&p.role==='GK');g.x=team?2:98;g.y=31;this.selected=team===0?p:this.teams[0].players.find(p=>!p.sentOff&&p.role==='GK');this.ball.reset();this.control(p);this.pen.age=0;this.pen.flight=false;this.say(team===0?'RIGORE • FRECCE + Z':'PARA • FRECCE',1.6);}
 penalties(dt){const pen=this.pen;pen.age+=dt;const team=pen.turn%2,g=this.teams[1-team].players.find(p=>!p.sentOff&&p.role==='GK');if(!pen.flight){const axis=this.input.axis();const dive=axis.x||axis.y;g.y=clamp(g.y+(team===1?dive*(10+(g.attributes?.goalkeeping??75)/10):Math.sin(this.elapsed*3)*9)*dt,25,37);g.keeperState=dive?'GK_DIVING':'GK_POSITIONING';if(team===0?this.input.take('z'):pen.age>1.4){this.shoot(this.ball.owner);if(team===0){const a=this.input.axis();const aim=a.x?31+a.x*5:31;const n=unit((team?-3:103)-this.ball.x,aim-this.ball.y);const speed=this.lastShot.speed;this.ball.vx=n.x*speed;this.ball.vy=n.y*speed;this.ball.vz=a.y<0?12:2;}if(team===1)this.ball.vy=Math.sin(this.elapsed*4)*9;pen.flight=true;pen.age=0}}else{const axis=this.input.axis();if(team===1&&pen.age>.1+(100-(g.attributes?.goalkeeping??75))/1000&&(axis.x||axis.y)){g.y=clamp(g.y+(axis.x||axis.y)*(10+(g.attributes?.goalkeeping??75)/10)*dt,25,37);g.keeperState='GK_DIVING'}this.ball.update(dt);const b=this.ball;let result=null;if(distance(b,g)<(2+(g.attributes?.goalkeeping??75)/80)&&b.z<(g.keeperState==='GK_DIVING'?5:3)){result=false;g.action='keeper';g.actionTime=.5}else if(b.x<0||b.x>100)result=b.y>25&&b.y<37&&b.z<5;else if(pen.age>2.5)result=false;if(result!==null){pen.history[team].push(result);pen.kicks[team]++;if(result)pen.goals[team]++;pen.turn++;this.say(result?'GOOOL!':'PARATO / FUORI',.8);const remaining=pen.kicks.map(n=>Math.max(0,5-n));if(window.S9ArcadeEngine.PenaltyManager.decided(pen.kicks,pen.goals)){this.phase='FINISHED';this.say(this.teams[pen.goals[0]>pen.goals[1]?0:1].name+' VINCE AI RIGORI!',999)}else this.setupPenalty();}}}
 update(dt){const first=this.humans[0].input;if(this.debug&&first.take('r'))this.reset();if(first.keymap?.d==='d'&&first.take('d'))this.debug=!this.debug;this.elapsed+=dt;this.messageTime-=dt;this.transition=Math.max(0,this.transition-dt);this.players.forEach(p=>p.tick(dt));if(this.phase==='FINISHED')return;if(this.phase==='PENALTIES'){this.penalties(dt);return}if(this.phase==='RESTART'){this.restarts.update(dt);this.ball.update(0);return}if(this.ball.owner)this.stats.teams[this.ball.owner.team.id].possessionSeconds+=dt;
 for(const h of this.humans)this.as(h,()=>this.humanStep(dt));
 // Keeper holding the ball: opponents keep their distance, so the release cannot be volleyed straight back in.
 const keeper=this.ball.owner;if(keeper?.role==='GK'&&this.ball.controlMode==='HANDS')for(const q of this.players){if(q.team===keeper.team||q.sentOff)continue;const d=distance(q,keeper);if(d<7){const n=d>.01?unit(q.x-keeper.x,q.y-keeper.y):{x:keeper.team.dir,y:0};q.x=keeper.x+n.x*7;q.y=clamp(keeper.y+n.y*7,0,62)}}
 this.teams.forEach(t=>t.ai.update(this,dt));this.tackles(dt);this.collisions();this.ball.update(dt);this.receive();this.boundaries();this.rules.update(dt);}
 humanStep(dt){this.selection(dt);const p=this.selected,b=this.ball,n=this.input.axis();if(!p)return;if(p.action!=='tackle'||!p.actionTime)p.move(n.x,n.y,dt,(b.controlMode==='HANDS'?4:p.burst?25:15)*(p.team.humanPace||1));if(b.owner===p&&b.controlMode==='HANDS'){p.x=clamp(p.x,p.team.id?84:1,p.team.id?99:16);p.y=clamp(p.y,15,47);if(p.aiWait===0)this.pass(p);}
 if(b.owner===p){if(this.input.take('x'))this.pass(p,true);else if(this.input.take('c'))this.pass(p);if(this.input.shotBuffer>0&&b.owner===p)this.shoot(p);if(this.input.take('v')&&b.owner===p&&p.specialCooldown===0){p.burst=.38;p.specialCooldown=2.3;this.say('BURST!',.4)}}else{if(this.input.take('x')||this.input.take('c'))p.tackle(false);if(this.input.take('v'))p.tackle(true)}}
}
// Skin tones (0 = sprite original). Recoloured by brightness, so shading of the art is kept.
const SKIN_TONES=[null,[214,150,104],[176,112,72],[124,78,50],[92,58,40]];
class Renderer {
 constructor(canvas){this.c=canvas;this.ctx=canvas.getContext('2d');this.ctx.imageSmoothingEnabled=false;this.images={};this.atlas=new Image();this.atlas.src=window.S9ArcadeSpriteSource?.('players','arcade/assets/animations.png?v=offline-1')||'arcade/assets/animations.png?v=offline-1';this.palettes=new Map();for(const key of ['blue','red','keeper']){const im=new Image();im.src='arcade/assets/'+key+'.png';this.images[key]=im}}
 sprite(p,m,pr){const actions=window.S9ArcadeFrames;if(!this.atlas.complete||!this.atlas.naturalWidth||!actions)return;let action=p.role==='GK'?(p.keeperState==='GK_CATCHING'?'catch':p.keeperState==='GK_HOLDING'?'hold':p.keeperState==='GK_DIVING'?(p.face.y<0?'dive_left':'dive_right'):p.action==='pass'?'throw':p.action==='shoot'?'kick_long':p.action==='run'?'gk_move':'gk_idle'):p.stun?'fall':p.burst?'special':p.action==='tackle'?(p.hard?'hard_tackle':'tackle'):m.ball.owner===p&&p.action==='run'?'dribble':p.action;const row=actions[action]||actions.idle;const frame=row[Math.floor(m.elapsed*10)%row.length];let sheet=this.atlas;const skin=SKIN_TONES[p.skin|0];if(p.team.kit&&p.role!=='GK'||skin){const k=p.role!=='GK'&&p.team.kit||null,key=JSON.stringify(k)+'|'+(p.skin|0);if(!this.palettes.has(key)){const canvas=document.createElement('canvas');canvas.width=this.atlas.width;canvas.height=this.atlas.height;const ctx=canvas.getContext('2d');ctx.drawImage(this.atlas,0,0);const pixels=ctx.getImageData(0,0,canvas.width,canvas.height),d=pixels.data;const rgb=value=>{let h=value.replace('#','');if(h.length===3)h=[...h].map(c=>c+c).join('');return [parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16)]};for(let i=0;i<d.length;i+=4){if(!d[i+3])continue;const x=(i/4)%canvas.width,y=Math.floor(i/4/canvas.width)%128;if(skin&&d[i]>165&&d[i+1]>60&&d[i+2]<140&&d[i]-d[i+2]>70&&d[i]>d[i+1]*1.15){const shade=d[i]/250;for(let j=0;j<3;j++)d[i+j]=Math.min(255,skin[j]*shade);continue}if(!k)continue;if(y>=75&&y<99&&Math.max(d[i],d[i+1],d[i+2])-Math.min(d[i],d[i+1],d[i+2])<25&&d[i]>100){const color=rgb(k.shorts),shade=(d[i]+d[i+1]+d[i+2])/765;for(let j=0;j<3;j++)d[i+j]=color[j]*shade;continue}if(d[i+2]<d[i]*1.3||d[i+2]<d[i+1]*1.1)continue;const secondary=k.pattern==='vertical_stripes'?Math.floor((x%128)/7)%2:k.pattern==='horizontal_band'?y>55&&y<66:k.pattern==='halves'?x%128>64:k.pattern==='trim'?(y<49||((x%128<48||x%128>80)&&y<82)):false;const color=rgb(y>100?k.socks:secondary?k.shirtSecondary:k.shirtPrimary);const shade=.55+d[i+2]/565;for(let j=0;j<3;j++)d[i+j]=Math.min(255,color[j]*shade)}ctx.putImageData(pixels,0,0);this.palettes.set(key,canvas)}sheet=this.palettes.get(key)}this.ctx.drawImage(sheet,frame%8*128,Math.floor(frame/8)*128,128,128,-45*pr.scale,-80*pr.scale,90*pr.scale,90*pr.scale);}
 drawPenalty(m){const c=this.ctx,team=m.pen.turn%2,g=m.teams[1-team].players[0],shooter=m.teams[team].players.find(p=>!p.sentOff&&p.role==='ST')||m.teams[team].players.find(p=>!p.sentOff&&p.role!=='GK'),b=m.ball;c.clearRect(0,0,1280,720);c.fillStyle='#0b142a';c.fillRect(0,0,1280,720);c.fillStyle='#22a24c';c.fillRect(0,240,1280,480);c.fillStyle='#142330';c.fillRect(275,155,730,280);c.strokeStyle='#89a7a3';c.lineWidth=2;for(let x=285;x<1000;x+=30){c.beginPath();c.moveTo(x,165);c.lineTo(x,435);c.stroke()}for(let y=165;y<435;y+=25){c.beginPath();c.moveTo(280,y);c.lineTo(1000,y);c.stroke()}c.strokeStyle='#fff';c.lineWidth=12;c.beginPath();c.moveTo(275,445);c.lineTo(275,155);c.lineTo(1005,155);c.lineTo(1005,445);c.stroke();c.lineWidth=3;c.beginPath();c.moveTo(0,445);c.lineTo(1280,445);c.stroke();
 const keeperX=640+(g.y-31)*48;c.save();c.translate(keeperX,442);this.sprite(g,m,{scale:2.1});c.restore();if(!m.pen.flight){c.save();c.translate(620,622);this.sprite(shooter,m,{scale:2});c.restore()}
 const progress=m.pen.flight?clamp(Math.abs(b.x-(team?18:82))/18,0,1):0,ballX=640+(b.y-31)*48*progress,ballY=610-progress*170-b.z*30;c.fillStyle='#fff';c.beginPath();c.arc(ballX,ballY,9-progress*3,0,Math.PI*2);c.fill();c.fillStyle='#112035';c.fillRect(ballX-3,ballY-3,6,6);
 this.text('PENALTY SHOOTOUT',640,48,34,'#ffed45');this.text(m.teams[0].name+'  '+m.pen.goals[0],290,87,22,'#81bcff');this.text(m.teams[1].name+'  '+m.pen.goals[1],990,87,22,'#ff8294');this.text(m.pen.history[0].map(v=>v?'●':'○').join(' '),290,119,22,'#ffed45');this.text(m.pen.history[1].map(v=>v?'●':'○').join(' '),990,119,22,'#ffed45');this.text(team===0?'FRECCE · MIRA   Z · TIRA':'FRECCE · TUFFO   TIMING!',640,685,24,'#ffed45');if(m.messageTime>0)this.text(m.message,640,655,21,'#fff');}
 project(x,y){const cam=this.camera||{x:50,y:31,zoom:26};return {x:Math.round(640+(x-cam.x)*cam.zoom),y:Math.round(365+(y-cam.y)*cam.zoom*.65),scale:Math.max(1.55,cam.zoom/40)}}
 text(s,x,y,size=20,color='#fff',align='center'){const c=this.ctx;c.font=`bold ${size}px monospace`;c.textAlign=align;c.fillStyle='#07101b';c.fillText(s,x+2,y+2);c.fillStyle=color;c.fillText(s,x,y)}
 draw(m){if(m.phase==='PENALTIES'){this.drawPenalty(m);return}const c=this.ctx;c.clearRect(0,0,1280,720);c.fillStyle='#141c34';c.fillRect(0,0,1280,720);for(let y=80;y<128;y+=9)for(let x=12;x<1270;x+=13){c.fillStyle=['#727cab','#e5c25d','#ae5065'][(x+y)%3];c.fillRect(x,y,5,4)}
 for(let i=0;i<10;i++){const a=this.project(i*10,0),b=this.project((i+1)*10,0),d=this.project((i+1)*10,62),e=this.project(i*10,62);c.fillStyle=i%2?'#219647':'#26a653';c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.lineTo(d.x,d.y);c.lineTo(e.x,e.y);c.fill()}
 const line=(points)=>{c.strokeStyle='#c2f1c3';c.lineWidth=2;c.beginPath();points.forEach(([x,y],i)=>{const p=this.project(x,y);i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y)});c.stroke()};line([[0,0],[100,0],[100,62],[0,62],[0,0]]);line([[50,0],[50,62]]);for(const x of [0,100]){const end=x?84:16;line([[x,14],[end,14],[end,48],[x,48]]);line([[x,23],[x?94:6,23],[x?94:6,39],[x,39]]);const a=this.project(x,25),b=this.project(x,37);c.fillStyle='#deeafa';c.fillRect(a.x+(x?0:-20),a.y-16,20,b.y-a.y+16);c.strokeStyle='#72859a';for(let y=a.y-16;y<b.y;y+=7){c.beginPath();c.moveTo(a.x+(x?0:-20),y);c.lineTo(a.x+(x?20:0),y);c.stroke()}}
 const mid=this.project(50,31);c.strokeStyle='#c2f1c3';c.beginPath();c.ellipse(mid.x,mid.y,90,65,0,0,Math.PI*2);c.stroke();
 for(const p of [...m.players].sort((a,b)=>a.y-b.y)){const pr=this.project(p.x,p.y),im=this.images[p.role==='GK'?'keeper':p.team.id?'red':'blue'];c.fillStyle='#0005';c.beginPath();c.ellipse(pr.x,pr.y+6,12*pr.scale,4*pr.scale,0,0,7);c.fill();if(p===m.selected){c.strokeStyle='#ffec54';c.lineWidth=3;c.beginPath();c.ellipse(pr.x,pr.y+7,17,6,0,0,7);c.stroke();this.text('1P',pr.x,pr.y-125,17,'#fff56c')}
 let frame=p.action==='kick'?6:p.action==='tackle'?7:p.action==='run'?Math.floor(m.elapsed*12)%6:0;const cols=p.role==='GK'?3:4;if(p.role==='GK')frame=p.action==='keeper'?2:p.action==='kick'?5:Math.floor(m.elapsed*4)%2;
 c.save();c.translate(pr.x,pr.y);if(p.face.x<0)c.scale(-1,1);if(p.burst){c.fillStyle='#7deafa70';c.fillRect(-30,-30,25,25)}this.sprite(p,m,pr);c.restore();if(p.action==='tackle'&&p.actionTime>0){c.strokeStyle=p.hard?'#ff5d31':'#fff4';c.beginPath();c.ellipse(pr.x,pr.y, p.hard?31:23,12,0,0,7);c.stroke()}
 if(m.debug){this.text(p.keeperState||p.receiveState,pr.x,pr.y-65,10);const t=this.project(p.target.x,p.target.y);c.strokeStyle=p.team.id?'#ff9c9c':'#9ee9ff';c.beginPath();c.moveTo(pr.x,pr.y);c.lineTo(t.x,t.y);c.stroke();this.text(p.role,pr.x,pr.y-42,10)}}
 const ref=this.project(m.ball.x-8,clamp(m.ball.y+8,4,58));if(this.atlas.complete&&this.atlas.naturalWidth){const ri=window.S9ArcadeFrames.referee[m.message.includes('FOUL')||m.message.includes('PENALTY')?2:0];c.drawImage(this.atlas,ri%8*128,Math.floor(ri/8)*128,128,128,ref.x-40,ref.y-100,80,100)}const b=m.ball,bp=this.project(b.x,b.y);c.fillStyle='#0006';c.beginPath();c.ellipse(bp.x,bp.y+5,6,3,0,0,7);c.fill();c.fillStyle='white';c.beginPath();c.arc(bp.x,bp.y-b.z*8,6,0,7);c.fill();c.fillStyle='#15203a';c.fillRect(bp.x-2,bp.y-b.z*8-2,4,4);
 c.fillStyle='#080f24';c.fillRect(0,0,1280,76);this.text(m.teams[0].name,250,42,27,'#81bcff');this.text(m.teams[1].name,1030,42,27,'#ff8294');this.text(`${m.rules.score[0]} — ${m.rules.score[1]}`,640,43,38,'#fff36e');const seconds=Math.ceil(m.rules.period==='GOLDEN'?m.rules.goldenRemaining:m.rules.remaining);this.text(m.rules.period==='PENALTIES'?`RIGORI ${m.pen.goals.join(' : ')}`:`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')} ${m.rules.period==='GOLDEN'?'GG':''}`,640,69,18);this.text('SERIEASIM2000 ARCADE',640,666,24,'#fff36e');this.text('FRECCE MUOVI   Z TIRO   X ALTO/SCIVOLATA   C PASSA/SCIVOLATA   V DRIBBLING/DURO   D DEBUG',640,696,16,'#bdc9e8');if(m.phase==='PENALTIES'){this.text(m.pen.history[0].map(v=>v?'●':'○').join(' '),235,68,18,'#fff36e');this.text(m.pen.history[1].map(v=>v?'●':'○').join(' '),1040,68,18,'#fff36e')}if(m.messageTime>0)this.text(m.message,640,113,25,'#fff36e');if(m.phase==='RESTART'&&m.restarts.data?.team===0)this.text('C / X • '+m.restarts.data.type,640,585,23,'#fff36e');if(m.debug){this.text(m.teams.map(t=>t.state).join(' / '),12,155,14,'#fff','left');this.text(`PLAYER ${m.selected.number} • BALL ${b.state} • OWNER ${b.owner?b.owner.team.id+':'+b.owner.number:'none'} • TARGET ${b.passTarget?.number??'none'}`,12,178,14,'#fff','left');}}
}

window.S9ArcadeEngine={InputManager,Player,Goalkeeper,Team,Ball,TeamAI,MatchRules,RestartManager,Match,Renderer};
})();
