/* Arcade evolution: shared preferences, objectives, readable controls and cosmetic progress. */
(function(){
'use strict';
const E=window.S9ArcadeEngine,M=E.Match.prototype,R=E.Renderer.prototype;
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem('sa2000:'+k))||f}catch(_){return f}};
const defaults={camera:'panoramic',radar:true,volume:.65,vibration:true,effects:.5,keys:{z:'z',c:'c',x:'x',v:'v',switch:'shift'},ball:'classic',pitch:'classic',kit:'classic',celebration:'classic'};
const settings={...defaults,...read('preferences',{}),keys:{...defaults.keys,...read('preferences',{}).keys}};
const progress={xp:0,medals:{},bestSurvival:0,...read('progress',{})};
const save=()=>{try{localStorage.setItem('sa2000:preferences',JSON.stringify(settings));localStorage.setItem('sa2000:progress',JSON.stringify(progress))}catch(_){}if(typeof document!=='undefined'){document.documentElement.style.setProperty('--arcade-effects',settings.effects);document.documentElement.style.setProperty('--arcade-scanline','rgba(0,0,0,'+(settings.effects*.16)+')')}};
const commands=[['z','TIRO','Tieni per caricare, rilascia per tirare'],['c','PASSAGGIO','Direzione + passaggio verso il compagno evidenziato'],['x','PASSAGGIO ALTO','Cross in attacco, scivolata in difesa'],['v','DRIBBLING','Finta in attacco, contrasto duro in difesa'],['switch','CAMBIO GIOCATORE','Scegli il difensore più vicino alla palla']];
const cosmetics=[{key:'ball',value:'gold',name:'Pallone oro',xp:100},{key:'pitch',value:'night',name:'Campo notturno',xp:200},{key:'kit',value:'neon',name:'Divisa neon',xp:300},{key:'celebration',value:'confetti',name:'Festa coriandoli',xp:400}];
const challenges={comeback:{name:'Rimonta in 60 secondi',description:'Parti sotto 0–2. Pareggia o vinci.',duration:60,score:[0,2]},volley:{name:'Gol al volo',description:'Cross con X, carica Z prima della ricezione. Segna al volo.',duration:90},resist:{name:'Resisti in dieci',description:'Difendi lo 0–0 per 60 secondi con un uomo in meno.',duration:60},passing:{name:'Accademia passaggi',description:'Completa 8 passaggi in 60 secondi.',duration:60},defending:{name:'Accademia difesa',description:'Vinci 3 contrasti in 60 secondi. Usa SHIFT per cambiare uomo.',duration:60},dribbling:{name:'Accademia dribbling',description:'Esegui 6 finte con V in 60 secondi, rispettando il recupero.',duration:60}};
const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function candidates(m,h){return m.teams[h.team].players.filter(p=>!p.sentOff&&p.role!=='GK'&&p!==h.selected&&!m.humans.some(o=>o!==h&&o.selected===p)).sort((a,b)=>distance(a,m.ball)-distance(b,m.ball))}
const keeperUpdate=E.Goalkeeper.prototype.update;E.Goalkeeper.prototype.update=function(m,dt){const before=m.stats.teams[this.team.id].saves;keeperUpdate.call(this,m,dt);if(m.stats.teams[this.team.id].saves>before)this.arcadeSaves=(this.arcadeSaves||0)+1};
const step=M.humanStep;
M.humanStep=function(dt){const h=this.human;if(this.input.take('switch')&&this.ball.owner?.team.id!==h.team){const p=candidates(this,h)[0];if(p){h.selected=p;h.selectionTimer=1.2;this.input.cancelShot()}}const p=h.selected,burst=p?.burst||0;step.call(this,dt);if(p&&p.burst>burst){this.stats.teams[h.team].dribbles=(this.stats.teams[h.team].dribbles||0)+1}};
const control=M.control;
M.control=function(p){const b=this.ball,from=b.passTarget&&this.lastPasser&&p.team===this.lastPasser.team&&p!==this.lastPasser?this.lastPasser:null;control.call(this,p);if(from&&b.lastTeam===p.team.id){const stats=this.stats.teams[p.team.id];stats.completedPasses=(stats.completedPasses||0)+1;from.completedPasses=(from.completedPasses||0)+1}};
function feedback(m,strength=.3){if(!settings.vibration)return;const ids=new Set(m.humans.flatMap(h=>Array.isArray(h.input.pads)?h.input.pads:[]));for(const p of typeof navigator!=='undefined'?(navigator.getGamepads?.()||[]):[]){if(!p||(!ids.has(p.index)&&!m.humans.some(h=>h.input.pads==='all')))continue;try{p.vibrationActuator?.playEffect('dual-rumble',{duration:90,strongMagnitude:strength,weakMagnitude:strength*.5})?.catch?.(()=>{})}catch(_){}}}
const shoot=M.shoot,pass=M.pass,tackles=M.tackles;
M.shoot=function(p,...args){shoot.call(this,p,...args);if(this.ball.state==='shot'){p.arcadeShots=(p.arcadeShots||0)+1;window.S9SFX?.kick?.();feedback(this,.5);if(args[0])this.stats.teams[p.team.id].volleys=(this.stats.teams[p.team.id].volleys||0)+1}};
M.pass=function(...args){const before=this.stats.teams.reduce((n,t)=>n+t.passes,0);pass.apply(this,args);if(this.stats.teams.reduce((n,t)=>n+t.passes,0)>before)window.S9SFX?.kick?.()};
M.tackles=function(dt){const n=this.stats.teams.reduce((n,t)=>n+t.tackles,0);tackles.call(this,dt);if(this.stats.teams.reduce((n,t)=>n+t.tackles,0)>n){window.S9SFX?.slam?.();feedback(this,.35)}};
const oldShoot=M.shoot;
M.shoot=function(p,...args){const before=this.stats.teams[p.team.id].volleys||0;oldShoot.call(this,p,...args);if((this.stats.teams[p.team.id].volleys||0)>before)this.volleyShooter=p;else this.volleyShooter=null};
function setup(m,config){m.evolutionConfig=config;for(const t of m.teams){let hash=0;for(const c of t.name)hash+=c.charCodeAt(0);t.style=['press','counter','possession'][hash%3];if(t.cpu){t.cpu.pace=1;for(const p of t.players)if(p.source&&window.ArcadeMatchBridge)p.attributes=ArcadeMatchBridge.attributes(p.source)}else t.humanPace=1;t.mentality=t.style==='press'?'Offensivo':t.style==='counter'?'Difensivo':'Equilibrato';if(settings.kit==='neon'&&progress.xp>=300&&m.humans[0]?.team===t.id)t.kit={...t.kit,shirtPrimary:'#73ff42',shirtSecondary:'#182453'}}
 if(config.duration)m.rules.remaining=config.duration;if(config.challenge){const c=challenges[config.challenge];m.objective={key:config.challenge,...c,volleys:0};m.rules.remaining=c.duration;m.rules.allowDraw=true;m.rules.score=c.score?.slice()||[0,0];if(config.challenge==='resist'){const p=m.teams[0].players[10];p.sentOff=true;m.players=m.players.filter(q=>q!==p);m.assignIdle()}if(['resist','defending'].includes(config.challenge))m.restarts.kickoff(1)}
 if(config.specialRule==='golden'){m.rules.period='GOLDEN';m.rules.goldenRemaining=120}
 if(config.specialRule==='keepers')for(const t of m.teams){t.players[0].attributes=t.players[0].attributes||{};t.players[0].attributes.goalkeeping=100;t.players[0].attributes.speed=95}
 if(config.specialRule==='fastball')m.fastBall=true;
 if(config.training&&m.training){m.training.limit=5;m.say('5 TENTATIVI · 1 GOL BRONZO · 3 ARGENTO · 5 ORO',2)}
}
const goal=E.MatchRules.prototype.goal;
E.MatchRules.prototype.goal=function(team){const m=this.m;if(team===0&&m.objective&&m.lastShooter&&m.lastShooter.team.id===0&&m.lastShooter===m.volleyShooter)m.objective.volleys++;goal.call(this,team);feedback(m,.8)};
const award=E.RestartManager.prototype.award;E.RestartManager.prototype.award=function(type,...args){if(this.m.evolutionConfig?.specialRule==='nofouls'&&['FREE KICK','PENALTY'].includes(type))return;return award.call(this,type,...args)};
const kick=E.Ball.prototype.kick;E.Ball.prototype.kick=function(...args){this.fastBoost=false;return kick.apply(this,args)};
const choose=M.chooseTarget;M.chooseTarget=function(p,aerial=false){if(p.team.style!=='possession'||this.isControlled(p)||this.restarts.data)return choose.call(this,p,aerial);const candidates=p.team.players.filter(q=>q!==p&&!q.sentOff&&q.role!=='GK');return candidates.sort((a,b)=>{const score=q=>{const d=distance(p,q),space=Math.min(12,...this.players.filter(o=>o.team!==p.team&&!o.sentOff).map(o=>distance(o,q)));return space*3-Math.abs(d-15)-Math.max(0,-p.team.dir*(q.x-p.x))*.4};return score(b)-score(a)})[0]||choose.call(this,p,aerial)};
const boundaries=M.boundaries;M.boundaries=function(){const b=this.ball;if(!b.owner&&(b.x<0||b.x>100)&&!['PENALTIES','FREEKICK'].includes(this.phase)){const upright=Math.min(Math.abs(b.y-25),Math.abs(b.y-37))<.3&&b.z<5.2,bar=b.y>25&&b.y<37&&Math.abs(b.z-5)<.25;if(upright||bar){b.x=b.x>50?99.6:.4;b.vx=-b.vx*.65;b.vy*=.8;if(bar)b.vz=-Math.abs(b.vz)*.6;b.state='rebound';b.lock=.12;const s=this.stats.teams[b.lastTeam];s.posts=(s.posts||0)+1;this.say(bar?'TRAVERSA!':'PALO!',1);window.S9SFX?.slam?.();feedback(this,.7);return}}return boundaries.call(this)};
const update=M.update;
M.update=function(dt){const saves=this.stats.teams.reduce((n,t)=>n+t.saves,0);update.call(this,dt);if(this.stats.teams.reduce((n,t)=>n+t.saves,0)>saves)feedback(this,.6);if(this.fastBall&&this.ball.state==='shot'&&!this.ball.fastBoost){this.ball.vx*=1.25;this.ball.vy*=1.25;this.ball.fastBoost=true}else if(this.ball.state!=='shot')this.ball.fastBoost=false;if(this.training?.limit&&this.training.attempts>=this.training.limit&&!this.training.active&&this.phase!=='FINISHED')this.rules.finish();const o=this.objective,s=this.stats.teams[0];if(o&&this.phase!=='FINISHED'&&((o.key==='passing'&&(s.completedPasses||0)>=8)||(o.key==='defending'&&s.tackles>=3)||(o.key==='dribbling'&&(s.dribbles||0)>=6)||(o.key==='volley'&&o.volleys>=1)))this.rules.finish()};
const foul=M.tackles;
M.tackles=function(dt){if(this.evolutionConfig?.specialRule!=='nofouls')return foul.call(this,dt);const flags=this.players.map(p=>p.hard);this.players.forEach(p=>p.hard=false);try{return foul.call(this,dt)}finally{this.players.forEach((p,i)=>p.hard=flags[i])}};
const camera=E.CameraController.prototype.update;
E.CameraController.prototype.update=function(m,dt){camera.call(this,m,dt);this.zoom=settings.camera==='close'?136:settings.camera==='wide'?22:36};
const draw=R.draw;
const pitch=R.pitch;R.pitch=function(...args){const c=this.ctx;c.save();if(settings.pitch==='night'&&progress.xp>=200)c.filter='brightness(.78) saturate(.8)';pitch.apply(this,args);c.restore()};
R.draw=function(m){const c=this.ctx;draw.call(this,m);if(this.replayMode||m.phase==='FINISHED'||m.pen||m.fk||m.cardScene)return;

 for(const h of m.humans){const p=h.selected;if(!p)continue;const pr=this.project(p.x,p.y);c.strokeStyle=h.color;c.lineWidth=3;c.beginPath();c.ellipse(pr.x,pr.y+6,19*pr.scale,7*pr.scale,0,0,Math.PI*2);c.stroke();let target;if(m.ball.owner===p)target=m.as(h,()=>m.chooseTarget(p));else target=candidates(m,h)[0];if(target){const t=this.project(target.x,target.y);c.strokeStyle=m.ball.owner===p?'#80ffcf':'#ffffff88';c.lineWidth=2;c.beginPath();c.ellipse(t.x,t.y+5,15*t.scale,5*t.scale,0,0,Math.PI*2);c.stroke()}
 this.text(h.label+' · '+(p.source?.name||'N° '+p.number).toUpperCase()+(p.specialCooldown>0?'':'  ·  FINTA ✓'),24+h.slot*300,700,14,h.color,'left')}
 this.chargeMeter(m);if(m.objective){this.panel(290,548,650,42,8);const s=m.stats.teams[0],o=m.objective,n=o.key==='passing'?(s.completedPasses||0)+'/8':o.key==='defending'?s.tackles+'/3':o.key==='dribbling'?(s.dribbles||0)+'/6':o.key==='volley'?o.volleys+'/1':'';this.text(o.name.toUpperCase()+' '+n,615,575,19,'#ffed72')}
};
const hint=R.controlsHint;R.controlsHint=function(m){if(window.S9ArcadeControls?.padConnected)return hint.call(this,m)+' · LB CAMBIA';const k=settings.keys;if(m.phase==='PENALTIES')return 'FRECCE MIRA · '+k.z.toUpperCase()+' TIRA · '+k.x.toUpperCase()+'/'+k.c.toUpperCase()+' TUFFO';return (k.z+' TIRO · '+k.c+' PASSA · '+k.x+' ALTO · '+k.v+' FINTA · '+k.switch+' CAMBIA · '+(window.S9ArcadeBindings?.label(S9ArcadeBindings.key('pause'))||'ESC')+' PAUSA · '+(window.S9ArcadeBindings?.label(S9ArcadeBindings.key('fullscreen'))||'F')+' FULL').toUpperCase()};
const radar=R.radar;R.radar=function(m){if(settings.radar)return radar.call(this,m)};
R.chargeMeter=function(m){if(m.phase==='FINISHED'||m.phase==='PENALTIES'||this.replayMode)return;for(const h of m.humans||[]){const input=h.input,p=h.selected,recent=m.lastShot?.player===p&&m.elapsed-m.lastShot.time<.45;if(!input||(!input.shotCharging&&!recent))continue;const q=input.shotCharging?input.shotCharge:m.lastShot.charge;for(let i=0;i<12;i++){this.ctx.fillStyle=i<Math.ceil(q*12)?i>8?'#ff6436':i>4?'#ffe44a':'#79e752':'#253c50';this.ctx.fillRect(40+h.slot*315+i*20,646,17,8)}}};
const text=R.text;R.text=function(value,...args){if(typeof value==='string'&&window.S9ArcadeBindings&&(/RIPRENDI|ESCI SENZA|SCHERMO INTERO|IMPOSTAZIONI/.test(value)||this.currentMatch?.phase==='FINISHED'&&value.includes('CONTINUA')))return text.call(this,value.replace('Z / INVIO',S9ArcadeBindings.label(S9ArcadeBindings.key('confirm','menu'))),...args);if(typeof value==='string'&&!window.S9ArcadeControls?.padConnected){value=value.replace(/Z\/C\/X/g,[settings.keys.z,settings.keys.c,settings.keys.x].join('/').toUpperCase()).replace(/X \/ C|C \/ X/g,[settings.keys.c,settings.keys.x].join(' / ').toUpperCase()).replace(/\b(Z|C|X|V|SHIFT)(?= \u00b7| \/ INVIO)/g,k=>(settings.keys[k==='SHIFT'?'switch':k.toLowerCase()]||k).toUpperCase())}return text.call(this,value,...args)};
const ball=R.drawBall;
R.drawBall=function(...args){if(settings.ball==='gold'&&progress.xp>=100){this.ctx.save();this.ctx.filter='sepia(1) saturate(4)';ball.apply(this,args);this.ctx.restore()}else ball.apply(this,args)};
const result=R.resultScreen;
R.resultScreen=function(m){result.call(this,m);const a=m.stats.teams[0],b=m.stats.teams[1];this.panel(330,490,620,70,10);this.text('TIRI '+a.shots+' — '+b.shots+'    PARATE '+a.saves+' — '+b.saves,640,514,18,'#bcecff');this.text('PASSAGGI '+Math.round((a.completedPasses||0)/Math.max(1,a.passes)*100)+'% — '+Math.round((b.completedPasses||0)/Math.max(1,b.passes)*100)+'%',640,541,16,'#fff');this.text((window.S9ArcadeBindings?.label(S9ArcadeBindings.key('confirm','menu'))||'Z / INVIO')+' · CONTINUA',640,584,20,'#ffe55a');const summary=m.resultSummary;if(summary?.objective)this.text((summary.objective.success?'OBIETTIVO SUPERATO':'RIPROVA')+' '+('★'.repeat(summary.objective.medal)),640,463,20,'#fff07a');if(summary?.mvp)this.text('MIGLIORE IN CAMPO · '+summary.mvp,640,615,18,'#bcecff');if(settings.celebration==='confetti'&&progress.xp>=400)for(let i=0;i<40;i++){this.ctx.fillStyle=['#ffed50','#80ffca','#ff7ba1'][i%3];this.ctx.fillRect((i*97)%1280,((m.presentationTime||0)*90+i*43)%720,6,9)}};
function record(m,result){const s=m.stats.teams[0],o=m.objective;let success=null;if(m.training?.limit){const t=m.training,medal=t.goals>=5?3:t.goals>=3?2:t.goals>=1?1:0;progress.medals['training:'+t.drill]=Math.max(progress.medals['training:'+t.drill]||0,medal);result.objective={name:'Allenamento · '+t.goals+' / '+t.attempts,success:medal>0,medal};success=medal>0}if(o){success=o.key==='comeback'?result.homeGoals>=result.awayGoals:o.key==='resist'?result.awayGoals===0:o.key==='volley'?o.volleys>0:o.key==='passing'?(s.completedPasses||0)>=8:o.key==='defending'?s.tackles>=3:(s.dribbles||0)>=6;const margin=result.homeGoals-result.awayGoals,defense=s.saves+s.tackles;const medal=!success?0:o.key==='comeback'?margin>=2?3:margin>0?2:1:o.key==='resist'?defense>=5?3:defense>=2?2:1:m.rules.remaining>20?3:m.rules.remaining>5?2:1;progress.medals[o.key]=Math.max(progress.medals[o.key]||0,medal);result.objective={name:o.name,success,medal};}progress.xp+=success===false?5:success?50:20;result.xp=progress.xp;result.stats.teams=m.stats.teams.map(t=>({...t}));const scores=m.players.map(p=>({name:p.source?.name||'N° '+p.number,value:m.scorers.filter(s=>s.playerId&&s.playerId===p.source?.id).length*10+(p.completedPasses||0)+(p.arcadeShots||0)*2+(p.arcadeSaves||0)*5+m.scorers.filter(s=>s.assistId&&s.assistId===p.source?.id).length*4})).sort((a,b)=>b.value-a.value);result.mvp=scores[0]?.name;save()}
const describe=key=>challenges[key].description.replace(/\b(Z|C|X|V|SHIFT)\b/g,k=>(settings.keys[k==='SHIFT'?'switch':k.toLowerCase()]||k).toUpperCase());
window.S9ArcadeEvolution={settings,progress,save,describe,commands,cosmetics,challenges,setup,record,candidates};save();
})();
