/* Shared celebration: trophy close-up, generic kit-swapped players and a timed lift. */
(function(){let renderer=null,trophy=null;const players=Array.from({length:7},()=>({role:'ST',action:'idle',face:{x:1,y:0},team:{}}));
function draw(c,w,h,box,age){const scene=box.querySelector('.arcade-victory');if(!scene)return;const r=scene.getBoundingClientRect(),cx=w/2,base=r.y+r.height-35,scale=Math.min(w/1028,1.25),kit=JSON.parse(scene.dataset.kit||'{}');if(!renderer){renderer=new S9ArcadeEngine.Renderer(document.createElement('canvas'))}renderer.ctx=c;if(!trophy){trophy=new Image();trophy.src='arcade/assets/championship-trophy.png?v=cabinet-1'}
 if(renderer.panel)renderer.panel(r.x,r.y,r.width,r.height,22);else{c.fillStyle='#151270db';c.fillRect(r.x,r.y,r.width,r.height)}c.textAlign='left';c.font='900 '+Math.round(18*scale)+'px monospace';c.fillStyle='#ffff24';c.fillText(age<2?'LA COPPA È TUA!':'CAMPIONI!',r.x+24,r.y+30);
 if(age<2&&trophy.complete&&trophy.naturalWidth){const th=Math.min(r.height-20,220),tw=th*trophy.width/trophy.height;c.drawImage(trophy,cx-tw/2,r.y+10,tw,th);return}
 c.fillStyle='#411ba8';c.fillRect(cx-135*scale,base-3,270*scale,28);c.fillStyle='#00f4ff';c.fillRect(cx-135*scale,base-3,270*scale,5);
 if(renderer.atlas.complete&&renderer.atlas.naturalWidth){for(let i=-3;i<=3;i++){const arrive=Math.min(1,Math.max(0,(age-2)*1.6)),step=Math.floor(arrive*6)/6,x=cx+i*80*scale+(1-step)*(i<0?-r.width/2:r.width/2),p=players[i+3];p.action=arrive<1?'run':'celebrate';p.team.kit=kit;c.save();c.translate(x,base+(i===0?0:10));renderer.sprite(p,{elapsed:age+i*.07,ball:{}},{scale:(i===0?1.6:1.2)*scale});c.restore()}}
 if(age>=2.65&&trophy.complete&&trophy.naturalWidth){const lift=Math.min(1,(age-2.65)/.9),th=76*scale,tw=th*trophy.width/trophy.height,top=r.y+60*(1-lift)+10;c.drawImage(trophy,cx-tw/2,top,tw,th)}
 if(age>3.5)for(let i=0;i<95;i++){const x=((i*137+Math.floor(age*12)*(i%3-1)*4)%w+w)%w,y=r.y+((i*71+Math.floor(age*18)*5)%Math.max(1,r.height));c.fillStyle=['#ffff24','#00faff','#ff18ad'][i%3];c.fillRect(x,y,5,3)}
}window.S9ArcadeCeremony={draw};})();
