/* Canvas cabinet presentation. DOM remains the accessible input/layout layer. */
(function(){
function mount(box){
 // The DOM is only the invisible input/layout layer from the first frame: never show its CSS boxes, even while art loads.
 const canvas=document.createElement('canvas');canvas.className='arcade-menu-art';box.classList.add('arcade-drawn');canvas.setAttribute('aria-hidden','true');document.body.append(canvas);const c=canvas.getContext('2d');
 const load=name=>{const im=new Image();im.src='arcade/assets/'+name+'?v=drawn-1';return im},stadium=load('cabinet-90s.png'),cup=load('cup-background.png'),bezel=load('drawn-panel.png');
 let ceremonyStart=null,alive=true,entries=[],dirty=true,last=0,mapSource='',mapImage=null,mapURL=null,ready=false;
 const observer=new MutationObserver(()=>dirty=true);observer.observe(box,{childList:true,subtree:true,characterData:true});const invalidate=()=>dirty=true;window.addEventListener('resize',invalidate);box.addEventListener('scroll',invalidate);
 function rect(n){const r=n.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height}}
 function panel(r,edge=18){if(r.w<=0||r.h<=0)return;if(!bezel.naturalWidth){c.fillStyle='#071933';c.fillRect(r.x,r.y,r.w,r.h);return}const sw=bezel.naturalWidth,sy=bezel.naturalHeight*.074,sh=bezel.naturalHeight*.85,s=sw*.12,dy=Math.min(edge,r.h/3),dx=Math.min(edge,r.w/3);const xs=[0,s,sw-s,sw],ys=[sy,sy+s,sy+sh-s,sy+sh],xd=[r.x,r.x+dx,r.x+r.w-dx,r.x+r.w],yd=[r.y,r.y+dy,r.y+r.h-dy,r.y+r.h];for(let y=0;y<3;y++)for(let x=0;x<3;x++)c.drawImage(bezel,xs[x],ys[y],xs[x+1]-xs[x],ys[y+1]-ys[y],xd[x],yd[y],xd[x+1]-xd[x],yd[y+1]-yd[y]);c.fillStyle='#164bcd66';c.fillRect(r.x+dx,r.y+dy,r.w-2*dx,r.h-2*dy)}
 function cover(im,w,h){if(!im.naturalWidth)return;const scale=Math.max(w/im.width,h/im.height);c.drawImage(im,(w-im.width*scale)/2,(h-im.height*scale)/2,im.width*scale,im.height*scale)}
 function lettering(value,r,size=18,color='#fff1a2',align='center',top=false){value=value.trim().toUpperCase();if(!value)return;c.font='900 '+size+'px monospace';const words=value.split(/\s+/),lines=[];let line='';for(const word of words){const next=line?line+' '+word:word;if(c.measureText(next).width>r.w-14&&line){lines.push(line);line=word}else line=next}if(line)lines.push(line);const lineH=size*1.15,y=top?r.y+size:r.y+r.h/2-(lines.length-1)*lineH/2;c.textAlign=align;c.textBaseline=top?'alphabetic':'middle';c.lineJoin='miter';c.lineWidth=Math.max(2,size/7);for(let i=0;i<lines.length;i++){const x=align==='left'?r.x+10:r.x+r.w/2;c.strokeStyle='#03091b';c.strokeText(lines[i],x+1,y+i*lineH+2,r.w-12);c.fillStyle=color;c.fillText(lines[i],x,y+i*lineH,r.w-12)}}
 function rebuild(){dirty=false;entries=[];for(const n of box.querySelectorAll('.arcade-screen-head,.arcade-europe-panel,.arcade-player-card,.arcade-mode-tile,.arcade-howto section,.arcade-group-table'))entries.push({type:'panel',n,r:rect(n)});
 const svg=box.querySelector('svg');if(svg){const source=new XMLSerializer().serializeToString(svg);if(source!==mapSource){mapSource=source;if(mapURL)URL.revokeObjectURL(mapURL);mapURL=URL.createObjectURL(new Blob([source],{type:'image/svg+xml'}));const im=new Image();im.onload=()=>{if(source===mapSource)mapImage=im};im.src=mapURL}entries.push({type:'map',n:svg,r:rect(svg)})}else{mapSource='';mapImage=null}
 for(const n of box.querySelectorAll('button'))entries.push({type:'button',n,r:rect(n)});
 for(const n of box.querySelectorAll('canvas,img'))entries.push({type:'image',n,r:rect(n)});
 for(const n of box.querySelectorAll('h1,h2,p,button,strong,small,span,th,td,b,.arcade-stat')){const text=Array.from(n.childNodes).filter(x=>x.nodeType===3).map(x=>x.textContent).join(' ').trim();if(text)entries.push({type:'text',n,r:rect(n),text})}
 }
 function draw(now){if(!alive||!box.isConnected){dispose();return}requestAnimationFrame(draw);if(now-last<33)return;last=now;canvas.style.display=box.style.display==='none'?'none':'block';if(canvas.style.display==='none')return;
 const w=window.innerWidth,h=window.innerHeight;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;dirty=true}if(dirty)rebuild();c.imageSmoothingEnabled=false;c.fillStyle='#040e28';c.fillRect(0,0,w,h);const heading=box.querySelector('h1')?.textContent||'';cover(/GIRONE|OTTAVI|QUARTI|SEMIFINALE|FINALE|^CHAMPION!|GAME OVER|RESULT|NEXT MATCH/.test(heading)?cup:stadium,w,h);
 if(box.querySelector('.arcade-victory')){if(ceremonyStart===null)ceremonyStart=now;window.S9ArcadeCeremony?.draw(c,w,h,box,(now-ceremonyStart)/1000)}else ceremonyStart=null;
 for(const e of entries){const {n,r,type}=e;if(r.y+r.h<0||r.y>h||!r.w||!r.h)continue;
 if(type==='panel'){panel(r,n.classList.contains('arcade-mode-tile')?30:17);continue}
 if(type==='map'){if(mapImage){const view=e.n.viewBox.baseVal,scale=Math.min(r.w/view.width,r.h/view.height);c.drawImage(mapImage,r.x+(r.w-view.width*scale)/2,r.y+(r.h-view.height*scale)/2,view.width*scale,view.height*scale)}continue}
 if(type==='button'){const team=n.classList.contains('arcade-team-tile'),mode=n.classList.contains('arcade-mode-tile'),selected=n.classList.contains('selected')||n===document.activeElement;if(!mode)panel(r,team?12:10);if(selected){c.strokeStyle='#ffe64a';c.lineWidth=3;if(team){c.beginPath();c.moveTo(r.x+5,r.y+r.h-3);c.lineTo(r.x+r.w-5,r.y+r.h-3);c.stroke()}else c.strokeRect(r.x+2,r.y+2,r.w-4,r.h-4);c.fillStyle='#ffe64a';c.beginPath();c.moveTo(r.x+5,r.y+r.h/2-6);c.lineTo(r.x+13,r.y+r.h/2);c.lineTo(r.x+5,r.y+r.h/2+6);c.fill()}continue}
 if(type==='image'){if(n.tagName==='CANVAS')c.drawImage(n,r.x,r.y,r.w,r.h);else if(n.complete&&n.naturalWidth){const k=Math.min(r.w/n.naturalWidth,r.h/n.naturalHeight),iw=n.naturalWidth*k,ih=n.naturalHeight*k;c.imageSmoothingEnabled=true;c.drawImage(n,r.x+(r.w-iw)/2,r.y+(r.h-ih)/2,iw,ih);c.imageSmoothingEnabled=false}continue}
 if(type==='text'){if(n.classList.contains('arcade-key')){const x=r.x+r.w/2,y=r.y+r.h/2;c.fillStyle='#02091b';c.fillRect(x-24,y-19,48,44);c.fillStyle=n.classList.contains('red')?'#eb3e39':n.classList.contains('green')?'#22af56':'#efa71d';c.beginPath();c.moveTo(x-15,y-23);c.lineTo(x+15,y-23);c.lineTo(x+23,y-15);c.lineTo(x+23,y+15);c.lineTo(x+15,y+23);c.lineTo(x-15,y+23);c.lineTo(x-23,y+15);c.lineTo(x-23,y-15);c.closePath();c.fill();c.strokeStyle='#ffe583';c.lineWidth=3;c.stroke();c.fillStyle='#ffffff44';c.fillRect(x-12,y-17,24,4)}let size=18,color='#fff1a2',textRect={...r};const tag=n.tagName;
 if(tag==='H1'){size=Math.min(w<550?20:28,(r.w-14)/(e.text.length*.61));color='#ffdc46'}else if(tag==='H2'){size=n.classList.contains('arcade-map-title')?14:24;color='#69eaff'}else if(tag==='SMALL'){size=12;color='#b4dfff'}else if(tag==='STRONG'){size=n.closest('.arcade-stat')?24:n.closest('.arcade-mode-tile')?24:19;color='#ffe351'}else if(tag==='TH'||tag==='TD'){size=17;color=tag==='TH'?'#5de5ff':'#fff2a4';if(n.parentElement.classList.contains('player-row'))color='#ffe44e'}else if(n.classList.contains('arcade-stat')){size=12;color='#73def9';textRect.h=20}else if(n.classList.contains('arcade-1p')){size=23;color='#ffe345'}else if(tag==='P'){size=n.classList.contains('arcade-city-name')?17:14;color='#ffe96b';if(n.classList.contains('arcade-prompt'))panel({x:r.x-8,y:r.y-4,w:r.w+16,h:r.h+8},10)}else if(n.classList.contains('arcade-team-name')){size=Math.min(15,(r.w-12)/(Math.max(...e.text.split(/\s+/).map(s=>s.length))* .61));color='#fff1a2'}else if(tag==='SPAN'&&!n.className){size=Math.min(18,(r.w-14)/(e.text.length*.61))}else if(tag==='BUTTON'){size=n.classList.contains('arcade-mode-tile')?32:n.classList.contains('arcade-team-tile')?12:Math.min(16,(r.w-22)/(e.text.length*.61));if(n.classList.contains('arcade-mode-tile')){textRect.y+=22;textRect.h=55}else if(n.classList.contains('arcade-team-tile')){const img=n.querySelector('img');if(img){if(n.closest('.arcade-map-team-strip')){textRect.x+=30;textRect.w-=30}else{textRect.y+=50;textRect.h-=50}}}}
 lettering(e.text,textRect,size,color);}
 }
 // Subtle CRT lines are part of the drawn output, rather than CSS cards.
 c.fillStyle='rgba(0,0,0,'+(.085*(window.S9ArcadeEvolution?.settings.effects??1))+')';for(let y=0;y<h;y+=4)c.fillRect(0,y,w,1);
 if(!ready&&stadium.naturalWidth&&bezel.naturalWidth){ready=true;canvas.dataset.ready='true'}
 }
 function dispose(){if(!alive)return;alive=false;observer.disconnect();window.removeEventListener('resize',invalidate);box.removeEventListener('scroll',invalidate);if(mapURL)URL.revokeObjectURL(mapURL);canvas.remove();box.classList.remove('arcade-drawn')}
 requestAnimationFrame(draw);return dispose;
}
window.S9ArcadeDrawnMenu={mount};
})();
