/* Offline arcade hub: fast launch, guided challenges and resumable competitions. */
(function(){
'use strict';
const V=window.S9ArcadeEvolution,S=V.settings,P=V.progress;
const node=(tag,text,parent)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(parent)parent.append(n);return n};
function button(parent,text,fn){const b=node('button',text,parent);b.type='button';b.onclick=fn;return b}
function result(parent,r,names=['CASA','OSPITI']){const panel=node('section',undefined,parent);panel.className='evo-result';if(r.objective)node('h3',(r.objective.success?'OBIETTIVO SUPERATO':'RIPROVA')+' · '+r.objective.name+' '+('★'.repeat(r.objective.medal)),panel);const ts=r.stats?.teams;if(ts){const table=node('table',undefined,panel);const head=node('tr',undefined,table);node('th','',head);for(const n of names)node('th',n,head).className='evo-team';for(const [label,key] of [['Tiri','shots'],['Parate','saves'],['Passaggi riusciti','completedPasses'],['Contrasti vinti','tackles'],['Pali e traverse','posts']]){const row=node('tr',undefined,table);node('th',label,row);for(const t of ts)node('td',t[key]||0,row)}}if(r.mvp)node('p','Migliore in campo: '+r.mvp,panel);node('p','PROGRESSO '+(r.xp||P.xp)+' XP',panel)}
function settings(parent,onClose){const panel=node('section',undefined,parent);panel.className='evo-settings';node('h2','IMPOSTAZIONI',panel);const field=(name)=>{const label=node('label',name,panel);return label};
 const camera=node('select',undefined,field('Camera'));for(const [v,l] of [['close','Ravvicinata'],['panoramic','Panoramica'],['wide','Campo largo']]){const o=node('option',l,camera);o.value=v}camera.value=S.camera;camera.onchange=()=>{S.camera=camera.value;V.save()};
 for(const [key,label] of [['radar','Radar'],['vibration','Vibrazione joypad'],['fantasy','Fantasia arcade · fiamme e scie']]){const input=node('input',undefined,field(label));input.type='checkbox';input.checked=S[key];input.onchange=()=>{S[key]=input.checked;V.save()}}
 for(const [key,label] of [['volume','Volume generale'],['effects','Flash e scanline']]){const input=node('input',undefined,field(label));input.type='range';input.min=0;input.max=1;input.step=.05;input.value=S[key];input.oninput=()=>{S[key]=+input.value;V.save();window.S9ArcadeStadium?.setVolume?.();window.S9ArcadeMusic?.setVolume?.()}}
 const B=window.S9ArcadeBindings,err=node('p','',panel);err.setAttribute('role','status');
 if(B){node('p','Seleziona un comando e premi il nuovo tasto. Per assegnare Tab, clicca prima sul campo. Nello stesso profilo i tasti occupati si scambiano. Le modifiche valgono dalla prossima partita.',panel);
 for(const [group,title,commands] of [['p1','TASTIERA 1P',B.play],['p2','TASTIERA 2P',B.play],['menu','MENU E INTRO',B.menu],['system','COMANDI GENERALI',B.system]]){node('h3',title,panel);const rows=[];for(const [action,label] of commands){const input=node('input',undefined,field(label));input.readOnly=true;input.value=B.label(B.map(group)[action]);input.setAttribute('aria-label',title+' '+label);rows.push([input,action]);let armed=false;input.onclick=()=>{armed=true;input.value='PREMI UN TASTO'};input.onkeydown=e=>{if(e.key==='Tab'&&!armed)return;armed=false;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation?.();try{B.set(group,action,e.key);for(const [n,a] of rows)n.value=B.label(B.map(group)[a]);err.textContent='Comando salvato'}catch(error){err.textContent=error.message}}}}
 for(const [group,title,commands] of [...Array.from({length:4},(_,i)=>['pad'+i,'JOYPAD '+(i+1),[...B.play,...B.system]]),['padmenu','JOYPAD · MENU', [...B.menu,...B.system]]]){node('h3',title,panel);const rows=[];for(const [action,label] of commands){const select=node('select',undefined,field(label));for(let i=0;i<32;i++){const option=node('option',i+' · '+({0:'A / ×',1:'B / ○',2:'X / □',3:'Y / △',4:'LB / L1',5:'RB / R1',6:'LT / L2',7:'RT / R2',8:'BACK / SHARE',9:'START / OPTIONS',12:'D-PAD ↑',13:'D-PAD ↓',14:'D-PAD ←',15:'D-PAD →'}[i]||'PULSANTE'),select);option.value=i}select.value=B.map(group)[action];rows.push([select,action]);select.onchange=()=>{B.set(group,action,select.value);for(const [n,a] of rows)n.value=B.map(group)[a];err.textContent='Pulsante salvato'}}}
 button(panel,'RIPRISTINA COMANDI',()=>{B.reset();panel.remove();settings(parent,onClose)});
 }
 button(panel,'CHIUDI',()=>{panel.remove();onClose?.()});return panel}
function schedule(ids){const list=ids.slice(),rounds=[];if(list.length%2)list.push(null);for(let r=0;r<list.length-1;r++){const fixtures=[];for(let i=0;i<list.length/2;i++){const h=list[i],a=list[list.length-1-i];if(h&&a)fixtures.push(r%2?[a,h]:[h,a])}rounds.push(fixtures);list.splice(1,0,list.pop())}return rounds}
function standings(run){const table=Object.fromEntries(run.ids.map(id=>[id,{id,played:0,pts:0,gf:0,ga:0}]));for(const r of run.results){for(const [id,gf,ga] of [[r.h,r.hg,r.ag],[r.a,r.ag,r.hg]]){const t=table[id];t.played++;t.gf+=gf;t.ga+=ga;t.pts+=gf>ga?3:gf===ga?1:0}}return Object.values(table).sort((a,b)=>b.pts-a.pts||(b.gf-b.ga)-(a.gf-a.ga)||b.gf-a.gf||run.ids.indexOf(a.id)-run.ids.indexOf(b.id))}
function open(onClose){
 const box=node('div');box.id='arcade-evolution';box.setAttribute('role','dialog');box.setAttribute('aria-label','Centro Arcade');document.body.append(box);const disposeArt=window.S9ArcadeDrawnMenu?.mount(box);let view='home',last=null,busy=false,mode='quick',challenge='comeback';let run=null;let category='club';let selected=V.settings.lastHome,opponent=V.settings.lastAway,difficulty=S.lastDifficulty||'normale',formation=S.lastFormation||'4-4-2';let lastConfig=null;
 const get=id=>S9ArcadeRoster.get(id),pool=()=>S9ArcadeRoster.pool(category);
 const load=()=>{try{return JSON.parse(localStorage.getItem('sa2000:evolutionRun'))}catch(_){return null}};
 const persist=()=>{try{localStorage.setItem('sa2000:evolutionRun',JSON.stringify(run))}catch(_){}};
 function close(){if(busy)return;disposeArt?.();box.remove();document.removeEventListener('keydown',keys,true);onClose?.()}
 function frame(title){box.replaceChildren();const head=node('header',undefined,box);node('h1',title,head);button(head,'MENU',close);return node('main',undefined,box)}
 function action(parent,text,fn){return button(parent,text,async()=>{if(busy)return;try{await fn()}catch(e){node('p',e.message,parent).setAttribute('role','alert')}})}
 async function launch(config){busy=true;box.style.display='none';lastConfig=config;try{last=await launchArcadeMatch(config);return last}finally{box.style.display='';busy=false}}
 const match=(h,a,extra={})=>({home:get(h),away:get(a),cleanNames:true,difficulty,onlineMode:['league','survival','challenge','academy'].includes(mode)?'coop':undefined,homeState:{formation},allowDraw:true,...extra});
 function picker(parent,label,id,onChange){const section=node('section',undefined,parent);node('h3',label,section);const search=node('input',undefined,section);search.type='search';search.placeholder='Cerca squadra';search.setAttribute('aria-label','Cerca '+label);const filter=node('select',undefined,section);for(const [v,l] of [['all','Tutte'],['favorites','Preferite'],['recent','Recenti']]){const o=node('option',l,filter);o.value=v}const select=node('select',undefined,section);select.size=6;select.setAttribute('aria-label',label);const favorite=button(section,'☆ PREFERITA',()=>{const ids=S.favorites||[];S.favorites=ids.includes(select.value)?ids.filter(x=>x!==select.value):[...ids,select.value];V.save();draw()});
 function draw(){const q=search.value.toLowerCase(),ids=filter.value==='favorites'?S.favorites:filter.value==='recent'?S.recent:null;select.replaceChildren();for(const t of pool().filter(t=>t.name.toLowerCase().includes(q)&&(!ids||ids.includes(t.id)))){const o=node('option',t.name,select);o.value=t.id}if([...select.options].some(o=>o.value===id))select.value=id;else if(select.options.length){id=select.value;onChange(id)}favorite.textContent=(S.favorites||[]).includes(select.value)?'★ PREFERITA':'☆ PREFERITA'}select.onchange=()=>{id=select.value;onChange(id);draw()};search.oninput=draw;filter.onchange=draw;draw();return section}
 function remember(){S.lastHome=selected;S.lastAway=opponent;S.lastDifficulty=difficulty;S.lastFormation=formation;S.recent=[...new Set([selected,opponent,...(S.recent||[])])].slice(0,10);V.save()}
 function render(){if(view==='home'){const main=frame('CENTRO ARCADE');node('p','PARTITE VELOCI · SFIDE · PROGRESSO '+P.xp+' XP',main);const grid=node('div',undefined,main);grid.className='evo-grid';for(const [key,label,desc] of [['quick','PARTITA RAPIDA','Impostazioni ricordate e rivincita'],['challenge','SFIDE ARCADE','Rimonta, gol al volo e inferiorità numerica'],['academy','ALLENAMENTO GUIDATO','Passaggi, difesa e dribbling con medaglie'],['league','CAMPIONATO BREVE','6 squadre, 5 giornate, salvataggio automatico'],['local','TORNEO LOCALE','4 squadre, 2 giocatori che si alternano'],['survival','SURVIVAL','Una sconfitta chiude la serie'],['special','REGOLE SPECIALI','Golden goal, niente falli, super portieri e palla veloce']]){const b=action(grid,label,()=>{mode=key;view='setup';render()});node('small',desc,b)}const saved=load();if(saved&&!saved.done)action(main,'RIPRENDI '+saved.label,()=>{run=saved;category=saved.category||'club';formation=saved.formation||'4-4-2';view='competition';render()});action(main,'ONLINE · STANZA PRIVATA',()=>{box.style.display='none';S9ArcadeOnline.open(()=>{box.style.display='';render()})});action(main,'OPZIONI · COMANDI · JOYPAD',()=>{view='settings';render()});action(main,'GOL SALVATI',()=>{if(!window.S9ArcadeGoals)return;box.style.display='none';S9ArcadeGoals.open(()=>{box.style.display='';render()})});action(main,'SPOGLIATOIO · SBLOCCHI',()=>{view='cosmetics';render()});return}
 if(view==='settings'){view='home';if(window.S9ArcadeOptions){box.style.display='none';S9ArcadeOptions.open({onClose:()=>{box.style.display='';render()}});return}const main=frame('PREFERENZE');settings(main,()=>{view='home';render()});return}
 if(view==='cosmetics'){const main=frame('SPOGLIATOIO');node('p',P.xp+' XP · Partita: 20 XP · Sfida superata: 50 XP',main);for(const key of ['ball','pitch','kit','celebration']){const section=node('section',undefined,main);action(section,'CLASSICO · '+key,()=>{S[key]='classic';V.save();render()});for(const item of V.cosmetics.filter(c=>c.key===key)){const b=action(section,item.name+' · '+item.xp+' XP'+(S[key]===item.value?' · EQUIPAGGIATO':''),()=>{S[key]=item.value;V.save();render()});b.disabled=P.xp<item.xp}}return}
 if(view==='setup'){const main=frame({quick:'PARTITA RAPIDA',challenge:'SFIDE ARCADE',academy:'ACCADEMIA',league:'CAMPIONATO BREVE',local:'TORNEO LOCALE',survival:'SURVIVAL',special:'REGOLE SPECIALI'}[mode]);const cat=node('select',undefined,main);for(const [v,l] of [['club','Club'],['national','Nazionali']]){const o=node('option',l,cat);o.value=v}cat.value=category;cat.onchange=()=>{category=cat.value;selected=null;opponent=null;render()};selected=pool().some(t=>t.id===selected)?selected:pool()[0].id;opponent=pool().some(t=>t.id===opponent)&&opponent!==selected?opponent:pool()[1].id;const teams=node('div',undefined,main);teams.className='evo-grid';picker(teams,'LA TUA SQUADRA',selected,id=>selected=id);if(['quick','special'].includes(mode))picker(teams,'AVVERSARIO',opponent,id=>opponent=id);
 const diff=node('select',undefined,main);diff.setAttribute('aria-label','Difficoltà');for(const id of S9ArcadeDifficulty.order){const o=node('option',S9ArcadeDifficulty.LEVELS[id].label,diff);o.value=id}diff.value=difficulty;diff.onchange=()=>difficulty=diff.value;const shape=node('select',undefined,main);shape.setAttribute('aria-label','Modulo');for(const f of ['4-4-2','4-3-3','3-5-2','5-3-2']){const o=node('option',f,shape);o.value=f}shape.value=formation;shape.onchange=()=>formation=shape.value;
 let rule='golden';if(['challenge','academy'].includes(mode)){const ids=mode==='academy'?['passing','defending','dribbling']:['comeback','volley','resist'];if(!ids.includes(challenge))challenge=ids[0];const select=node('select',undefined,main);const description=node('p',(V.describe?V.describe(challenge):V.challenges[challenge].description),main);for(const id of ids){const o=node('option',V.challenges[id].name+' '+('★'.repeat(P.medals[id]||0)),select);o.value=id}select.value=challenge;select.onchange=()=>{challenge=select.value;description.textContent=(V.describe?V.describe(challenge):V.challenges[challenge].description)}}
 if(mode==='special'){const select=node('select',undefined,main);for(const [v,l] of [['golden','Golden goal immediato'],['nofouls','Niente falli'],['keepers','Super portieri'],['fastball','Pallone veloce']]){const o=node('option',l,select);o.value=v}select.onchange=()=>rule=select.value}
 if(mode==='local')node('p','Ogni partecipante sceglie una squadra diversa. Frecce + Z/C/X/V/SHIFT contro WASD + J/K/L/I/U. In alternativa usa due joypad. Ogni partita mostra le squadre da assegnare.',main);
 const entrants=[];if(mode==='local'){for(let i=0;i<4;i++){entrants[i]=pool()[i].id;picker(main,'PARTECIPANTE '+(i+1),entrants[i],id=>entrants[i]=id)}}
 action(main,'AVVIA',async()=>{remember();if(['league','local','survival'].includes(mode)){const ids=mode==='local'?entrants:[selected,...pool().filter(t=>t.id!==selected).sort((a,b)=>Math.abs((a.strength||75)-75)-Math.abs((b.strength||75)-75)).slice(0,5).map(t=>t.id)];if(new Set(ids).size!==ids.length)throw Error('Scegli squadre diverse per i quattro partecipanti.');run={mode,category,formation,label:mode==='league'?'CAMPIONATO':mode==='local'?'TORNEO LOCALE':'SURVIVAL',ids,user:selected,difficulty,round:0,results:[],fixtures:mode==='league'?schedule(ids):mode==='local'?[[[ids[0],ids[1]],[ids[2],ids[3]]]]:[],wins:0,done:false};persist();view='competition';render();return}const r=await launch(match(selected,opponent,{challenge:['challenge','academy'].includes(mode)?challenge:undefined,specialRule:mode==='special'?rule:undefined}));view=r?'result':'setup';render()});return}
 if(view==='result'){const main=frame('RISULTATO');node('h2',last.homeGoals+' : '+last.awayGoals,main);result(main,last);action(main,'RIVINCITA / RIPROVA',async()=>{const r=await launch(lastConfig);if(r){view='result';render()}else{view='home';render()}});action(main,'CAMBIA SQUADRE',()=>{view='setup';render()});action(main,'CENTRO ARCADE',()=>{view='home';render()});return}
 if(view==='competition'){const main=frame(run.label);if(run.results.length){const r=run.results[run.results.length-1];node('p',get(r.h).name+' '+r.hg+' — '+r.ag+' '+get(r.a).name,main)}
 if(run.mode==='league'){const table=node('table',undefined,main);const header=node('tr',undefined,table);for(const l of ['SQUADRA','G','PT','GF','GS'])node('th',l,header);for(const t of standings(run)){const row=node('tr',undefined,table);for(const v of [get(t.id).name,t.played,t.pts,t.gf,t.ga])node('td',v,row)}}
 if(run.done){node('h2',run.mode==='survival'?'SERIE TERMINATA · '+run.wins+' VITTORIE · RECORD '+P.bestSurvival:'CAMPIONE · '+get(run.champion).name,main);action(main,'NUOVA COMPETIZIONE',()=>{view='setup';mode=run.mode;render()});return}
 let fixture;if(run.mode==='league')fixture=run.fixtures[run.round].find(f=>f.includes(run.user));else if(run.mode==='local'){fixture=run.fixtures[run.round].find(f=>!run.results.some(r=>r.round===run.round&&r.h===f[0]&&r.a===f[1]));node('p',run.round===0?'SEMIFINALI':'FINALE',main)}else{const enemies=pool().filter(t=>t.id!==run.user).sort((a,b)=>(a.strength||75)-(b.strength||75));fixture=[run.user,enemies[Math.min(enemies.length-1,Math.floor(run.wins*enemies.length/10))].id];node('p',run.wins+' VITTORIE · DIFFICOLTÀ CRESCENTE · RECORD '+P.bestSurvival,main)}
 node('h2',get(fixture[0]).name+' VS '+get(fixture[1]).name,main);if(run.mode==='local')node('p','1P: '+get(fixture[0]).name+' · 2P: '+get(fixture[1]).name,main);
 action(main,'GIOCA',async()=>{difficulty=run.mode==='survival'?run.wins<2?'facile':run.wins<5?'normale':'difficile':run.difficulty;const pads=[...(navigator.getGamepads?.()||[])].filter(Boolean);const players=run.mode==='local'?(pads.length>=2?[{team:0,device:'pad'+pads[0].index},{team:1,device:'pad'+pads[1].index}]:[{team:0,device:'kb'},{team:1,device:pads.length?'pad'+pads[0].index:'kb2'}]):[{team:fixture[0]===run.user?0:1,device:'all'}];const r=await launch(match(...fixture,{allowDraw:run.mode==='league',players,duration:run.mode==='survival'?90:120}));if(!r){render();return}const entry={h:fixture[0],a:fixture[1],hg:r.homeGoals,ag:r.awayGoals,winner:r.winner,round:run.round};run.results.push(entry);
 if(run.mode==='league'){for(const f of run.fixtures[run.round])if(!f.includes(run.user))run.results.push({h:f[0],a:f[1],...S9ArcadeRoster.simulate(...f,true),round:run.round});run.round++;if(run.round===run.fixtures.length){run.done=true;run.champion=standings(run)[0].id}}
 else if(run.mode==='local'){const rs=run.results.filter(r=>r.round===run.round);if(run.round===0&&rs.length===2){run.fixtures.push([[rs[0].winner,rs[1].winner]]);run.round++}else if(run.round===1){run.done=true;run.champion=r.winner}}
 else{if(r.winner===run.user){run.wins++;P.bestSurvival=Math.max(P.bestSurvival,run.wins);V.save()}else run.done=true}persist();render()});action(main,'TORNA AL CENTRO · SALVATO',()=>{view='home';render()});return}
 }
 function keys(e){if(box.style.display==='none'||/INPUT|SELECT|TEXTAREA/.test(e.target?.tagName))return;const B=window.S9ArcadeBindings,k=B?B.keyboard('menu',e):({ArrowUp:'arrowup',ArrowDown:'arrowdown',ArrowLeft:'arrowleft',ArrowRight:'arrowright',z:'confirm',Escape:'back'})[e.key];if(k==='back'){e.preventDefault();e.stopImmediatePropagation();if(view==='home')close();else{view='home';render()}return}if(['arrowup','arrowdown','arrowleft','arrowright','confirm'].includes(k)){e.preventDefault();e.stopImmediatePropagation();const items=[...box.querySelectorAll('button,select,input')].filter(n=>!n.disabled);let i=items.indexOf(document.activeElement);if(k==='confirm'){(i>=0?items[i]:items[1]||items[0])?.click()}else{const delta=k==='arrowleft'||k==='arrowup'?-1:1;items[(i+delta+items.length)%items.length]?.focus()}}}

 document.addEventListener('keydown',keys,true);render();
}
window.S9ArcadeHub={open,settings,result,schedule,standings};
})();
