var window=globalThis;function addEventListener(){}function removeEventListener(){};load('arcade/engine/core.js');load('arcade/engine/controllers.js');load('arcade/engine/penalties.js');load('arcade/engine/arcade-features.js');load('arcade/engine/assist.js');load('arcade/bridge.js');
function assert(v,s){if(!v)throw Error(s)}function pass(s){print('PASS '+s)}
load('game/catalog.js');const home=SA2000_CATALOG.club.find(t=>t.name==='Atalanta'),away={...SA2000_CATALOG.club.find(t=>t.name==='Bari')};
let seed=7;const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
function make(){const m=new S9ArcadeEngine.Match(new S9ArcadeEngine.InputManager());m.rules.allowDraw=true;ArcadeMatchBridge.setupTeam(m.teams[0],home,{formation:'4-4-2',cleanNames:true});ArcadeMatchBridge.setupTeam(m.teams[1],away,{formation:'4-4-2',cleanNames:true});m.restarts.kickoff(0);m.phase='PLAY';m.restarts.data=null;return m}
function step(m,n=1){for(let i=0;i<n;i++){m.update(1/120);m.input.end(1/120)}}
function hold(m,dx,dy){const d=m.input.down;d.clear();if(dx>.3)d.add('arrowright');if(dx<-.3)d.add('arrowleft');if(dy>.3)d.add('arrowdown');if(dy<-.3)d.add('arrowup')}
// Passes from random positions in a random arrow direction.
const done={x:[0,0],c:[0,0]};
for(const k of ['x','c'])for(let n=0;n<60;n++){const m=make(),p=m.teams[0].players[5+n%6];p.x=25+rnd()*45;p.y=8+rnd()*46;m.control(p);const a=rnd()*Math.PI*2;hold(m,Math.cos(a),Math.sin(a));step(m,24);if(m.ball.owner!==m.selected)continue;m.input.pressed.add(k);step(m);if(m.ball.owner)continue;done[k][1]++;for(let i=0;i<480;i++){step(m);if(m.ball.owner){if(m.ball.owner.team.id===0)done[k][0]++;break}if(m.phase!=='PLAY')break}}
assert(done.x[0]>=done.x[1]*.8&&done.c[0]>=done.c[1]*.85,'assisted passes intercepted too often '+JSON.stringify(done));pass('assisted lobs '+done.x.join('/')+' and ground passes '+done.c.join('/')+' reach a teammate');
// Short lob is never chosen when a longer option exists; lob lands away from the nearest marker.
{const m=make(),p=m.teams[0].players[6];p.x=50;p.y=31;m.control(p);hold(m,1,0);m.pass(p,true);const q=m.ball.passTarget,land=q.receiverIntent;assert(Math.hypot(q.x-p.x,q.y-p.y)>=12,'short lob chosen');assert(m.ball.vz>7,'assisted lob arc too low to clear markers');pass('assisted lob chooses a real target and a high arc')}
// Human slide aims at the carrier; CPU cannot steal a ball just won, nor tackle a running carrier from behind.
{const m=make(),d=m.teams[0].players[3],o=m.teams[1].players[9];o.x=40;o.y=30;d.x=38;d.y=27;d.face={x:-1,y:0};m.players.forEach(q=>{if(q!==d&&q!==o&&q.role!=='GK'){q.x=q.team.id?90:8;q.y=q.number*5}});m.control(o);m.selected=d;o.aiWait=5;m.input.pressed.add('c');step(m,6);assert(m.ball.owner===d,'assisted tackle missed adjacent carrier');const cpu=m.teams[1].players[6];cpu.x=d.x+1.6;cpu.y=d.y;cpu.face={x:-1,y:0};cpu.tackle(false);m.tackles(1/120);assert(m.ball.owner===d,'ball stolen during possession grace');pass('assisted tackle wins the ball and keeps it through the grace window')}
{const m=make(),h=m.teams[0].players[9],c=m.teams[1].players[3];h.x=60;h.y=31;m.control(h);m.ball.grace=0;hold(m,1,0);step(m,2);c.x=h.x-1.6;c.y=h.y;c.face={x:1,y:0};c.tackle(false);m.tackles(1/120);assert(m.ball.owner===h,'running carrier lost ball from behind');pass('running human carrier shields the ball from CPU tackles from behind')}
// Shot without arrows goes to the side away from the keeper.
{const m=make(),s=m.teams[0].players[9],g=m.teams[1].players[0];s.x=82;s.y=31;g.y=29;m.control(s);m.input.down.clear();m.shoot(s);assert(m.lastShot.aim>33,'shot not aimed at open side');pass('assisted shot targets the corner away from the keeper')}
// Human keeper catches ordinary CPU shots and is never left without automatic saves.
{let caught=0;for(let n=0;n<40;n++){const m=make(),s=m.teams[1].players[9],g=m.teams[0].players[0];s.x=16+rnd()*6;s.y=22+rnd()*18;m.control(s);m.teams.forEach(t=>t.players.forEach(p=>{if(p!==s&&p.role!=='GK'){p.x=50;p.y=31}}));m.selected=g;m.shoot(s);for(let i=0;i<300;i++){step(m);if(m.ball.owner===g){caught++;break}if(m.phase!=='PLAY'||m.ball.state==='rebound')break}}assert(caught>=28,'human keeper caught only '+caught);pass('human keeper catches '+caught+'/40 CPU shots, even when selected')}
// CPU keeper never re-catches his own distribution; attackers stay away while he holds the ball.
{const m=make(),g=m.teams[1].players[0],a=m.teams[0].players[9];g.x=97;g.y=31;m.control(g);a.x=95;a.y=31;m.selected=a;step(m,2);assert(Math.hypot(a.x-g.x,a.y-g.y)>=6.9,'attacker allowed next to keeper holding the ball');let recaught=false;g.aiWait=0;for(let i=0;i<360;i++){const before=m.ball.owner;step(m);if(before!==g&&m.ball.owner===g&&m.ball.lastTeam===1)recaught=true}assert(!recaught,'keeper caught his own throw');pass('CPU keeper distribution is never re-caught by himself and cannot be volleyed at point blank')}
