var window=globalThis,store={},saved=0,list=[];
var addEventListener=()=>{},removeEventListener=()=>{},requestAnimationFrame=()=>{};
var navigator={getGamepads:()=>list};
var document={documentElement:{},addEventListener(){},createElement:()=>({}),head:{append(){}}};
window.S9ArcadeEvolution={settings:{keys:{z:'b'}},save(){saved++;store.preferences=JSON.stringify(this.settings)}};
load('arcade/engine/core.js');load('game/bindings.js');load('arcade/ui/controls.js');
const B=S9ArcadeBindings,E=S9ArcadeEngine,S=S9ArcadeEvolution.settings;
function assert(v,s){if(!v)throw Error(s)}function pass(s){print('PASS '+s)}
assert(S.keys.z==='b'&&S.keys.arrowup==='arrowup'&&S.keys2.z==='j','migration');B.set('p1','arrowup','t');B.set('p2','z','o');let a=new E.InputManager({keys:'arrows'}),b=new E.InputManager({keys:'wasd'});assert(a.keymap.t==='arrowup'&&!a.keymap.arrowup&&b.keymap.o==='z'&&!b.keymap.j,'profiles');pass('stored action bindings migrate and both players can remap movement and actions');
B.set('p1','z','c');assert(S.keys.z==='c'&&S.keys.c==='b','swap');let refused=false;try{B.set('p1','z','f')}catch(_){refused=true}assert(refused,'global collision');B.set('system','fullscreen','f2');B.set('p1','z','f');B.set('menu','confirm','enter');B.set('menu','back','backspace');B.set('system','pause','tab');assert(B.keyboard('menu','Enter')==='confirm'&&B.keyboard('system','Tab')==='pause','all special keys');pass('duplicates swap within a profile, conflicting shared keys are rejected, and special keys can be assigned');
a=new E.InputManager({keys:'arrows'});a.active=true;a.onDown({key:'f',preventDefault(){}});a.end(.85);a.onUp({key:'f'});assert(a.shotPower===1&&a.shotBuffer>0,'charged remap');pass('remapped shooting retains hold, full charge and release behavior');
B.set('pad0','z',7);B.set('pad1','z',5);list=[{index:1,axes:[0,0],buttons:Array.from({length:16},(_,i)=>({pressed:i===5,value:i===5?1:0}))}];const remote=new E.InputManager({keys:null,pads:[1]});remote.active=true;remote.poll();assert(!remote.down.has('z'),'a button already held when the match starts must be released first');list[0].buttons[5].pressed=false;list[0].buttons[5].value=0;remote.poll();list[0].buttons[5].pressed=true;list[0].buttons[5].value=1;remote.poll();assert(remote.down.has('z'),'secondpad');remote.end(.85);list[0].buttons[5].pressed=false;list[0].buttons[5].value=0;remote.poll();assert(remote.shotPower===1,'padrelease');assert(B.padAction(7,0)==='z'&&B.padAction(5,1)==='z','separate pads');pass('independent gamepad mappings drive the assigned player and preserve charged releases');
window.S9ArcadeActive={paused:false};assert(S9ArcadeControls.keyFor(9,1)==='tab','mappedpause');S9ArcadeActive.paused=true;assert(S9ArcadeControls.keyFor(5,1)==='enter','mappedcontinue');S9ArcadeActive=null;B.set('padmenu','confirm',3);assert(S9ArcadeControls.keyFor(3)==='enter','mappedmenu');pass('gamepad menu, pause and result events use current physical keyboard bindings');
const persisted=JSON.parse(store.preferences);assert(persisted.keys2.z==='o'&&persisted.padKeys[1].z===5,'save');B.reset();assert(S.keys.z==='z'&&S.keys2.z==='j'&&S.systemKeys.pause==='escape'&&S.padKeys[1].z===0,'reset');pass('all keyboard and gamepad profiles persist and reset together');
