var window=globalThis,noop=()=>{},document={querySelectorAll:()=>[],querySelector:()=>null,getElementById:()=>null,createElement:()=>({style:{},append:noop}),body:{}};var MutationObserver=class{observe(){}};function addEventListener(){}function removeEventListener(){}
var store={},localStorage={getItem:k=>k in store?store[k]:null,setItem:(k,v)=>{store[k]=String(v)},removeItem:k=>{delete store[k]}};
load('game/shim.js');load('game/catalog.js');load('arcade/assets/europe-map.js');load('arcade/assets/regional-maps.js');load('arcade/ui/roster.js');load('arcade/ui/menu.js');
load('arcade/engine/core.js');load('arcade/engine/controllers.js');load('arcade/engine/penalties.js');load('arcade/engine/arcade-features.js');load('arcade/bridge.js');
function assert(v,s){if(!v)throw Error(s)}function pass(s){print('PASS '+s)}
const clubs=S9ArcadeRoster.pool('club'),nations=S9ArcadeRoster.pool('national');
assert(clubs.length===80&&nations.length===65,'catalog size');for(const list of [clubs,nations])assert(new Set(list.map(t=>t.name)).size===list.length&&new Set(list.map(t=>t.id)).size===list.length,'duplicate team');pass('standalone catalog: 80 clubs and 65 national teams, one entry each');
for(const t of [...clubs,...nations]){assert(t.players.length>=11&&t.players.some(p=>p.pos==='GK'),'incomplete squad '+t.name);const png=readFile(t.crest,'binary');assert(png[1]===80&&png[2]===78&&png[3]===71,'missing crest '+t.crest);assert(t.arcadeKit?.shirtPrimary&&t.arcadeKit.pattern,'kit '+t.name)}pass('every squad is complete, with a local PNG patch crest and a kit');
for(const [list,category] of [[clubs,'club'],[nations,'national']]){const zones=new Set(S9ArcadeRegions.zones(category).map(z=>z.id));for(const t of list){const z=S9ArcadeRegions.regionFor(t),p=S9ArcadeUI.regionalLocation(t,z);assert(zones.has(z),'zone '+t.name);assert(p&&p.city&&p.x>0&&p.x<420&&p.y>0&&p.y<500,'marker outside map '+t.name)}}pass('every team sits in a selectable zone with its city inside the map');
for(const t of [...clubs,...nations]){const m=new S9ArcadeEngine.Match(new S9ArcadeEngine.InputManager());ArcadeMatchBridge.setupTeam(m.teams[0],t,{cleanNames:true});ArcadeMatchBridge.setupTeam(m.teams[1],clubs[0],{cleanNames:true});m.restarts.kickoff(0);m.input.pressed.add('c');m.update(1/120);assert(m.phase==='PLAY','kickoff failed '+t.name)}pass('every catalog team loads through the match bridge and kicks off');
S9Save.putSetting('arcadePureCup',{v:1});S9Save.getSetting('arcadePureCup').then(v=>{assert(v?.v===1&&'sa2000:arcadePureCup' in store,'save shim');pass('settings and tournaments persist in local storage under the game prefix')});
