var window=globalThis;function addEventListener(){}function removeEventListener(){};load('arcade/engine/core.js');load('arcade/engine/controllers.js');load('arcade/engine/penalties.js');load('arcade/engine/arcade-features.js');load('arcade/engine/assist.js');load('arcade/engine/difficulty.js');load('arcade/engine/setpieces.js');load('arcade/bridge.js');load('game/catalog.js');
function assert(v,s){if(!v)throw Error(s)}function pass(s){print('PASS '+s)}
const E=S9ArcadeEngine,clubs=SA2000_CATALOG.club,home=clubs.find(t=>t.name==='Boca Juniors'),away=clubs.find(t=>t.name==='River Plate');
function game(sides,level='normale'){const inputs=sides.map(()=>new E.InputManager({keys:null}));inputs.forEach(i=>i.active=true);const m=new E.Match(inputs[0]);ArcadeMatchBridge.setupTeam(m.teams[0],home,{cleanNames:true});ArcadeMatchBridge.setupTeam(m.teams[1],away,{cleanNames:true});m.setHumans(sides.map((team,i)=>({team,input:inputs[i]})));S9ArcadeDifficulty.apply(m,level);m.rules.allowDraw=true;return {m,inputs}}
function bot(m,h,t){const s=h.selected,b=m.ball,i=h.input,rd=m.restarts.data;if(m.phase==='FREEKICK'&&m.fk){const fk=m.fk;if(m.fkHumans().shooter===h){if(fk.stage==='ready'&&!fk.button&&fk.age>.7)i.press('z');else if(fk.button&&fk.power>.6)i.release('z')}if(fk.stage==='result'&&t%20===0)i.pressed.add('z');return}if(m.phase==='RESTART'&&rd?.aim&&rd.taker===s){if(!rd.aim.button){if(t%30===0)i.press('c')}else if(rd.aim.power>.35)i.release('c');return}i.release('c');i.down.clear();if(!s)return;const dir=m.teams[h.team].dir,tgt=b.owner===s?{x:s.x+dir*10,y:31}:b.owner&&b.owner.team.id===h.team?{x:b.owner.x+dir*8,y:s.home.y}:b;const dx=tgt.x-s.x,dy=tgt.y-s.y;if(dx>.5)i.down.add('arrowright');if(dx<-.5)i.down.add('arrowleft');if(dy>.5)i.down.add('arrowdown');if(dy<-.5)i.down.add('arrowup');
 if(m.phase==='RESTART'||m.phase==='PENALTIES'){if(t%30===0){i.pressed.add('c');i.pressed.add('z')}return}if(b.owner===s){if((dir>0?s.x>76:s.x<24)&&t%40===0){i.shotBuffer=.28;i.shotPower=.7}else if(t%90===0)i.pressed.add(t%180?'c':'x')}else if(b.owner&&b.owner.team.id!==h.team&&Math.hypot(b.owner.x-s.x,b.owner.y-s.y)<3&&t%50===0)i.pressed.add('c')}
for(const [name,sides] of [['co-op 1P+2P vs CPU',[0,0]],['1P vs 2P',[0,1]],['2 contro 2',[0,0,1,1]]]){const {m,inputs}=game(sides);let t=0,distinctOk=true,switches=new Set();
 for(;t<40000&&m.phase!=='FINISHED';t++){for(const h of m.humans)bot(m,h,t);m.update(1/120);inputs.forEach(i=>i.end(1/120));const sel=m.humans.map(h=>h.selected).filter(Boolean);if(new Set(sel).size!==sel.length)distinctOk=false;if(m.ball.owner&&m.isControlled(m.ball.owner))switches.add(m.humanOf(m.ball.owner).slot);for(const h of m.humans)assert(!h.selected||h.selected.team.id===h.team,'human controls opposing player')}
 assert(m.phase==='FINISHED','match did not finish '+name);assert(distinctOk,'two humans controlled the same player in '+name);assert(switches.size===m.humans.length,'some human never had the ball in '+name+' '+[...switches]);
 assert(m.teams.every(team=>m.teamHasHumans(team)?!team.cpu:!!team.cpu),'difficulty applied to a human side');pass(name+' plays a full match '+m.rules.score.join('-')+' with distinct players per human and every human on the ball')}
{const {m}=game([0,0]);const h2=m.humans[1],p=m.humans[0].selected;m.control(p);m.lastPasser=p;const q=m.teams[0].players.find(x=>x!==p&&x!==h2.selected&&x.role!=='GK');m.control(q);assert(m.humans[0].selected===q&&h2.selected!==q,'pass receiver did not follow the passer');pass('co-op: receiving a pass moves control to the passer, the partner keeps his player')}
{const {m}=game([0,1]);m.startPenalties();const hp=m.penaltyHumans();assert(hp.shooter===m.humans[0]&&hp.keeper===m.humans[1]&&m.humans[1].selected.role==='GK','penalty roles');pass('versus shootout: 1P shoots, 2P controls the keeper')}
{const lv=S9ArcadeDifficulty.LEVELS;assert(lv.facile.coins>lv.normale.coins&&lv.normale.coins>lv.difficile.coins,'coins');const easy=game([0],'facile').m,hard=game([0],'difficile').m;assert(easy.teams[1].cpu.pace<hard.teams[1].cpu.pace&&easy.teams[1].players[5].attributes.defending<hard.teams[1].players[5].attributes.defending,'difficulty');pass('difficulty levels weaken only the CPU side and grant more coins on easier levels')}

// Set pieces: arrow swings, a press stops it, holding builds power, release plays the ball along the arrow.
for(const [type,key,state] of [['FREE KICK','z','shot'],['THROW IN','x','aerial'],['CORNER','x','aerial'],['FREE KICK','c','pass']]){const {m,inputs}=game([0]),i=inputs[0];const spot=type==='CORNER'?[99.5,.5]:type==='THROW IN'?[60,0]:[60,40];m.restarts.award(type,0,spot[0],spot[1]);const d=m.restarts.data;for(let k=0;k<200;k++){m.update(1/120);i.end(1/120)}const swing=new Set();for(let k=0;k<60;k++){m.update(1/120);swing.add(d.aim.angle.toFixed(2))}assert(swing.size>8,'arrow does not swing '+type);
 i.press(key);for(let k=0;k<100;k++){m.update(1/120);i.end(1/120)}const locked=d.aim.angle;assert(d.aim.power>.6,'power not charging '+type);i.release(key);m.update(1/120);i.end(1/120);assert(m.phase==='PLAY'&&m.ball.state===state,'set piece not played '+type+' '+m.ball.state);const dir=Math.atan2(m.ball.vy,m.ball.vx);assert(Math.abs(dir-locked)<.05,'ball ignores arrow '+type);pass(type+' with '+key.toUpperCase()+': swinging arrow, power hold, ball follows the stopped arrow')}
{const {m}=game([0]),h=m.humans[0],o=h.selected,c=m.teams[1].players[6];m.phase='PLAY';m.restarts.data=null;o.x=50;o.y=31;m.control(o);m.ball.grace=0;o.face={x:1,y:0};h.input.down.add('arrowright');m.update(1/120);c.x=o.x-1.8;c.y=o.y;c.face={x:1,y:0};c.tackle(false);m.tackles(1/120);assert(m.phase==='RESTART'&&m.restarts.data.type==='FREE KICK'&&m.restarts.data.team===0,'CPU foul from behind not whistled');pass('CPU tackle from behind on a running human is a free kick')}
{let fouls=0;for(const lv of ['facile','normale']){const {m,inputs}=game([0],lv);for(let t=0;t<40000&&m.phase!=='FINISHED';t++){bot(m,m.humans[0],t);m.update(1/120);inputs.forEach(i=>i.end(1/120))}fouls+=m.stats.teams[1].fouls||0;print('MATCH '+lv+' '+m.rules.score.join('-')+' CPU fouls '+(m.stats.teams[1].fouls||0)+' cards '+(m.stats.teams[1].yellowCards||0))}assert(fouls>=2,'still almost no fouls: '+fouls);pass('CPU commits fouls in real matches ('+fouls+' in two)')}
load('arcade/engine/freekick.js');
// Close free kick: scene with wall and keeper; outcomes resolve back onto the pitch.
for(const [label,lateral,power,curl,expect] of [['over the wall into the open corner',.85,.72,0,'goal'],['blasted over the bar',0,1,0,'over'],['low into the wall',-.1,.1,0,'wall'],['wide',1.35,.6,0,'wide']]){const {m,inputs}=game([0],'normale');m.phase='PLAY';m.restarts.data=null;m.restarts.award('FREE KICK',0,76,33);assert(m.restarts.data.foul&&m.restarts.data.scene,'foul beat missing');for(let k=0;k<400&&m.phase!=='FREEKICK';k++){m.update(1/120);inputs[0].end(1/120)}assert(m.phase==='FREEKICK'&&m.fk.wall.length===4,'scene not opened');const fk=m.fk;fk.kp=-.4;Object.assign(fk,{lateral,power,curl});m.fkStrike();fk.lateral=lateral;fk.cpuJump=false;const before=m.rules.score[0];for(let i=0;i<600&&m.phase==='FREEKICK';i++){if(m.fk?.stage==='result'&&m.fk.age>.7)inputs[0].pressed.add('z');m.update(1/120);inputs[0].end(1/120)}
 const kinds={goal:m.rules.score[0]===before+1,over:m.restarts.data?.type==='GOAL KICK',wide:m.restarts.data?.type==='GOAL KICK',wall:m.phase==='PLAY'&&m.ball.state==='rebound'};assert(kinds[expect],'free kick '+label+' gave phase '+m.phase+' score '+m.rules.score);pass('free kick scene: '+label+' → '+expect)}
{const {m,inputs}=game([0],'normale');m.phase='PLAY';m.restarts.data=null;m.restarts.award('FREE KICK',0,76,31);const i=inputs[0];for(let k=0;k<400&&m.phase!=='FREEKICK';k++){m.update(1/120);i.end(1/120)}for(let k=0;k<90;k++){m.update(1/120);i.end(1/120)}i.press('z');for(let k=0;k<90;k++){i.down.add('arrowleft');m.update(1/120);i.end(1/120)}assert(m.fk.power>.5&&m.fk.curl<-.5,'power/curl not charging');i.release('z');m.update(1/120);assert(m.fk.stage==='flight','strike not released');pass('free kick: press stops the aim, hold charges power, arrows add curl')}

// Foul beat and restart shape: everyone frozen for a second, keeper stays home, no single-file line.
{const {m,inputs}=game([0]);m.phase='PLAY';m.restarts.data=null;const g=m.teams[1].players[0];m.restarts.award('THROW IN',0,60,0);for(let k=0;k<240;k++){m.update(1/120);inputs[0].end(1/120)}assert(Math.abs(g.x-97)<2&&Math.abs(g.y-31)<3,'keeper left his goal on a throw-in');const xs=new Set(m.teams[1].players.filter(p=>p.role!=='GK').map(p=>Math.round(p.x/3)));assert(xs.size>=3,'defenders lined up in single file');pass('throw-in: CPU keeper holds his line and both teams keep their shape')}
{const {m,inputs}=game([0]);m.phase='PLAY';m.restarts.data=null;const o=m.teams[0].players[7],before=m.players.map(p=>[p.x,p.y]);o.x=40;o.y=30;m.control(o);m.restarts.award('FREE KICK',0,40,30);const d=m.restarts.data,moved=()=>m.players.some((p,i)=>p!==d.taker&&Math.hypot(p.x-snap[i][0],p.y-snap[i][1])>.05);const snap=m.players.map(p=>[p.x,p.y]);for(let k=0;k<100;k++){m.update(1/120);inputs[0].end(1/120)}assert(d.foul&&!moved(),'players moved during the foul freeze');for(let k=0;k<200;k++){m.update(1/120);inputs[0].end(1/120)}assert(moved(),'players never settle after the foul');pass('foul: whistle and FALLO beat freeze play for a second, then players walk into position')}
load('arcade/engine/training.js');
// Training: every drill keeps producing attempts and counts goals; the match clock never runs out.
for(const drill of ['direct','indirect','corner','penalty']){const {m,inputs}=game([0]);S9ArcadeTraining.setup(m,drill);const i=inputs[0];let t=0;for(;t<120*60&&m.training.attempts<5;t++){const fk=m.fk,rd=m.restarts.data,pen=m.pen;if(fk&&fk.stage==='ready'){if(!fk.button&&fk.age>.7)i.press('z');else if(fk.button&&fk.power>.62)i.release('z')}else if(m.phase==='RESTART'&&rd?.aim&&m.humanOf(rd.taker)){if(!rd.aim.button)i.press('x');else if(rd.aim.power>.5)i.release('x')}else if(m.phase==='PENALTIES'){if(t%50===0)i.pressed.add('z')}else if(m.phase==='PLAY'){i.release('z');i.release('x');const s=m.humans[0].selected;if(m.ball.owner===s){i.shotBuffer=.28;i.shotPower=.7}}m.update(1/120);i.end(1/120)}
 assert(m.training.attempts>=5,'drill '+drill+' stalled at '+m.training.attempts+' phase '+m.phase);assert(m.rules.remaining===120,'clock ran during training');pass('training '+drill+': '+m.training.attempts+' attempts, '+m.training.goals+' goals, no clock')}
{const {m,inputs}=game([0],'normale');m.phase='PLAY';m.restarts.data=null;m.restarts.award('FREE KICK',0,76,33);for(let k=0;k<400&&m.phase!=='FREEKICK';k++){m.update(1/120);inputs[0].end(1/120)}Object.assign(m.fk,{lateral:.85,power:.72,curl:0,kp:-.4});m.fkStrike();m.fk.cpuJump=false;for(let k=0;k<400&&m.phase==='FREEKICK';k++){if(m.fk?.stage==='result')inputs[0].pressed.add('z');m.update(1/120);inputs[0].end(1/120)}assert(m.fkReplay?.film.length>20,'no free-kick replay');const replay=new E.ReplayManager();replay.record(m,1/30,null);replay.start();assert(replay.playback===replay.fkFilm.film,'replay not the free-kick scene');pass('free-kick goals are replayed from the recorded scene')}
{let corners=0;for(const lv of ['facile','normale']){const {m,inputs}=game([0],lv);const award=m.restarts.award.bind(m.restarts);m.restarts.award=(type,...r)=>{if(type==='CORNER')corners++;return award(type,...r)};for(let t=0;t<40000&&m.phase!=='FINISHED';t++){bot(m,m.humans[0],t);m.update(1/120);inputs.forEach(i=>i.end(1/120))}}print('CORNERS in two matches '+corners);assert(corners>=2,'corners still rare: '+corners);pass('corners now happen in real matches ('+corners+' in two)')}
