var window=globalThis;function addEventListener(){}function removeEventListener(){}
var storage={};var localStorage={getItem:k=>storage[k]||null,setItem:(k,v)=>storage[k]=v};
var document={documentElement:{style:{setProperty(){}}}};
load('arcade/engine/core.js');load('arcade/engine/controllers.js');load('arcade/engine/arcade-features.js');load('arcade/engine/assist.js');load('arcade/engine/difficulty.js');load('arcade/engine/penalties.js');load('arcade/engine/setpieces.js');load('arcade/engine/training.js');load('arcade/engine/evolution.js');load('arcade/ui/evolution-hub.js');
const E=S9ArcadeEngine,V=S9ArcadeEvolution;
function assert(v,s){if(!v)throw Error(s)}function pass(s){print('PASS '+s)}
function make(config={}){const i=new E.InputManager();i.active=true;const m=new E.Match(i);V.setup(m,config);m.phase='PLAY';m.restarts.data=null;return m}
{const m=make(),before=m.selected;m.ball.owner=m.teams[1].players[9];m.input.pressed.add('switch');m.humanStep(1/120);assert(m.selected!==before,'manual switch');assert(m.selected.team.id===0&&m.selected.role!=='GK','legal defender');assert(m.selectionTimer>1,'manual selection lock');pass('manual defender switching locks a distinct outfield player')}
{const m=make();m.setHumans([{team:0,input:m.input},{team:0,input:new E.InputManager()}]);const h=m.humans[0],other=m.humans[1];const options=V.candidates(m,h);assert(!options.includes(other.selected),'coop switch collision');pass('co-op manual selection never steals another human player')}
{V.settings.keys.z='b';const i=new E.InputManager({keys:'arrows'});assert(i.keymap.b==='z'&&!i.keymap.z,'custom shooting binding');V.settings.keys.z='z';pass('custom bindings replace old keys')}
{const m=make({challenge:'comeback'});assert(m.rules.score.join(',')==='0,2'&&m.rules.remaining===60,'comeback setup');const r={homeGoals:2,awayGoals:2,stats:{}};V.record(m,r);assert(r.objective.success&&r.objective.medal===1,'comeback result');assert(storage['sa2000:progress'],'persisted reward');pass('comeback objective, medals and progress persistence')}
{const m=make({challenge:'resist'});assert(m.teams[0].players.filter(p=>!p.sentOff).length===10,'ten players');const r={homeGoals:0,awayGoals:1,stats:{}};V.record(m,r);assert(!r.objective.success&&r.objective.medal===0,'failed defensive objective');pass('inferiority challenge removes a player and rejects conceded goals')}
for(const [key,stat,count] of [['passing','completedPasses',8],['defending','tackles',3],['dribbling','dribbles',6]]){const m=make({challenge:key});m.stats.teams[0][stat]=count;m.update(1/120);assert(m.phase==='FINISHED','objective did not finish '+key);pass('guided '+key+' finishes at its real action target')}
{const m=make({challenge:'volley'});m.volleyShooter=m.lastShooter=m.teams[0].players[9];m.rules.goal(0);assert(m.objective.volleys===1,'volley goal');m.update(1/120);assert(m.phase==='FINISHED','volley completion');pass('volley challenge counts goals rather than shot attempts')}
{const rounds=S9ArcadeHub.schedule(['a','b','c','d','e','f']),seen=new Set();assert(rounds.length===5,'five rounds');for(const fixtures of rounds){assert(new Set(fixtures.flat()).size===6,'one fixture per round');for(const f of fixtures)seen.add(f.slice().sort().join(':'))}assert(seen.size===15,'unique pairings');const table=S9ArcadeHub.standings({ids:['a','b','c'],results:[{h:'a',a:'b',hg:2,ag:0},{h:'b',a:'c',hg:1,ag:1}]});assert(table[0].id==='a'&&table[0].pts===3&&table[1].id==='c','league ranking');pass('league round robin and deterministic points / goal difference standings')}
{const m=make({specialRule:'golden'});assert(m.rules.period==='GOLDEN','golden start');m.rules.goal(0);assert(m.phase==='FINISHED','golden winner');const k=make({specialRule:'keepers'});assert(k.teams[1].players[0].attributes.goalkeeping===100,'super keeper');const f=make({specialRule:'fastball'});f.control(f.teams[0].players[9]);f.shoot(f.selected);const speed=Math.hypot(f.ball.vx,f.ball.vy);f.update(1/120);assert(Math.hypot(f.ball.vx,f.ball.vy)>speed*1.1,'fast ball boost');pass('special match rules apply to actual play')}
{const m=make(),camera=new E.CameraController();for(const [name,zoom] of [['close',136],['panoramic',36],['wide',22]]){V.settings.camera=name;camera.update(m,1);assert(camera.zoom===zoom,'camera '+name)}V.settings.camera='panoramic';pass('three camera presets')}
{const m=make(),p=m.teams[0].players[9],unused=m.teams[0].players[6];m.control(p);m.pass(p);const q=m.ball.passTarget;const attempted=m.stats.teams[0].passes;m.control(q);assert(m.stats.teams[0].completedPasses===1&&attempted===1,'completed pass stat');pass('completed pass statistics count actual team receptions')}

{const m=make(),b=m.ball;b.owner=null;b.x=100.1;b.y=25.1;b.z=2;b.vx=40;b.vy=1;b.lastTeam=0;m.boundaries();assert(b.vx<0&&b.x<100&&m.rules.score[0]===0&&m.stats.teams[0].posts===1,'post rebound');pass('posts rebound into play with no phantom goal')}
{const m=make({specialRule:'nofouls'});m.restarts.award('FREE KICK',1,50,31);assert(m.phase==='PLAY'&&!m.restarts.data,'no foul restart');m.restarts.award('CORNER',0,99,0);assert(m.phase==='RESTART','normal restarts preserved');pass('no-fouls rule suppresses foul restarts and preserves corners')}
{const m=make();S9ArcadeTraining.setup(m,'direct');V.setup(m,{training:'direct'});m.training.attempts=5;m.training.goals=3;m.training.active=false;m.training.wait=1;m.update(1/120);assert(m.phase==='FINISHED','five attempt lesson completion');const r={homeGoals:3,awayGoals:0,stats:{}};V.record(m,r);assert(r.objective.medal===2&&V.progress.medals['training:direct']===2,'training medal');pass('set-piece lessons finish and persist earned medals')}
load('arcade/bridge.js');load('game/catalog.js');
{const m=make(),home=SA2000_CATALOG.club[0],away=SA2000_CATALOG.club[1];ArcadeMatchBridge.setupTeam(m.teams[0],home,{cleanNames:true});ArcadeMatchBridge.setupTeam(m.teams[1],away,{cleanNames:true});S9ArcadeDifficulty.apply(m,'facile');V.setup(m,{duration:3});m.rules.allowDraw=true;assert(m.teams[1].players[5].attributes.defending===ArcadeMatchBridge.attributes(m.teams[1].players[5].source).defending,'difficulty preserves player attributes');for(let i=0;i<1800&&m.phase!=='FINISHED';i++){m.update(1/120);m.input.end(1/120)}assert(m.phase==='FINISHED','integrated match finish');const r={homeGoals:m.rules.score[0],awayGoals:m.rules.score[1],stats:{}};V.record(m,r);assert(r.mvp&&r.stats.teams.length===2,'actual result stats');pass('real catalogue match finishes with decision-based difficulty and player statistics')}
