/* Fire-shot lifecycle, physics invariants and replay-safe rendering. */
var window=globalThis;function addEventListener(){}function removeEventListener(){}
var Image=class{constructor(){this.complete=true;this.naturalWidth=1024;this.naturalHeight=1200;this.width=1024;this.height=1200}};
var storage={},localStorage={getItem:k=>storage[k]||null,setItem:(k,v)=>storage[k]=v};
var strokes=0,polygons=0,ctx=new Proxy({stroke(){strokes++},fill(){polygons++}},{get:(t,k)=>k in t?t[k]:()=>{},set:(t,k,v)=>(t[k]=v,true)});
var document={documentElement:{style:{setProperty(){}}},createElement:()=>({getContext:()=>ctx})};
load('arcade/engine/core.js');load('arcade/engine/controllers.js');load('arcade/engine/art.js');load('arcade/engine/penalties.js');load('arcade/engine/setpieces.js');load('arcade/engine/visual.js');load('arcade/engine/freekick.js');load('arcade/engine/evolution.js');load('arcade/engine/fantasy.js');
const E=S9ArcadeEngine,V=S9ArcadeEvolution;
function assert(v,s){if(!v)throw Error(s)}function pass(s){print('PASS '+s)}
function make(){const i=new E.InputManager();i.active=true;const m=new E.Match(i);m.phase='PLAY';m.restarts.data=null;m.rules.allowDraw=true;const p=m.teams[0].players[9];p.x=70;p.y=31;m.control(p);return m}
function shot(m,power=1,volley=false){m.shoot(m.selected,volley,power);return m.ball.arcadeShot}
{const m=make();assert(!shot(m,.9),'below 95% should not ignite');assert(shot(m,.96)?.kind==='fire','95% charge ignites');assert(shot(m,1)?.kind==='fire','full power flame');assert(m.message==='FIRE SHOT!','fire announcement');m.control(m.teams[0].players[6]);assert(!m.ball.arcadeShot,'extinguish on reception');shot(m,1);m.pass(m.selected);assert(!m.ball.arcadeShot,'extinguish on new pass');shot(m,1);m.ball.reset();assert(!m.ball.arcadeShot,'extinguish on reset');pass('only full charge ignites; reception, pass and reset extinguish flames')}
{const m=make();m.input.shotPower=1;m.input.shotBuffer=.28;m.shoot(m.selected);assert(m.ball.arcadeShot?.kind==='fire','buffered full charge');const n=make();assert(shot(n,1,true)?.kind==='meteor','full volley meteor');const cpu=make();cpu.shoot(cpu.teams[1].players[9]);assert(!cpu.ball.arcadeShot,'default CPU shot should not be full charge');pass('buffered full-power shots ignite, volleys become meteors, ordinary CPU shots stay normal')}
{const m=make();shot(m);m.ball.state='rebound';m.update(0);assert(!m.ball.arcadeShot,'rebound still burning');shot(m);m.restarts.award('THROW IN',1,50,0);assert(!m.ball.arcadeShot,'restart still burning');m.reset();assert(!m.arcadeImpact,'stale impact after match reset');pass('rebounds and restarts stop flames and match reset clears impact state')}
{const m=make();shot(m);m.ball.x=100.1;m.ball.y=31;m.ball.z=2;m.boundaries();assert(m.rules.score[0]===1&&m.arcadeImpact.kind==='goal'&&m.message==='SUPER GOAL!','fire goal impact');assert(!m.ball.arcadeShot,'kickoff still burning');const n=make();shot(n,.5);n.ball.x=100.1;n.ball.y=31;n.ball.z=2;n.boundaries();assert(n.message==='GOAL!','ordinary goal became super goal');pass('fire goals get comic impact and ordinary goals retain their presentation')}
{function physical(m){return JSON.stringify(['x','y','z','vx','vy','vz','state'].map(k=>m.ball[k]))}const a=make(),b=make();V.settings.fantasy=true;shot(a);V.settings.fantasy=false;shot(b);assert(physical(a)===physical(b),'fantasy altered shot physics');V.settings.fantasy=true;pass('fantasy presentation leaves shot trajectory, speed and scoring rules unchanged')}
{const m=make();m.beginFreeKick(0,76,31);m.fk.power=1;m.fkStrike();assert(m.fk.arcadeShot?.kind==='fire','full free kick');const n=make();n.beginFreeKick(0,76,31);n.fk.power=.8;n.fkStrike();assert(!n.fk.arcadeShot,'normal free kick ignited');pass('full-power direct free kicks also ignite')}
{const m=make(),p=shot(m),impact=m.arcadeImpact,film=new E.ReplayManager();m.elapsed=.12;film.record(m,.04,{x:70,y:31,zoom:36});m.control(m.teams[0].players[6]);const liveOwner=m.ball.owner,liveState=m.ball.state,liveImpact=m.arcadeImpact;film.start();const renderer={camera:{x:50,y:31},text(){},draw(frame){assert(frame.ball.arcadeShot===p&&frame.ball.state==='shot','recorded flame missing');assert(frame.arcadeImpact===impact,'recorded impact missing')}};film.draw(m,renderer);assert(m.ball.owner===liveOwner&&m.ball.state===liveState&&!m.ball.arcadeShot&&m.arcadeImpact===liveImpact,'replay corrupted live state');film.index=0;renderer.draw=()=>{throw Error('canvas failure')};try{film.draw(m,renderer)}catch(_){}assert(m.ball.owner===liveOwner&&!m.ball.arcadeShot&&m.arcadeImpact===liveImpact,'failed replay corrupted state');pass('replay records flames and impact, restoring live state even on render failure')}
{const m=make();shot(m);const r=new E.Renderer({getContext:()=>ctx});r.sprite=()=>{};const before=JSON.stringify(['x','y','z','vx','vy','vz'].map(k=>m.ball[k]));polygons=0;r.drawBall(640,360,10,m);assert(polygons>=3,'no flame polygons');r.draw(m);assert(before===JSON.stringify(['x','y','z','vx','vy','vz'].map(k=>m.ball[k])),'render changed physics');const keep=r.fantasyFlame;let fire=0;r.fantasyFlame=(...a)=>{fire++;return keep.apply(r,a)};V.settings.fantasy=false;polygons=0;r.drawBall(640,360,10,m);assert(polygons===1,'disabled flames drawn');V.settings.fantasy=true;V.settings.effects=0;polygons=0;r.drawBall(640,360,10,m);assert(polygons===1,'zero intensity still draws flame');V.settings.effects=.5;pass('flames render procedurally without world mutations and respect fantasy / intensity controls')}
{const m=make(),r=new E.Renderer({getContext:()=>ctx});r.sprite=()=>{};m.input.shotCharging=true;m.input.shotHeld=.85;strokes=0;r.draw(m);const aura=strokes;m.input.shotCharging=false;m.selected.burst=.38;strokes=0;r.draw(m);assert(aura>0&&strokes>0,'aura / dash missing');pass('full-charge aura and special-dribble speed lines render')}
