var window=globalThis;var Image=class{};function addEventListener(){};function removeEventListener(){};
load('arcade/engine/core.js');load('arcade/engine/controllers.js');load('arcade/engine/penalties.js');load('arcade/engine/arcade-features.js');
function assert(v,s){if(!v)throw Error(s)}
function test(s,fn){fn();print('PASS '+s)}
function game(){const input=new S9ArcadeEngine.InputManager();input.active=true;const m=new S9ArcadeEngine.Match(input);m.phase='PLAY';m.restarts.data=null;return m}
function key(input,type,key,repeat=false){input[type]({key,repeat,preventDefault(){}})}
function charged(m,seconds){key(m.input,'onDown','z');m.input.end(seconds);key(m.input,'onUp','z');m.update(.001);return m.lastShot.speed}
test('Z press holds ball; release fires once',()=>{const m=game();key(m.input,'onDown','z');m.update(.01);assert(m.ball.owner===m.selected,'fired on keydown');m.input.end(.04);key(m.input,'onUp','z');m.update(.001);assert(m.ball.state==='shot','release failed');const count=m.stats.teams[0].shots;m.input.end(.01);m.update(.01);assert(m.stats.teams[0].shots===count,'duplicate shot')});
test('tap, medium and full charge produce increasing real ball speeds',()=>{const low=charged(game(),.04),medium=charged(game(),.4),high=charged(game(),.85);assert(low<medium&&medium<high,'power not applied');assert(high/low>1.5,'difference too small')});
test('charge caps and ignores keyboard auto-repeat',()=>{const m=game();key(m.input,'onDown','z');m.input.end(.5);key(m.input,'onDown','z',true);assert(m.input.shotHeld===.5,'repeat reset');m.input.end(5);assert(m.input.shotCharge===1,'uncapped');key(m.input,'onUp','z');assert(m.input.shotPower===1,'bad release')});
test('blur and passing cancel charge without phantom shot',()=>{const m=game();key(m.input,'onDown','z');m.input.end(.4);m.input.onBlur();assert(!m.input.shotCharging&&!m.input.shotBuffer&&!m.input.down.size,'blur');key(m.input,'onDown','z',true);assert(!m.input.shotCharging,'repeat after blur rearmed shot');key(m.input,'onDown','z');m.pass(m.selected);key(m.input,'onUp','z');assert(!m.input.shotBuffer,'pass armed phantom shot')});
test('player physical shot-power attribute affects charged ball speed',()=>{const a=game(),b=game();a.selected.attributes={shooting:75,shotPower:30};b.selected.attributes={shooting:75,shotPower:95};assert(charged(a,.7)<charged(b,.7),'physical ignored')});
test('CPU shots retain original base speed independently of held Z',()=>{const m=game();key(m.input,'onDown','z');m.input.end(.85);const cpu=m.teams[1].players[9];m.control(cpu);m.shoot(cpu);assert(Math.abs(m.lastShot.speed-55)<.01,'CPU uses human charge');assert(m.input.shotCharging,'CPU consumes input')});
test('released shot is buffered for reception and airborne volley',()=>{const m=game(),p=m.selected;m.ball.owner=null;m.ball.x=p.x;m.ball.y=p.y;m.ball.z=3;m.ball.lock=0;key(m.input,'onDown','z');m.input.end(.4);key(m.input,'onUp','z');m.receive();assert(p.action==='volley'&&m.lastShot.charge>.4,'volley lost charge')});
test('penalty charge affects actual aimed trajectory',()=>{function shot(time){const m=game();m.startPenalties();key(m.input,'onDown','z');m.input.end(time);assert(!m.pen.flight,'early penalty');key(m.input,'onUp','z');m.penalties(.01);assert(m.pen.flight,'penalty not released');return Math.hypot(m.ball.vx,m.ball.vy)}assert(shot(.85)>shot(.04)*1.5,'penalty override discarded charge')});
test('behind hard foul issues a real yellow card and pauses match clock',()=>{const m=game(),p=m.selected,o=m.teams[1].players[9];p.x=50;p.y=31;o.x=52;o.y=31;o.face={x:1,y:0};m.control(o);p.face={x:1,y:0};p.tackle(true);m.tackles(.001);assert(m.cardScene?.card==='YELLOW'&&p.yellowCards===1,'no yellow');const clock=m.rules.remaining,age=m.restarts.data.age,x=p.x;m.update(.5);assert(m.rules.remaining===clock&&m.restarts.data.age===age&&p.x===x,'scene ran physics');m.update(2);assert(!m.cardScene&&m.phase==='RESTART','scene failed to resume')});
test('second yellow expels player from physics and restart selection',()=>{const m=game(),p=m.selected;S9ArcadeEngine.CardManager.issue(m,p);m.cardScene=null;S9ArcadeEngine.CardManager.issue(m,p);assert(p.sentOff&&m.players.length===21&&m.cardScene.secondYellow,'not expelled');m.cardScene=null;m.restarts.kickoff(0);assert(m.selected!==p&&!m.selected.sentOff,'expelled taker');const x=p.x;m.teams[0].ai.update(m,.2);assert(p.x===x,'expelled player moves');m.startPenalties();assert(!m.selected.sentOff,'expelled penalty shooter')});
test('red-card goalkeeper gets a temporary eligible replacement',()=>{const m=game(),g=m.teams[0].players[0];S9ArcadeEngine.CardManager.issue(m,g,true);m.cardScene=null;const replacement=m.teams[0].players.find(p=>!p.sentOff&&p.role==='GK');assert(replacement&&replacement!==g&&typeof replacement.update==='function','no keeper');m.startPenalties();m.pen.turn=1;m.setupPenalty();assert(m.selected===replacement,'penalty selects expelled keeper')});

test('replay restores live players, ownership, camera and clocks even if drawing fails',()=>{const m=game(),replay=new S9ArcadeEngine.ReplayManager(),camera={x:50,y:31,zoom:26};replay.record(m,.04,camera);replay.start();const players=m.players,owner=m.ball.owner,selected=m.selected,x=players[0].x,clock=m.elapsed;m.players[0].x=37;camera.x=80;const renderer={camera,animationTime:100,draw(){throw Error('QA draw failure')},text(){}};try{replay.draw(m,renderer,.02)}catch(e){assert(e.message==='QA draw failure','unexpected error')}assert(m.players===players&&m.selected===selected&&m.ball.owner===owner&&m.players[0].x===37&&camera.x===80&&m.elapsed===clock&&renderer.animationTime===100,'replay corrupted live game')});

test('X launches an aerial pass while C stays grounded',()=>{const a=game(),b=game();key(a.input,'onDown','x');a.update(.001);key(b.input,'onDown','c');b.update(.001);assert(a.ball.state==='aerial'&&a.ball.vz>0,'X did not loft');assert(b.ball.state==='pass'&&b.ball.vz<3,'C changed');assert(a.ball.passTarget&&!a.ball.passTarget.sentOff,'no eligible receiver');assert(a.lastPasser.action==='pass'&&a.lastPasser.actionTime>0,'missing kick animation');const count=a.stats.teams[0].passes;key(a.input,'onDown','x',true);a.update(.001);assert(a.stats.teams[0].passes===count,'repeat passed twice')});
test('X cancels shot charge and works from a restart',()=>{const m=game();key(m.input,'onDown','z');m.input.end(.5);key(m.input,'onDown','x');m.update(.001);key(m.input,'onUp','z');assert(!m.input.shotBuffer&&!m.input.shotCharging,'phantom shot after lob');const r=game();r.restarts.kickoff(0);r.restarts.data.delay=0;key(r.input,'onDown','x');r.update(.001);assert(r.phase==='PLAY'&&r.ball.state==='aerial','restart lob failed')});

test('Goalkeeper settles without oscillating, turning or restarting run poses',()=>{const m=game(),g=m.teams[1].players[0];m.ball.owner=m.selected;m.ball.y=31;g.x=97;g.y=31;for(let i=0;i<240;i++){g.tick(1/120);g.update(m,1/120);assert(g.x===97&&g.y===31&&g.action==='idle'&&g.face.x===-1,'idle goalkeeper jitters')}g.y=31.3;for(let i=0;i<240;i++){g.tick(1/120);g.update(m,1/120)}assert(Math.abs(g.y-31)<.23&&g.action==='idle','keeper never settles')});
test('Goalkeeper dive pose survives its full action instead of flipping back next tick',()=>{const m=game(),g=m.teams[1].players[0];g.x=97;g.y=31;m.ball.owner=null;m.ball.x=97;m.ball.y=31;m.ball.z=3;m.ball.lock=0;m.ball.vx=55;g.update(m,.01);assert(g.keeperState==='GK_DIVING','no dive');g.tick(.01);g.update(m,.01);assert(g.keeperState==='GK_DIVING'&&g.actionTime>0,'dive reset immediately')});

test('Camera shows approximately nineteen metres around the ball',()=>{const m=game(),c=new S9ArcadeEngine.CameraController();m.ball.x=92;m.ball.y=17;m.ball.z=8;m.ball.vx=70;c.update(m,.001);assert(c.x===92&&c.y===17&&c.zoom===36,'ball not centered or zoom changed');assert(640/c.zoom*1.05>18&&640/c.zoom*1.05<20&&360/(c.zoom*.65)*68/62<18,'view not widened appropriately')});
test('CPU leaves keeper with ball in hands alone and does not start tackles',()=>{const m=game(),g=m.teams[0].players[0],a=m.teams[1].players[9];g.x=3;g.y=31;m.control(g);a.x=5;a.y=31;a.aiWait=0;m.teams[1].ai.update(m,.01);assert(a.action!=='tackle'&&a.target.x>g.x+5,'CPU presses protected keeper')});
test('Nine penalty cells produce distinct physical horizontal and vertical targets',()=>{const targets=new Set();for(let i=0;i<9;i++){const m=game();m.startPenalties();m.pen.aim=i;m.pen.aimExplicit=true;charged(m,.5);assert(m.pen.flight,'no penalty flight');const b=m.ball,t=-Math.log(1-(100-b.x)*.12/b.vx)/.12,y=b.y+b.vy/.12*(1-Math.exp(-.12*t)),z=b.z+b.vz*t-12*t*t;const aim=S9ArcadeEngine.PenaltyTargets.cell(i);assert(Math.abs(y-aim.y)<.1&&Math.abs(z-aim.z)<.1,'wrong target trajectory');targets.add(y.toFixed(1)+':'+z.toFixed(1))}assert(targets.size===9,'repeated target cells')});
test('Penalty goalkeeper waits on the line, result persists until explicit continue',()=>{const m=game();m.startPenalties();const g=m.teams[1].players[0];for(let i=0;i<100;i++)m.penalties(.01);assert(g.y===31&&g.action==='idle'&&g.keeperState==='GK_POSITIONING','keeper moves before shot');m.pen.aim=8;m.pen.aimExplicit=true;charged(m,.85);for(let i=0;i<400&&m.pen.stage!=='result';i++)m.penalties(.01);assert(m.pen.stage==='result'&&m.pen.outcome.label&&m.pen.kicks[0]===1,'no readable result');const turn=m.pen.turn,owner=m.ball.owner;for(let i=0;i<300;i++)m.penalties(.01);assert(m.pen.turn===turn&&m.pen.stage==='result'&&m.ball.owner===owner,'jumped to next kicker');key(m.input,'onDown','z');m.penalties(.01);assert(m.pen.turn===1&&m.pen.stage==='ready','continue does not advance');const hg=m.teams[0].players[0];for(let i=0;i<100;i++)m.penalties(.01);assert(hg.y===31,'human keeper moves before CPU shot')});
test('In-match spot kick uses same grid and returns to play after result confirmation',()=>{const m=game();m.beginSpotKick(0);assert(m.pen.single&&m.pen.stage==='ready'&&m.rules.period==='REGULAR','single penalty mode');m.pen.aim=8;m.pen.aimExplicit=true;charged(m,.85);for(let i=0;i<400&&m.pen.stage!=='result';i++)m.penalties(.01);const goal=m.pen.outcome.goal;m.penalties(1);key(m.input,'onDown','z');m.penalties(.01);assert(!m.pen&&m.phase==='RESTART'&&m.rules.period==='REGULAR','single penalty failed to exit');assert(m.rules.score[0]===(goal?1:0),'single penalty wrong score')});

test('Simultaneous direction and dive use the newly selected penalty cell',()=>{const m=game();m.startPenalties();m.pen.turn=1;m.setupPenalty();m.penalties(1.81);assert(m.pen.flight,'CPU did not shoot');key(m.input,'onDown','arrowright');key(m.input,'onDown','x');m.penalties(.01);assert(m.pen.keeperCommitted&&m.pen.diveCell===5,'keeper used previous cell');assert(!m.input.shotCharging,'dive leaves charge active')});

load('arcade/engine/final-showdown.js');
test('Secret final intro pauses clock and gives every CPU player an original creature',()=>{const m=game();S9ArcadeFinal.configure(m,true);const elapsed=m.elapsed,clock=m.rules.remaining;m.update(1);assert(m.elapsed===elapsed&&m.rules.remaining===clock&&m.bonusFinal.intro===1,'intro advances play');m.update(1.3);assert(m.elapsed===elapsed,'intro not paused');m.update(.01);assert(m.elapsed>elapsed,'final never starts');assert(m.teams[1].players.every(p=>['trex','ostrich'].includes(p.creature))&&m.teams[1].name==='JURASSIC KICKERS','human boss roster')});
test('Secret final keeps physical shots and penalties at their ordinary speeds',()=>{const a=game(),b=game();S9ArcadeFinal.configure(b,true);b.bonusFinal.intro=3;a.shoot(a.selected,false,1);b.shoot(b.selected,false,1);assert(a.lastShot.speed===b.lastShot.speed&&!b.lastShot.special,'power-shot gimmick retained');const normal=game();S9ArcadeFinal.configure(normal,false);assert(!normal.bonusFinal&&!normal.teams[1].creatures,'friendly changed')});
test('Context keys: Z shoots only, X/C slide in defense and V changes action with possession',()=>{for(const k of ['x','c']){const m=game();m.control(m.teams[1].players[9]);key(m.input,'onDown',k);m.update(.001);assert(m.selected.action==='tackle'&&!m.selected.hard,'defensive slide absent')}const attack=game();key(attack.input,'onDown','v');attack.update(.001);assert(attack.selected.burst>0,'no attacking dribble');const defense=game();defense.control(defense.teams[1].players[9]);key(defense.input,'onDown','v');defense.update(.001);assert(defense.selected.hard&&defense.selected.action==='tackle','no hard tackle');const onlyShot=game();key(onlyShot.input,'onDown','z');onlyShot.input.end(.3);key(onlyShot.input,'onUp','z');onlyShot.update(.001);assert(onlyShot.ball.state==='shot'&&onlyShot.stats.teams[0].passes===0,'Z passed')});
test('Assisted lob follows directional input and excludes sent-off receivers',()=>{const m=game(),p=m.selected;p.x=50;p.y=31;p.face={x:1,y:0};m.teams[0].players.forEach(q=>{if(q!==p){q.x=30;q.y=31}});const up=m.teams[0].players[2],down=m.teams[0].players[3];up.x=50;up.y=12;down.x=50;down.y=50;key(m.input,'onDown','arrowup');m.pass(p,true);assert(m.ball.passTarget===up,'lob ignored arrows');up.sentOff=true;assert(m.chooseTarget(p,true)!==up,'expelled receiver selected')});
test('Assisted lob distance determines landing rather than fixed overshoot',()=>{for(const distance of [8,20,45]){const m=game(),p=m.selected,q=m.teams[0].players[2];p.x=20;p.y=31;q.x=20+distance;q.y=31;q.vx=q.vy=0;m.chooseTarget=()=>q;m.pass(p,true);const flight=(m.ball.vz+Math.sqrt(m.ball.vz*m.ball.vz+96))/24;let elapsed=0;while(elapsed<flight){const dt=Math.min(.002,flight-elapsed);m.ball.update(dt);elapsed+=dt}assert(Math.abs(m.ball.x-q.x)<.15&&Math.abs(m.ball.y-q.y)<.15,'lob missed static receiver at '+distance)}});
test('Kickoff opponents respect centre-circle distance and first pass goes to support',()=>{for(const team of [0,1]){const m=game();m.restarts.kickoff(team);const d=m.restarts.data;for(const p of m.teams[1-team].players)assert(Math.hypot(p.x-50,p.y-31)>=9.99,'opponent inside centre circle');m.pass(d.taker);assert(m.ball.passTarget===d.support,'unsafe kickoff target');assert(team?d.support.x>50:d.support.x<50,'support not behind ball')}});
test('Opening ground pass is received by own side before CPU can steal it',()=>{const m=game();m.restarts.kickoff(0);const support=m.restarts.data.support;key(m.input,'onDown','c');m.update(.001);m.input.end(.001);let received=false;for(let i=0;i<90;i++){m.update(1/120);m.input.end(1/120);assert(!m.ball.owner||m.ball.owner.team.id===0,'CPU stole opening pass');assert(m.rules.score[1]===0,'immediate CPU goal');if(m.ball.owner===support){received=true;break}}assert(received,'support failed to collect opening pass')});
test('CPU shot aim does not depend on player arrows and pressure worsens accuracy',()=>{function aimed(keys,pressure){const m=game(),p=m.teams[1].players[9];m.players.forEach(q=>{q.x=60;q.y=8});p.x=22;p.y=31;m.control(p);for(const k of keys)m.input.down.add(k);if(pressure){m.teams[0].players[2].x=24;m.teams[0].players[2].y=31}m.shoot(p);return m.lastShot.aim}const a=aimed([],false),b=aimed(['arrowup'],false),c=aimed([],true);assert(a===b,'CPU uses human direction');assert(Math.abs(c-31)>Math.abs(a-31),'pressure does not affect CPU shot')});
test('Keeper stays near goal line and predicts incoming shot rather than charging shooter',()=>{const m=game(),g=m.teams[0].players[0];g.x=3;g.y=31;m.ball.owner=null;m.ball.state='shot';m.ball.x=18;m.ball.y=31;m.ball.vx=-55;m.ball.vy=10;m.ball.flight=.2;m.ball.z=1;m.ball.lock=0;g.update(m,.02);assert(g.target.x===3&&g.x===3&&g.target.y>31,'keeper rushes toward incoming shot');assert(g.keeperState==='GK_POSITIONING','wrong shot response')});
test('CPU attack shots have physical saves and misses instead of automatic goals',()=>{let goals=0,saves=0,misses=0;for(let i=0;i<60;i++){const m=game(),p=m.teams[1].players[9],g=m.teams[0].players[0];m.players.forEach(q=>{q.x=60;q.y=8});g.x=3;g.y=31;p.x=22;p.y=31;m.control(p);m.stats.teams[1].shots=i;if(i%2){m.teams[0].players[2].x=24;m.teams[0].players[2].y=31}m.shoot(p);for(let j=0;j<240&&m.phase==='PLAY';j++){g.update(m,1/240);m.ball.update(1/240);m.boundaries();if(m.stats.teams[0].saves>0)break}if(m.rules.score[1])goals++;else if(m.stats.teams[0].saves)saves++;else misses++}assert(goals<30&&saves>10&&misses>3,'CPU conversion still excessive: '+goals+' goals, '+saves+' saves, '+misses+' misses');print('CPU SHOT BENCHMARK: '+goals+' goals / '+saves+' saves / '+misses+' misses from 60 central long shots')});
test('Close-range CPU chances can still produce real goals',()=>{let goals=0;for(let i=0;i<40;i++){const m=game(),p=m.teams[1].players[9],g=m.teams[0].players[0];m.players.forEach(q=>{q.x=60;q.y=8});g.x=3;g.y=31;p.x=9;p.y=31;m.control(p);m.stats.teams[1].shots=i;m.shoot(p);for(let j=0;j<240&&m.phase==='PLAY';j++){g.update(m,1/240);m.ball.update(1/240);m.boundaries();if(m.stats.teams[0].saves>0)break}if(m.rules.score[1])goals++}assert(goals>0&&goals<40,'keeper became invincible or CPU still infallible: '+goals);print('CPU CLOSE-RANGE BENCHMARK: '+goals+' goals from 40 chances')});
test('CPU chooses a pass instead of firing from a poor wide angle',()=>{const m=game(),p=m.teams[1].players[9];p.x=18;p.y=54;m.control(p);p.aiWait=0;m.teams[1].ai.update(m,.001);assert(m.stats.teams[1].shots===0&&m.stats.teams[1].passes===1,'CPU shoots every wide attack')});
test('Loose-ball recovery assigns two AI teammates even if controlled defender is closest',()=>{const m=game(),p=m.teams[0].players[2];m.selected=p;p.x=12;p.y=31;m.ball.owner=null;m.ball.x=12;m.ball.y=31;m.ball.vx=18;m.ball.vy=12;m.ball.lastTeam=0;m.ball.state='rebound';m.teams[0].ai.update(m,.02);const target={x:m.ball.x+m.ball.vx*.12,y:m.ball.y+m.ball.vy*.12};assert(m.teams[0].players.filter(q=>q!==p&&q.role!=='GK'&&Math.hypot(q.target.x-target.x,q.target.y-target.y)<.01).length===2,'manual defender consumed automatic recovery slot');const cover=m.teams[0].players.filter(q=>q!==p&&['CB','LB','RB','CM'].includes(q.role)&&q.target.x<15);assert(cover.length>=3,'defenders abandoning box')});
test('Keeper tips a rising shot over the bar for a corner',()=>{const m=game(),g=m.teams[0].players[0];g.x=3;g.y=31;m.ball.owner=null;m.ball.x=3;m.ball.y=31;m.ball.vx=-60;m.ball.z=3;m.ball.lock=0;m.ball.state='shot';m.ball.flight=.3;m.ball.lastTeam=1;m.phase='PLAY';m.restarts.data=null;g.update(m,.001);assert(m.ball.vx<0&&m.ball.vz>10,'not tipped over');for(let i=0;i<200&&m.phase==='PLAY';i++){m.ball.update(1/120);m.boundaries()}assert(m.restarts.data?.type==='CORNER'&&m.rules.score[1]===0,'tip did not give a corner')});
test('Keeper parries away from central striker and toward safer flank',()=>{const m=game(),g=m.teams[0].players[0];g.x=3;g.y=31;m.ball.owner=null;m.ball.x=3;m.ball.y=31;m.ball.vx=-60;m.ball.z=1;m.ball.lock=0;m.ball.state='shot';m.ball.flight=.3;const enemy=m.teams[1].players[9];enemy.x=15;enemy.y=17;g.update(m,.001);assert(m.ball.state==='rebound'&&m.ball.vx>0&&Math.abs(m.ball.vy)>=15,'parry returned centrally');assert(m.ball.vy>0,'parry chose occupied flank')});
test('Nearest eligible player wins loose ball regardless of roster ordering',()=>{const m=game();m.players.forEach(p=>{p.x=50;p.y=8});m.ball.owner=null;m.ball.x=20;m.ball.y=31;m.ball.z=0;m.ball.lock=0;const defender=m.teams[0].players[2],attacker=m.teams[1].players[9];defender.x=22;defender.y=31;attacker.x=20.4;attacker.y=31;m.receive();assert(m.ball.owner===attacker,'earlier roster entry stole ball');m.ball.owner=null;defender.x=20.1;m.receive();assert(m.ball.owner===defender,'closest defender cannot claim rebound')});
test('Collecting own rebound preserves CPU shooting cooldown',()=>{const m=game(),p=m.teams[1].players[9];p.aiWait=1.3;m.control(p);assert(p.aiWait===1.3,'reception reset shot cooldown')});
test('Goalkeeper can smother attacker feet instead of letting CPU walk through goal',()=>{const m=game(),g=m.teams[0].players[0],p=m.teams[1].players[9];g.x=3;g.y=31;p.x=4.5;p.y=31;p.face={x:-1,y:0};m.control(p);m.ball.update(0);g.update(m,.001);assert(m.ball.owner===g&&m.ball.controlMode==='HANDS'&&m.stats.teams[0].saves===1,'keeper lets striker dribble through')});
test('AI defender presses ball carrier even when the manual defender is closest',()=>{const m=game(),manual=m.teams[0].players[2],helper=m.teams[0].players[3],enemy=m.teams[1].players[9];m.teams[0].players.forEach(p=>{p.x=45;p.y=8});manual.x=19;manual.y=31;helper.x=24;helper.y=31;enemy.x=20;enemy.y=31;m.selected=manual;m.control(enemy);m.ball.update(0);m.teams[0].ai.update(m,.01);assert(helper.target.x===enemy.x&&helper.target.y===enemy.y&&helper.vx<0,'selected defender disables automatic pressure')});
test('CPU reception allows a brief read window and slower dribble than player movement',()=>{const m=game(),p=m.teams[1].players[9];p.x=50;p.y=31;m.control(p);const x=p.x;m.teams[1].ai.update(m,.01);assert(p.x===x&&p.aiWait>=1,'no CPU reception delay');p.tick(.3);m.teams[1].ai.update(m,.1);assert(Math.abs(p.vx)<12&&p.x<x,'CPU pace unchanged')});
