var window=globalThis,location={search:'',protocol:'https:',origin:'https://example.com'},performance={now:()=>123};
var S9ArcadeEngine={Match:class{},Renderer:class{}},document={getElementById:()=>null};
var URL=class{constructor(v){var m=/^(https?):\/\/([^/]+)(.*)$/.exec(v);if(!m)throw Error('URL');this.protocol=m[1]+':';this.username=m[2].includes('@')?'user':'';this.password='';this.href=v}};
load('arcade/ui/online.js');load('arcade/engine/supporter-flags.js');
function assert(v,s){if(!v)throw Error(s)}function pass(s){print('PASS '+s)}
const O=S9ArcadeOnline;
assert(O.playersFor({players:[{team:1}]},'coop').every(p=>p.team===1),'coop');assert(O.playersFor({players:[{team:1}]},'versus')[1].team===0,'versus');assert(O.playersFor({players:[{team:0},{team:1}]},'coop')[1].team===1,'bracket opposing players');pass('online assigns two players for cooperative and opposing-team modes');
const held=new Set(),input={active:true,press:k=>held.add(k),release:k=>held.delete(k),onBlur:()=>held.clear()};O.applyInput(input,['z','arrowup','injected']);assert(held.size===2&&!held.has('injected'),'whitelist');O.applyInput(input,['c']);assert(held.size===1&&held.has('c'),'release');input.active=false;O.applyInput(input,['z']);assert(!held.size,'pause');input.active=true;
const host=new O.Session({role:'host'},'https://example.com');host.generation=2;host.game={inputs:[null,input],control:a=>host.action=a};host.receive({type:'input',match:2,sequence:1,keys:['z']});host.receive({type:'input',match:2,sequence:0,keys:['c']});assert(held.has('z'),'stale sequence');host.receive({type:'input',match:1,sequence:2,keys:['c']});assert(held.has('z'),'old match');host.receive({type:'inputreset',match:2});assert(!held.size,'blur');host.receive({type:'control',match:2,action:'pause'});assert(host.action==='pause','pause');host.receive({type:'control',match:2,action:'delete'});assert(host.action==='pause','control whitelist');pass('remote input rejects stale matches, reordered packets and unknown commands; pause and blur release held keys');
var saved=0;window.S9ArcadeEvolution={progress:{xp:0,medals:{}},save:()=>saved++};const guest=new O.Session({role:'guest'},'https://example.com');guest.generation=2;const reward={type:'result',match:2,reward:{xp:50,key:'volley',medal:3}};guest.receive(reward);guest.receive(reward);assert(saved===1&&S9ArcadeEvolution.progress.xp===50&&S9ArcadeEvolution.progress.medals.volley===3,'duplicate reward');pass('guest receives completion rewards once per match');
var rejected=false;try{O.serverURL('http://example.com')}catch(_){rejected=true}assert(rejected,'mixed content');pass('HTTPS game rejects insecure signaling URLs');
var rects=[],ctx=new Proxy({fillRect(...a){rects.push([this.fillStyle,...a])}},{get:(t,k)=>k in t?t[k]:()=>{},set:(t,k,v)=>(t[k]=v,true)}),r=new S9ArcadeEngine.Renderer();r.ctx=ctx;const team={kit:{shirtPrimary:'#f00',shirtSecondary:'#fff',pattern:'vertical_stripes'}};r.supporterFlag(0,0,22,13,team,0,2);const first=JSON.stringify(rects);assert(rects.some(a=>a[0]==='#f00')&&rects.some(a=>a[0]==='#fff'),'kit colors');rects=[];r.supporterFlag(0,0,22,13,team,1,2);assert(first!==JSON.stringify(rects),'animated cloth');r.currentMatch={teams:[team,{kit:{}}]};r.stadiumCelebration={team:1};assert(r.supporterTeam(1,true)===r.currentMatch.teams[1],'scoring flags');pass('supporter flags animate using club colors and celebrate the scoring team');
