var window=globalThis;function addEventListener(){}function removeEventListener(){}
var Image=class{constructor(){this.complete=true;this.naturalWidth=this.width=1024;this.height=3200}};
var calls=[],ctx=new Proxy({drawImage(...args){calls.push(args)}},{get:(t,k)=>k in t?t[k]:()=>{},set:(t,k,v)=>(t[k]=v,true)}),document={createElement:()=>({getContext:()=>ctx})};
load('arcade/assets/animations.js');load('arcade/engine/core.js');load('arcade/engine/controllers.js');load('arcade/engine/penalties.js');load('arcade/engine/art.js');load('arcade/engine/visual.js');
const plainUpdate=S9ArcadeEngine.Goalkeeper.prototype.update;
load('arcade/engine/spectacular-saves.js');
const E=S9ArcadeEngine,A=S9ArcadeSaves;
function assert(v,s){if(!v)throw Error(s)}function pass(s){print('PASS '+s)}
function shot(z,speed,side=1){const m=new E.Match(new E.InputManager());m.phase='PLAY';m.restarts.data=null;m.elapsed=2;const g=m.teams[0].players[0];g.x=3;g.y=31;Object.assign(m.ball,{owner:null,x:4,y:31+side,z,vx:-speed,vy:0,vz:0,flight:.3,state:'shot',lastTeam:1,lock:0});return {m,g}}
for(const [z,speed,kind] of [[1,70,'stretch'],[2.5,70,'tip'],[4,40,'punch']])for(const side of [-1,1]){const {m,g}=shot(z,speed,side);g.update(m,0);assert(m.stats.teams[0].saves===1,'save not real');assert(g.saveAnimation?.kind===kind&&g.saveAnimation.side===(side<0?'left':'right'),'wrong animation');const r=new E.Renderer({getContext:()=>ctx});r.sprite(g,m,{scale:2});assert(r.poseStates.get(g).action==='save_'+kind+'_'+(side<0?'left':'right'),'wrong sprite row');const first=S9ArcadeFrames[r.poseStates.get(g).action][0],draw=calls[calls.length-1];assert(draw[1]===first%8*128&&draw[2]===Math.floor(first/8)*128,'atlas coordinates');g.keeperState='GK_POSITIONING';m.elapsed=2.4;r.sprite(g,m,{scale:2});assert(r.poseStates.get(g).action.startsWith('save_'),'animation cut short');m.elapsed=2.81;assert(!A.pose(g,m),'stale save');}
pass('real low, fingertip and punch saves select six dedicated sprite sequences and complete after keeper simulation resumes');
for(const [z,speed] of [[1,70],[2.5,70],[4,40]]){const a=shot(z,speed),b=shot(z,speed);plainUpdate.call(a.g,a.m,0);b.g.update(b.m,0);const physical=({m,g})=>JSON.stringify({ball:['x','y','z','vx','vy','vz','lock','state'].map(k=>m.ball[k]),g:[g.x,g.y,g.actionTime,g.keeperState],score:m.rules.score,stats:m.stats});assert(physical(a)===physical(b),'save changed physics')}
pass('spectacular-save artwork does not change reach, rebound velocity, score or goalkeeper recovery');
const {m,g}=shot(2.5,70);g.update(m,0);const original=g.saveAnimation,replay=new E.ReplayManager();replay.record(m,.04);g.saveAnimation=null;replay.start();replay.draw(m,{camera:{},draw(){assert(g.saveAnimation===original,'replay metadata missing')},text(){}},.01);assert(g.saveAnimation===null,'live metadata changed');g.saveAnimation=original;g.reset();assert(g.saveAnimation===null,'reset metadata');pass('save pose metadata survives replay snapshots and is cleared on player reset');
const penalty=shot(1,70);penalty.g.keeperState='GK_DIVING';penalty.m.pen={diveCell:0};assert(A.pose(penalty.g,penalty.m).startsWith('save_tip'),'high penalty dive lacks sprite');pass('penalty and free-kick dives use spectacular sprite families even before contact');
