var window=globalThis;function assert(v,s){if(!v)throw Error(s)}function pass(s){print('PASS '+s)}
var tracks=[],listeners=new Map(),whistles=0,saves=0;function addEventListener(k,f){listeners.set(k,f)}function removeEventListener(k,f){if(listeners.get(k)===f)listeners.delete(k)}
var Audio=class{constructor(src){this.src=src;this.paused=true;this.currentTime=0;this.events={};this.plays=0;tracks.push(this)}addEventListener(k,f){this.events[k]=f}play(){this.paused=false;this.plays++;return Promise.resolve()}pause(){this.paused=true}};
var S9SFX={saveSound:()=>saves++,fullTimeWhistle:()=>whistles++};load('arcade/engine/stadium.js');
const stadium=S9ArcadeStadium.create(),m={rules:{score:[0,0]},stats:{teams:[{saves:0},{saves:0}]},phase:'PLAY'};stadium.start();stadium.start();assert(tracks.length===2&&tracks[0].loop&&tracks[0].plays===1,'duplicate ambience');stadium.observe(m);assert(tracks[1].plays===0,'early roar');m.rules.score[0]++;stadium.observe(m);stadium.observe(m);assert(tracks[1].plays===1&&tracks[1].currentTime===5.1&&stadium.reaction.team===0,'goal not synced or repeated');m.phase='FINISHED';m.rules.score[1]++;stadium.observe(m);assert(tracks[1].plays===2&&stadium.reaction.team===1&&whistles===1,'winning goal missed');stadium.observe(m);assert(whistles===1,'repeated whistle');stadium.tick(1.5);assert(stadium.reaction&&stadium.reaction.age>1,'crowd faded too soon');stadium.tick(2);assert(!stadium.reaction,'celebration never ends');m.phase='PENALTIES';m.pen={goals:[1,0]};stadium.observe(m);stadium.observe(m);assert(tracks[1].plays===3,'penalty missed or duplicated');m.stats.teams[0].saves=1;stadium.observe(m);assert(saves===1,'save sound missing');stadium.stop();assert(tracks.every(t=>t.paused)&&!listeners.size,'sound or input listeners leaked');tracks[1].events.loadedmetadata();assert(tracks[1].paused,'late metadata restarted audio');pass('stadium ambience and goal roar play once, include winning goals and penalties, and stop cleanly');
load('arcade/engine/core.js');S9ArcadeEngine.Renderer=class{constructor(){}draw(){} };S9ArcadeEngine.CameraController=class{update(){}};S9ArcadeEngine.ReplayManager=class{record(){}start(){}};
var frames=[],performance={now:()=>0};function requestAnimationFrame(fn){frames.push(fn)};var button={},canvas={setAttribute(){}};var panel={style:{},dataset:{},setAttribute(){},querySelector:s=>s==='button'?button:canvas,remove(){this.removed=true}};var document={createElement:()=>panel,body:{append(){}}};var musicStops=0,musicStarts=0;window.S9ArcadeUI={kit:()=>({shirtPrimary:'#3456ed'})};window.S9ArcadeMusic={start:()=>musicStarts++,stop:()=>musicStops++};window.S9ArcadeMenuOpen=true;
var keyHandlers=[],baseAdd=addEventListener,baseRemove=removeEventListener;addEventListener=(k,f)=>{if(k==='keydown')keyHandlers.push(f);baseAdd(k,f)};removeEventListener=(k,f)=>{keyHandlers=keyHandlers.filter(g=>g!==f);baseRemove(k,f)};const key=k=>[...keyHandlers].forEach(f=>f({key:k,preventDefault(){},stopImmediatePropagation(){}}));
load('arcade/bridge.js');const source={id:'qa',name:'QA',season:'',players:Array.from({length:18},(_,i)=>({id:'p'+i,pos:i<2?'GK':i<8?'DF':i<14?'MF':'ST',overall:75}))};launchArcadeMatch({home:source,away:{...source,id:'qb'}});assert(!tracks[2].paused&&musicStops===1,'bridge did not start ambience or stop music');const match=S9ArcadeActive.match;match.rules.period='GOLDEN';match.rules.goal(0);frames.shift()(20);assert(tracks[3].plays===1&&S9ArcadeActive.renderer.stadiumCelebration,'golden winning goal did not reach sound/visuals');for(let t=120;t<=1400;t+=100)frames.shift()(t);key('z');assert(panel.removed&&tracks[2].paused&&tracks[3].paused&&!S9ArcadeActive&&musicStarts===1,'bridge finish leaked stadium sound');pass('actual match bridge starts stadium sound, celebrates golden-goal win, stops sound and restores menu music on exit');
