var window=globalThis;load('arcade/ui/tournament.js');
const TM=S9ArcadeTournament,ids=Array.from({length:20},(_,i)=>'t'+i);
function assert(x,s){if(!x)throw Error(s)}function test(s,f){f();print('PASS '+s)}
const simulate=(h,a)=>({hg:1,ag:0,winner:h});
test('Arcade has one selectable entry per club or nation',()=>{const pool=TM.pool([{id:'a',name:'Italia',strength:70},{id:'b',name:'Italia',strength:90},{id:'c',name:'Francia',strength:80},{id:'d',name:'Milan',strength:99}],['a','b','c']);assert(pool.length===2&&pool.some(t=>t.id==='b')&&!pool.some(t=>t.id==='d'),'duplicate or wrong category')});
test('Exactly three group games, draws, real table and top-two qualification',()=>{const c=TM.create('club',ids,'t0');const opponents=new Set();for(let i=0;i<3;i++){const f=TM.fixture(c);assert(f.allowDraw&&c.stage==='groups'&&c.round===i,'wrong group phase');opponents.add(f.h==='t0'?f.a:f.h);TM.advance(c,{homeGoals:2,awayGoals:2,winner:null},()=>({hg:0,ag:0,winner:null}))}assert(opponents.size===3,'opponent repeated');assert(c.results.length===24,'not all group fixtures');assert(TM.standings(c,0)[0].played===3&&TM.standings(c,0)[0].points===3,'draw points');assert(c.stage==='knockout'&&c.bracket.length===8&&!TM.fixture(c).allowDraw,'no quarterfinal');});
test('Champions and World Cup finish after three groups plus three knockout games',()=>{for(const category of ['club','national']){const c=TM.create(category,ids,'t0','4-3-3');for(let i=0;i<3;i++){const f=TM.fixture(c);TM.advance(c,{homeGoals:f.h==='t0'?5:0,awayGoals:f.a==='t0'?5:0,winner:'t0'},simulate)}let rounds=0;while(c.stage==='knockout'){const f=TM.fixture(c);TM.advance(c,{homeGoals:f.h==='t0'?2:0,awayGoals:f.a==='t0'?2:0,winner:'t0'},simulate);rounds++}assert(c.stage==='won'&&rounds===3&&c.formation==='4-3-3','tournament flow');assert(new Set(c.groups.flat()).size===16,'duplicate participants')}});
test('Losing group side is eliminated only after all three matches',()=>{const c=TM.create('national',ids,'t0');for(let i=0;i<3;i++){const f=TM.fixture(c);TM.advance(c,{homeGoals:f.h==='t0'?0:5,awayGoals:f.a==='t0'?0:5},simulate);if(i<2)assert(c.stage==='groups','early elimination')}assert(c.stage==='out'&&TM.fixture(c)===null,'eliminated side proceeds')});
test('Knockout loss ends tournament, persisted state resumes the same fixture',()=>{const c=TM.create('club',ids,'t0');for(let i=0;i<3;i++){const f=TM.fixture(c);TM.advance(c,{homeGoals:f.h==='t0'?5:0,awayGoals:f.a==='t0'?5:0,winner:'t0'},simulate)}const restored=JSON.parse(JSON.stringify(c));assert(JSON.stringify(TM.fixture(restored))===JSON.stringify(TM.fixture(c)),'resume changed fixture');const f=TM.fixture(c);TM.advance(c,{homeGoals:0,awayGoals:0,winner:f.h==='t0'?f.a:f.h},simulate);assert(c.stage==='out','loss progresses')});
test('Only the final fixture is special and champion bonus survives save/load',()=>{const c=TM.create('national',ids,'t0');for(let i=0;i<6;i++){const f=TM.fixture(c);assert(!!f.specialFinal===(i===5),'special outside final');TM.advance(c,{homeGoals:f.h==='t0'?2:0,awayGoals:f.a==='t0'?2:0,winner:'t0'},simulate)}assert(c.stage==='won'&&c.bonus.champion===10000&&c.bonus.finalShowdown===5000&&c.bonus.total===24000,'wrong champion bonus');const restored=JSON.parse(JSON.stringify(c));assert(restored.bonus.total===24000&&TM.fixture(restored)===null,'lost reward or repeat final')});

test('Secret final substitutes a valid creature opponent and loss ends the tournament',()=>{const c=TM.create('club',ids,'t0');for(let i=0;i<5;i++){const f=TM.fixture(c);TM.advance(c,{homeGoals:f.h==='t0'?2:0,awayGoals:f.a==='t0'?2:0,winner:'t0'},simulate)}const f=TM.fixture(c);assert(f.bonusFinal&&f.h==='t0'&&f.a==='arcade_jurassic','wrong Easter egg fixture');TM.advance(c,{homeGoals:0,awayGoals:2,winner:f.a},simulate);assert(c.stage==='out'&&!c.bonus&&c.bracket[0]==='arcade_jurassic','losing final awards trophy')});
