var window=globalThis;var Image=class{constructor(){this.complete=true;this.naturalWidth=1024;this.width=1024;this.height=2304}};function addEventListener(){};
var calls=[],ctx=new Proxy({drawImage:function(){calls.push([...arguments])}},{get:(t,k)=>k in t?t[k]:()=>{},set:(t,k,v)=>(t[k]=v,true)});var document={createElement:()=>({width:0,height:0,getContext:()=>ctx})};
load('arcade/assets/animations.js');load('arcade/engine/core.js');load('arcade/engine/controllers.js');load('arcade/engine/penalties.js');load('arcade/engine/art.js');load('arcade/engine/visual.js');load('arcade/engine/presentation-upgrade.js');
function ok(x,label){if(!x)throw Error(label);print('PASS '+label)}
const renderer=new S9ArcadeEngine.Renderer({getContext:()=>ctx}),p={role:'ST',action:'run',team:{},face:{x:1,y:0}},m={elapsed:40,ball:{}};
renderer.sprite(p,m,{scale:1.55});p.action='shoot';p.actionTime=.22;m.elapsed=40.08;renderer.sprite(p,m,{scale:1.55});const f=S9ArcadeFrames.shoot[0],call=calls[calls.length-1];ok(call[1]===f%8*128&&call[2]===Math.floor(f/8)*128,'RUN → SHOOT begins at frame 0 independently of match clock');
m.elapsed=40.29;renderer.sprite(p,m,{scale:1.55});const end=calls[calls.length-1],last=S9ArcadeFrames.shoot[7];ok(end[1]===last%8*128&&end[2]===Math.floor(last/8)*128,'shot reaches final exposure during action');
const saved=JSON.stringify(S9ArcadeFrames);renderer.sprite({role:'REF',action:'whistle',team:{}},m,{scale:1.55});ok(JSON.stringify(S9ArcadeFrames)===saved,'sprite drawing restores shared manifest');
const gr=new S9ArcadeEngine.Renderer({getContext:()=>ctx}),gp={role:'GK',action:'keeper',keeperState:'GK_CATCHING',actionTime:.4,team:{},face:{x:1,y:0}},gm={elapsed:100,ball:{owner:gp,controlMode:'HANDS'}};
function lastFrameIs(index){const call=calls[calls.length-1];return call[1]===index%8*128&&call[2]===Math.floor(index/8)*128}
gr.sprite(gp,gm,{scale:1.55});ok(lastFrameIs(S9ArcadeFrames.catch[0]),'human goalkeeper hand possession starts with catch pose');gm.elapsed=100.3;gr.sprite(gp,gm,{scale:1.55});ok(lastFrameIs(S9ArcadeFrames.hold[0]),'human goalkeeper transitions from catch to hold');gp.action='pass';gm.ball.owner=null;gm.elapsed=100.31;gr.sprite(gp,gm,{scale:1.55});ok(lastFrameIs(S9ArcadeFrames.throw[0]),'distribution overrides stale catch state');gp.action='shoot';gm.elapsed=100.4;gr.sprite(gp,gm,{scale:1.55});ok(lastFrameIs(S9ArcadeFrames.kick_long[0]),'long goalkeeper kick uses the full kick sequence');
const match=new S9ArcadeEngine.Match(new S9ArcadeEngine.InputManager());renderer.sprite=()=>{};renderer.draw(match);match.startPenalties();renderer.draw(match);ok(match.phase==='PENALTIES'&&match.pen.turn===0,'field and penalty presentation leave match state intact');

const before=JSON.stringify({phase:match.phase,score:match.rules.score,pen:match.pen});match.cardScene={card:'YELLOW',age:1.5,player:match.players[2],number:3,name:'QA Player',team:'QA Team'};renderer.draw(match);ok(JSON.stringify({phase:match.phase,score:match.rules.score,pen:match.pen})===before,'card cinematic renderer leaves match rules untouched');

const rm=new S9ArcadeEngine.Match(new S9ArcadeEngine.InputManager()),rr=new S9ArcadeEngine.Renderer({getContext:()=>ctx});const ref=rr.updateReferee(rm),rx=ref.x;rm.ball.x=80;rm.ball.y=45;rm.elapsed=.05;rr.updateReferee(rm);ok(ref.x>rx&&ref.x<rx+1,'referee moves continuously in world coordinates without teleporting');ok(ref.x!==rm.ball.x-8&&ref.y!==rm.ball.y+8,'referee is not fixed to a ball-relative screen corner');

const bar=new S9ArcadeEngine.Renderer({getContext:()=>ctx});bar.project=()=>{throw Error('power HUD should not follow offscreen player')};bar.chargeMeter({phase:'PLAY',selected:{},input:{shotCharging:true,shotCharge:.5},elapsed:0});ok(true,'power meter stays in HUD independently of player position and close camera');
const radarMatch=new S9ArcadeEngine.Match(new S9ArcadeEngine.InputManager());renderer.project=()=>{throw Error('radar must include offscreen players')};const radarState=JSON.stringify(radarMatch.players.map(p=>[p.x,p.y]));renderer.radar(radarMatch);ok(radarState===JSON.stringify(radarMatch.players.map(p=>[p.x,p.y])),'radar draws all world positions without modifying players or using camera projection');
const visualCrowd=new S9ArcadeEngine.Renderer({getContext:()=>ctx});visualCrowd.stadiumCelebration={team:0,age:.5};const crowdState=JSON.stringify(radarMatch.players.map(p=>[p.x,p.y]));visualCrowd.crowdCutaway(radarMatch);ok(JSON.stringify(radarMatch.players.map(p=>[p.x,p.y]))===crowdState,'goal crowd cutaway draws independently of pitch camera and leaves players unchanged');
const radarRects=[],radarTexts=[],topRadar=new S9ArcadeEngine.Renderer({getContext:()=>new Proxy({fillRect:(...a)=>radarRects.push(a)},{get:(t,k)=>k in t?t[k]:()=>{},set:(t,k,v)=>(t[k]=v,true)})});topRadar.text=(...a)=>radarTexts.push(a);topRadar.hud(radarMatch);ok(radarRects.some(a=>a[0]===525&&a[1]===18&&a[2]===230&&a[3]===90)&&radarTexts.some(a=>a[0]==='2:00'&&a[2]===139)&&radarTexts.filter(a=>a[0]==='0'&&a[2]===78&&a[3]===51).length===2,'arcade reference HUD puts full radar above timer and uses separate large scores');{const blits=[],art=new S9ArcadeEngine.Renderer({getContext:()=>new Proxy({drawImage:(...a)=>blits.push(a),fillRect:(...a)=>blits.push(['rect',...a])},{get:(t,k)=>k in t?t[k]:()=>{},set:(t,k,v)=>(t[k]=v,true)})});art.text=()=>{};art.hud(radarMatch);const bezel=blits.filter(a=>a[0]!=='rect'&&/drawn-panel/.test(a[0].src||''));ok(bezel.length>=9*6&&!blits.some(a=>a[0]==='rect'&&a[3]>=100&&a[4]>=30&&a[3]<1280&&a[1]!==525),'scoreboards, radar, timer, message and controls bar are drawn-panel bitmaps, no flat HUD boxes')}topRadar.replayMode=true;radarRects.length=0;topRadar.hud(radarMatch);ok(!radarRects.some(a=>a[0]===525&&a[1]===18),'radar hides during replay so caption stays readable');
