(function(){
const E=window.S9ArcadeEngine;
const attributes=p=>{const s=p.stats||{},v=k=>Math.max(1,Math.min(100,s[k]??p.overall??65));return {speed:v('speed'),control:v('technique'),passing:v('passing'),shooting:v('shooting'),defending:v('defending'),goalkeeping:v('positioning'),acceleration:v('speed'),shotPower:v('physical'),passAccuracy:v('passing'),tackleStrength:v('defending')}};
// Squad skin tones from the team's origin, stable per player (hash of id): no all-identical faces.
const SKIN_GROUPS=[[/cameroon|nigeria|ghana|ivory|senegal|southafrica|mali|congo|zambia|sundowns|jamaica/,[0,.05,.15,.4,.4]],[/morocco|algeria|tunisia|egypt|alahly|zamalek|raja|saudi|iran|iraq|qatar|uae|alhilal|turkey|fener|galatasaray/,[.15,.55,.25,.05,0]],[/japan|korea|china|kashima|urawa|jeonbuk|shanghai|uzbek/,[.3,.6,.1,0,0]],[/brazil|colombia|uruguay|argentina|mexico|peru|ecuador|venezuela|bolivia|paraguay|chile|costarica|honduras|panama|usa|flamengo|santos|saopaulo|corinthians|palmeiras|boca|river|penarol|nacional|america|chivas|dcunited|galaxy/,[.35,.3,.2,.1,.05]],[/france|england|netherlands|belgium|portugal|arsenal|chelsea|psg|marseille|ajax|psv|manutd|liverpool|canada|sporting|benfica/,[.5,.15,.1,.15,.1]]];
function skinFor(team,player){const id=String(team?.id||'').toLowerCase()+' '+String(team?.name||'').toLowerCase(),w=(SKIN_GROUPS.find(([re])=>re.test(id))||[0,[.75,.15,.06,.03,.01]])[1];let h=2166136261;for(const ch of String(player?.id||player?.name||'')){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)>>>0}let r=(h%1000)/1000;for(let i=0;i<w.length;i++){if(r<w[i])return i;r-=w[i]}return 0}
function setupTeam(t,source,state){t.name=source.name+(state?.cleanNames?'':' '+source.season);t.source=source;t.kit=window.S9ArcadeUI?.kit(source);let roster=state?.players||source.players;let chosen=state?.lineup?.map(id=>roster.find(p=>p.id===id)).filter(Boolean)||[];if(chosen.length!==11){const used=new Set();chosen=['GK','DF','DF','DF','DF','MF','MF','MF','MF','ST','ST'].map(role=>{const p=roster.find(p=>!used.has(p.id)&&(p.pos===role||role==='MF'&&p.pos==='AM'))||roster.find(p=>!used.has(p.id));used.add(p.id);return p})}chosen.sort((a,b)=>(a.pos==='GK'?-1:0)-(b.pos==='GK'?-1:0));t.players.forEach((p,i)=>{p.source=chosen[i];p.skin=skinFor(source,chosen[i]);p.attributes=attributes(chosen[i]);p.morale=chosen[i].morale??65;t.mentality=state?.mentality||'Equilibrato'});
 const lines=(state?.formation||'4-4-2').split('-').map(Number);t.formation=state?.formation||'4-4-2';
 if(lines.every(n=>n>0)&&lines.reduce((a,b)=>a+b,0)===10){let i=1;lines.forEach((count,row)=>{for(let j=0;j<count;j++){const p=t.players[i++],x=20+row*(40/Math.max(1,lines.length-1));p.role=row===0?(j===0?'LB':j===count-1?'RB':'CB'):row===lines.length-1?'ST':j===0?'LM':j===count-1?'RM':'CM';p.home={x:t.id?100-x:x,y:8+(count===1?23:j*46/(count-1))}}})}
}
// Device per human: 'all' (arrows keyboard + every pad, single player), 'kb' (arrows), 'kb2' (WASD + IJKL), 'padN'.
function deviceOptions(device,all){if(device==='remote')return {keys:null,pads:null};const shared=all.some(d=>d.device==='kb2');if(device==='kb2')return {keys:'wasd',pads:null};if(device==='kb')return {keys:shared?'arrowsPlay':'arrows',pads:null};if(/^pad\d$/.test(device||''))return {keys:null,pads:[+device.slice(3)]};if(/^kb\+pad\d$/.test(device||''))return {keys:shared?'arrowsPlay':'arrows',pads:[+device.slice(6)]};return {keys:'arrows',pads:'all'}}
function launchArcadeMatch(config){if(window.S9ArcadeActive)return Promise.reject(new Error('Una partita Arcade è già in corso'));return new Promise((resolve,reject)=>{
 const panel=document.createElement('div');panel.id='arcade-match';panel.style.cssText='position:fixed;inset:0;z-index:99999;background:#080e24;display:grid;place-items:center';panel.innerHTML='<canvas tabindex="0" width="1280" height="720"></canvas>';panel.setAttribute('role','dialog');panel.setAttribute('aria-label','Partita Arcade');document.body.append(panel);
 const devices=config.players?.length?config.players:[{team:0,device:'all'}],inputs=devices.map(d=>new E.InputManager(deviceOptions(d.device,devices))),input=inputs[0];inputs.forEach(i=>i.active=true);const m=new E.Match(input);setupTeam(m.teams[0],config.home,{...config.homeState,cleanNames:config.cleanNames});setupTeam(m.teams[1],config.away,{...config.awayState,cleanNames:config.cleanNames});if(window.S9ArcadeKits&&m.teams[0].kit&&m.teams[1].kit)m.teams[1].kit=S9ArcadeKits.resolve(m.teams[0].kit,m.teams[1].kit);m.setHumans(devices.map((d,i)=>({team:d.team,input:inputs[i]})));window.S9ArcadeDifficulty?.apply(m,config.difficulty);if(config.training)window.S9ArcadeTraining?.setup(m,config.training);m.rules.allowDraw=!!config.allowDraw;m.rules.offset=config.scoreOffset||[0,0];m.rules.awayGoals=config.awayGoals||null;m.restarts.kickoff(0);window.S9ArcadeEvolution?.setup(m,config);if(window.S9ArcadeKits&&m.teams[0].kit&&m.teams[1].kit)m.teams[1].kit=S9ArcadeKits.resolve(m.teams[0].kit,m.teams[1].kit);const renderer=new E.Renderer(panel.querySelector('canvas')),camera=new E.CameraController(),replay=new E.ReplayManager();renderer.camera=camera;const stadium=window.S9ArcadeStadium?.create();const canvas=panel.querySelector('canvas');for(const t of m.teams)renderer.bitmap?.(renderer.crestSource?.(t));
 let alive=true,previous=performance.now(),acc=0,score=0,finished=false,goalCelebration=null,paused=false,result=null;const close=()=>{config.onlineSession?.unbindMatch(window.S9ArcadeActive);alive=false;removeEventListener('keydown',onKey,true);stadium?.stop();inputs.forEach(i=>i.dispose());panel.remove();window.S9ArcadeActive=null;window.S9ArcadeMusicMuted=false;if(window.S9ArcadeMenuOpen)window.S9ArcadeMusic?.start()};// Keyboard / pad flow drawn on the canvas: ESC or START pauses, Z resumes, X leaves without recording; Z/ENTER continues after the result. Mouse optional.
 function proceed(){if(!finished||!result||m.presentationTime-m.elapsed<.8)return;close();resolve(result)}
 function onKey(e){if(!alive||/INPUT|SELECT|TEXTAREA/.test(e.target?.tagName))return;if(config.demo){e.preventDefault();e.stopImmediatePropagation();close();resolve({demo:'exit'});return}const physical=(e.key||'').toLowerCase(),B=window.S9ArcadeBindings,menuAction=B?B.keyboard('menu',e):({z:'confirm',enter:'confirm',' ':'confirm',x:'back',backspace:'back',arrowup:'arrowup',arrowdown:'arrowdown'})[physical],systemAction=B?B.keyboard('system',e):({escape:'pause',p:'settings',f:'fullscreen'})[physical];
  if(finished){if(menuAction==='confirm'){e.preventDefault();e.stopImmediatePropagation();proceed()}return}
  if(paused&&panel.querySelector('.evo-settings')){if(systemAction==='pause'){panel.querySelector('.evo-settings').remove();e.preventDefault();e.stopImmediatePropagation()}return}
  if(paused&&systemAction==='settings'){e.preventDefault();e.stopImmediatePropagation();window.S9ArcadeHub?.settings(panel);return}
  if(systemAction==='pause'){e.preventDefault();e.stopImmediatePropagation();paused=!paused;renderer.pauseIndex=0;inputs.forEach(i=>{i.onBlur();i.active=!paused});window.S9ArcadeActive&&(window.S9ArcadeActive.paused=paused);return}
  if(!paused||systemAction==='fullscreen')return;e.preventDefault();e.stopImmediatePropagation();const resume=()=>{paused=false;inputs.forEach(i=>{i.onBlur();i.active=true});window.S9ArcadeActive&&(window.S9ArcadeActive.paused=false)};
  if(menuAction==='arrowup'||menuAction==='arrowdown'){renderer.pauseIndex=((renderer.pauseIndex||0)+(menuAction==='arrowup'?2:1))%3;return}
  if(menuAction==='back'){resume();return}
  if(menuAction==='confirm'){const choice=renderer.pauseIndex||0;if(choice===0)resume();else if(choice===1)window.S9ArcadeHub?.settings(panel);else{close();resolve(null)}}}

 addEventListener('keydown',onKey,true);canvas.addEventListener?.('click',()=>{if(config.demo&&alive){close();resolve({demo:'exit'});return}if(finished)proceed()});if(config.demo)m.demo=config.demo;canvas.focus?.({preventScroll:true});
 window.S9ArcadeFinal?.configure(m,config.specialFinal);
 window.S9ArcadeActive={match:m,input,inputs,renderer,camera,paused:false,finished:false,control(action,value){if(!alive)return;if(action==='cancel'){close();resolve(null);return}if(action==='continue'){proceed();return}if(action==='skip'){if(replay.playback)replay.playback=null;if(goalCelebration)goalCelebration=null;inputs.forEach(i=>i.cancelShot());return}if(finished)return;if((action==='pause'&&(!paused||value!==true))||(action==='resume'&&paused&&!panel.querySelector('.evo-settings')))onKey({key:window.S9ArcadeBindings?.key('pause')||'escape',preventDefault(){},stopImmediatePropagation(){}})}};config.onlineSession?.bindMatch(window.S9ArcadeActive);
 window.S9ArcadeMusicMuted=true;window.stopMenuMusic?.();window.stopEventMusic?.();window.S9ArcadeMusic?.stop();stadium?.start();
 function frame(now){if(!alive)return;try{inputs.forEach(i=>i.poll());if(config.demo?.exit?.()){close();resolve({demo:'exit'});return}const dt=Math.min((now-previous)/1000,.1);previous=now;renderer.stadiumCelebration=stadium?.tick(dt);
 if(paused){renderer.draw(goalCelebration?{...m,goalCelebration}:m);renderer.pauseScreen?.(m);requestAnimationFrame(frame);return}
 if(finished){m.presentationTime+=dt;renderer.draw(m);if(config.demo&&m.presentationTime-m.elapsed>3){close();resolve({demo:'end'});return}requestAnimationFrame(frame);return}
 if(goalCelebration){goalCelebration.age+=dt;renderer.draw({...m,elapsed:m.elapsed+goalCelebration.age,goalCelebration});inputs.forEach(i=>{i.cancelShot();i.end(dt)});if(goalCelebration.age>=1.4){replay.start();goalCelebration=null}requestAnimationFrame(frame);return}
 if(replay.playback){if(inputs.map(i=>i.take('z')).some(Boolean)){replay.playback=null;inputs.forEach(i=>i.cancelShot())}else replay.draw(m,renderer,dt);inputs.forEach(i=>i.end(dt));requestAnimationFrame(frame);return}
 acc+=dt;while(acc>=1/120){config.demo?.step(m,1/120);m.update(1/120);inputs.forEach(i=>i.end(1/120));acc-=1/120}stadium?.observe(m);renderer.stadiumCelebration=stadium?.reaction;camera.update(m,dt);renderer.draw(m);panel.dataset.phase=m.phase;panel.querySelector('canvas').setAttribute('aria-label',m.teams[0].name+' '+m.rules.score[0]+' - '+m.rules.score[1]+' '+m.teams[1].name+' · '+m.phase);replay.record(m,dt,camera);
 const total=m.rules.score[0]+m.rules.score[1];if(total>score&&m.phase!=='FINISHED'){goalCelebration={age:0,team:m.scorers[m.scorers.length-1]?.team??0};score=total}
 if(m.phase==='FINISHED'){finished=true;m.presentationTime=m.elapsed;inputs.forEach(i=>i.active=false);window.S9ArcadeActive.finished=true;result={homeGoals:m.rules.score[0],awayGoals:m.rules.score[1],winner:!m.pen&&m.rules.leader()===null?null:(m.pen?m.pen.goals[0]>m.pen.goals[1]:m.rules.leader()===0)?config.home.id:config.away.id,scorers:m.scorers,stats:{...m.stats,penalties:m.pen?.goals||null,cards:(m.discipline||[]).map(({card,secondYellow,playerId,name,team,number,time})=>({card,secondYellow,playerId,name,team,number,time}))}};if(!config.demo)window.S9ArcadeEvolution?.record(m,result);m.resultSummary=result;requestAnimationFrame(frame);return}requestAnimationFrame(frame)}catch(error){close();reject(error)}}
 requestAnimationFrame(frame);
 });}
window.launchArcadeMatch=launchArcadeMatch;window.ArcadeMatchBridge={launchArcadeMatch,attributes,setupTeam,skinFor};
})();
